ALTER TABLE interest_spaces ADD COLUMN visibility TEXT NOT NULL DEFAULT 'public' CHECK(visibility IN ('public','private','secret'));
UPDATE interest_spaces SET visibility=CASE access WHEN 'approval' THEN 'private' ELSE 'public' END;
ALTER TABLE interest_spaces ADD COLUMN handle TEXT;
UPDATE interest_spaces SET handle='y-'||replace(id,'-','');
CREATE UNIQUE INDEX space_unique_handle ON interest_spaces(handle COLLATE NOCASE);
ALTER TABLE interest_spaces ADD COLUMN purpose TEXT NOT NULL DEFAULT 'Friendship';
ALTER TABLE interest_spaces ADD COLUMN subcategory TEXT NOT NULL DEFAULT '';
ALTER TABLE interest_spaces ADD COLUMN logo_key TEXT;
ALTER TABLE interest_spaces ADD COLUMN cover_key TEXT;
ALTER TABLE interest_spaces ADD COLUMN archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1));
CREATE INDEX spaces_visibility_updated ON interest_spaces(visibility,archived,updated_at);
ALTER TABLE space_channels ADD COLUMN read_only INTEGER NOT NULL DEFAULT 0 CHECK(read_only IN (0,1));
ALTER TABLE space_channels ADD COLUMN archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1));
ALTER TABLE space_channels ADD COLUMN position INTEGER NOT NULL DEFAULT 0;
ALTER TABLE space_posts ADD COLUMN locked INTEGER NOT NULL DEFAULT 0 CHECK(locked IN (0,1));
ALTER TABLE space_posts ADD COLUMN edited_at INTEGER;
CREATE TABLE space_invites(token_hash TEXT PRIMARY KEY,space TEXT NOT NULL REFERENCES interest_spaces(id) ON DELETE CASCADE,creator TEXT NOT NULL REFERENCES members(id),expires_at INTEGER NOT NULL,max_uses INTEGER NOT NULL CHECK(max_uses BETWEEN 1 AND 100),uses INTEGER NOT NULL DEFAULT 0,revoked INTEGER NOT NULL DEFAULT 0 CHECK(revoked IN (0,1)),created_at INTEGER NOT NULL);
CREATE INDEX space_invites_management ON space_invites(space,created_at);
CREATE TABLE space_invite_redemptions(id TEXT PRIMARY KEY,token_hash TEXT NOT NULL REFERENCES space_invites(token_hash),member TEXT NOT NULL REFERENCES members(id),created_at INTEGER NOT NULL,UNIQUE(token_hash,member));
CREATE TABLE space_messages(id TEXT PRIMARY KEY,space TEXT NOT NULL REFERENCES interest_spaces(id) ON DELETE CASCADE,channel TEXT NOT NULL REFERENCES space_channels(id),author TEXT NOT NULL REFERENCES members(id),body TEXT NOT NULL,reply_id TEXT REFERENCES space_messages(id),deleted INTEGER NOT NULL DEFAULT 0,edited_at INTEGER,created_at INTEGER NOT NULL);
CREATE INDEX space_messages_history ON space_messages(space,channel,created_at,id);
CREATE TABLE space_channel_follows(channel TEXT NOT NULL REFERENCES space_channels(id) ON DELETE CASCADE,member TEXT NOT NULL REFERENCES members(id),PRIMARY KEY(channel,member));
CREATE TABLE space_discussion_follows(post TEXT NOT NULL REFERENCES space_posts(id) ON DELETE CASCADE,member TEXT NOT NULL REFERENCES members(id),PRIMARY KEY(post,member));
ALTER TABLE space_reports ADD COLUMN message TEXT REFERENCES space_messages(id);
