'use client';
import {useState,useEffect,useRef} from 'react';
import {Phone,Video,Mic,MicOff,VideoOff,PhoneOff,Volume2,VolumeX} from 'lucide-react';
import {Modal} from './ui';
import {api} from '@/lib/services';
import {addRemoteTrack,playRemoteMedia} from '@/lib/call-media';
import {gatherRelaySdp} from '@/lib/call-ice';
import type {Friendship,Member} from '@/lib/community-model';
import type {CallRow} from '@/lib/call-service';
type Call=CallRow&{peer:Member};
export type CallIntent={friend:Friendship;mode:'voice'|'video';nonce:number};
export default function CallManager({me,intent,onClear}:{me:Member;intent:CallIntent|null;onClear:()=>void}){
 const [configured,setConfigured]=useState<boolean|null>(null),[phase,setPhase]=useState(''),[call,setCall]=useState<Call|null>(null),[incoming,setIncoming]=useState<Call|null>(null),[error,setError]=useState(''),[muted,setMuted]=useState(false),[camera,setCamera]=useState(true),[speaker,setSpeaker]=useState(true),[seconds,setSeconds]=useState(0),[busy,setBusy]=useState(false),[mediaReady,setMediaReady]=useState(false),[soundBlocked,setSoundBlocked]=useState(false),[remoteVisible,setRemoteVisible]=useState(false);
 const pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null),remote=useRef<MediaStream|null>(null),localVideo=useRef<HTMLVideoElement>(null),remoteVideo=useRef<HTMLVideoElement>(null),remoteAudio=useRef<HTMLAudioElement>(null),current=useRef<Call|null>(null),generation=useRef(0),connectedAt=useRef(0),currentPhase=useRef(''),speakerEnabled=useRef(true);currentPhase.current=phase;speakerEnabled.current=speaker;
 function cleanup(){generation.current++;pc.current?.close();pc.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;remote.current?.getTracks().forEach(t=>t.stop());remote.current=null;setMediaReady(false);connectedAt.current=0;setSoundBlocked(false);setRemoteVisible(false);}
 async function hangup(close=false){const c=current.current;cleanup();if(c)void api('/api/calls','POST',{action:'end',id:c.id}).catch(()=>{});current.current=null;setIncoming(null);setPhase(close?'':'ended');setBusy(false);if(close){setCall(null);onClear();}}
 function fail(e:unknown){const name=(e as Error).name;setError(name==='NotAllowedError'?'Camera or microphone permission was denied. Allow access in your browser and try again.':name==='NotFoundError'?'No microphone or camera was found. Connect a device and try again.':(e as Error).message||'The call failed. Please try again.');void hangup();}
 useEffect(()=>{void api('/api/calls?capabilities=1').then(r=>setConfigured(r.configured)).catch(()=>setConfigured(false));return()=>{generation.current++;pc.current?.close();stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{if(intent&&!current.current){setPhase('confirm');setError('');setIncoming(null);}},[intent?.nonce]);
 useEffect(()=>{if(call||phase==='confirm'||phase==='ended')return;let dead=false,inFlight=false;const check=async()=>{if(inFlight||document.hidden||!navigator.onLine)return;inFlight=true;try{const r=await api('/api/calls');if(!dead&&r.call)setIncoming(r.call);else if(!dead)setIncoming(null);}catch{}finally{inFlight=false;}};void check();const t=setInterval(check,2500);return()=>{dead=true;clearInterval(t);};},[call?.id,phase]);
 useEffect(()=>{if(!call?.id||phase==='ended')return;let stopped=false,inFlight=false;const check=async()=>{if(inFlight||!navigator.onLine)return;inFlight=true;try{const r=await api('/api/calls?id='+call.id);if(stopped)return;const c=r.call as Call|null;if(!c||['ended','declined'].includes(c.state)){setError(c?.state==='declined'?'Your Yaaro declined the call.':'This call has ended.');cleanup();current.current=null;setPhase('ended');return;}current.current=c;setCall(c);if(c.answer&&c.caller===me.id&&pc.current?.signalingState==='have-local-offer')await pc.current.setRemoteDescription({type:'answer',sdp:c.answer});if(c.state==='connecting'&&c.answer&&pc.current?.connectionState==='connected')await api('/api/calls','POST',{action:'connected',id:c.id});}catch(e){if(!stopped)fail(e);}finally{inFlight=false;}};void check();const t=setInterval(check,1500);return()=>{stopped=true;clearInterval(t);};},[call?.id,me.id,phase]);
 useEffect(()=>{if(phase!=='connected')return;const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-connectedAt.current)/1000)),1000);const pulse=setInterval(()=>{const id=current.current?.id;if(id)void api('/api/calls','POST',{action:'pulse',id}).catch(fail);},20000);return()=>{clearInterval(timer);clearInterval(pulse);};},[phase]);
 function playIncoming(){const media=remote.current,token=generation.current;if(!media)return;void playRemoteMedia(remoteVideo.current,remoteAudio.current,media,speakerEnabled.current).then(blocked=>{if(token===generation.current)setSoundBlocked(blocked);});}
 useEffect(()=>{if(mediaReady){if(localVideo.current)localVideo.current.srcObject=stream.current;playIncoming();}},[mediaReady,call?.mode,speaker]);
 useEffect(()=>{if(!call?.id||phase==='ended')return;const beforeUnload=()=>{stream.current?.getTracks().forEach(t=>t.stop());void fetch('/api/calls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'end',id:call.id}),keepalive:true}).catch(()=>{});};window.addEventListener('pagehide',beforeUnload);return()=>window.removeEventListener('pagehide',beforeUnload);},[call?.id,phase]);
 async function createPeer(c:Call){const token=generation.current;const config=await api(`/api/calls?id=${c.id}&ice=1`);if(token!==generation.current)throw new Error('Call cancelled.');if(!navigator.mediaDevices?.getUserMedia||!window.RTCPeerConnection)throw new Error('Calling is unavailable in this browser. Open YAARO in a current browser over HTTPS.');const media=await navigator.mediaDevices.getUserMedia({audio:true,video:c.mode==='video'?{width:{ideal:640},height:{ideal:480},facingMode:'user'}:false});if(token!==generation.current){media.getTracks().forEach(t=>t.stop());throw new Error('Call cancelled.');}stream.current=media;const peer=new RTCPeerConnection({...config,iceTransportPolicy:'relay'});pc.current=peer;media.getTracks().forEach(t=>peer.addTrack(t,media));remote.current=new MediaStream();peer.ontrack=e=>{if(peer!==pc.current)return;addRemoteTrack(remote.current!,e.track);playIncoming();e.track.onunmute=()=>{if(peer===pc.current)playIncoming();};};peer.onconnectionstatechange=()=>{if(peer!==pc.current)return;if(peer.connectionState==='connected'){if(!connectedAt.current){connectedAt.current=Date.now();setSeconds(0);}setError('');setPhase('connected');}if(peer.connectionState==='failed')fail(new Error('The call could not connect. Please check your network and try again.'));if(peer.connectionState==='disconnected')setError('Connection interrupted. Trying to reconnect…');};setMediaReady(true);setMuted(false);setCamera(true);setSpeaker(true);return peer;}
 const gather=gatherRelaySdp;
 async function start(){if(!intent||busy||!configured)return;setBusy(true);setPhase('preparing');setError('');let c:Call|null=null;try{const id=crypto.randomUUID();await api('/api/calls','POST',{action:'start',id,conversation:intent.friend.id,mode:intent.mode});c={id,conversation:intent.friend.id,caller:me.id,callee:intent.friend.person.id,mode:intent.mode,state:'ringing',offer:null,answer:null,created_at:Date.now(),updated_at:Date.now(),peer:intent.friend.person};current.current=c;setCall(c);const peer=await createPeer(c);await peer.setLocalDescription(await peer.createOffer());const sdp=await gather(peer);if(peer!==pc.current)return;await api('/api/calls','POST',{action:'offer',id:c.id,sdp});if(currentPhase.current!=='connected')setPhase('ringing');}catch(e){fail(e);}finally{setBusy(false);}}
 async function accept(){if(!incoming||busy)return;setBusy(true);const c=incoming;setIncoming(null);setCall(c);current.current=c;setPhase('preparing');setError('');try{const availability=await api('/api/calls?capabilities=1');setConfigured(availability.configured);if(!availability.configured)throw new Error('Calling is unavailable. Please check the private relay configuration.');await api('/api/calls','POST',{action:'accept',id:c.id});const peer=await createPeer(c);await peer.setRemoteDescription({type:'offer',sdp:c.offer!});await peer.setLocalDescription(await peer.createAnswer());const sdp=await gather(peer);if(peer!==pc.current)return;await api('/api/calls','POST',{action:'answer',id:c.id,sdp});if(currentPhase.current!=='connected')setPhase('connecting');}catch(e){fail(e);}finally{setBusy(false);}}
 async function decline(){const id=incoming?.id;if(id)try{await api('/api/calls','POST',{action:'decline',id});setIncoming(null);}catch(e){setError((e as Error).message);}}
 function toggleMic(){const tracks=stream.current?.getAudioTracks()||[];tracks.forEach(t=>t.enabled=muted);setMuted(!muted);}
 function toggleCamera(){stream.current?.getVideoTracks().forEach(t=>t.enabled=!camera);setCamera(!camera);}
 function toggleSound(){setSpeaker(!speaker);}
 if(!phase&&!incoming)return null;
 if(incoming&&!phase)return <Modal title={`Incoming ${incoming.mode} call`} onClose={()=>void decline()}><div className="real-call-incoming"><span className="call-orb">{incoming.mode==='video'?<Video/>:<Phone/>}</span><h2>{incoming.peer.name} is calling.</h2><p>Your camera and microphone stay off until you accept.</p>{!incoming.offer&&<p role="status">The caller is preparing the secure connection…</p>}{error&&<p role="alert">{error}</p>}<div className="inline-actions"><button className="button primary" onClick={accept} disabled={busy||!incoming.offer}>Accept {incoming.mode} call</button><button className="button outline" onClick={decline} disabled={busy}>Decline</button></div></div></Modal>;
 if(phase==='confirm')return <Modal title={intent?.mode==='video'?'Video call':'Voice call'} onClose={()=>{setPhase('');onClear();}}><div className="real-call-incoming"><span className="call-orb">{intent?.mode==='video'?<Video/>:<Phone/>}</span><h2>Call {intent?.friend.person.name}?</h2><p>{configured?'Starting asks your browser for microphone'+(intent?.mode==='video'?' and camera':'')+' permission. Your Yaaro must accept to join.':configured===null?'Checking calling availability…':'Voice and video are waiting for a configured private relay. Your camera and microphone have not been accessed.'}</p><button className="button primary wide" onClick={start} disabled={busy||!configured}>Start {intent?.mode} call</button></div></Modal>;
 return <Modal title={call?.mode==='video'?'YAARO video call':'YAARO voice call'} onClose={()=>void hangup(true)}><div className="real-call-stage"><div className="real-call-status"><b>{call?.peer.name||intent?.friend.person.name}</b><span role="status">{phase==='connected'?`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`:phase==='preparing'?'Preparing your call…':phase==='ringing'?'Waiting for your Yaaro…':phase==='connecting'?'Connecting securely…':'Call ended'}</span></div>{call?.mode==='video'&&phase!=='ended'?<div className="real-video-grid"><video ref={remoteVideo} autoPlay playsInline muted onPlaying={()=>setRemoteVisible(true)} onWaiting={()=>setRemoteVisible(false)} aria-label="Your Yaaro’s video"/><video ref={localVideo} autoPlay playsInline muted aria-label="Your camera preview" className={!camera?'camera-off':''}/>{!remoteVisible&&<span className="remote-video-status" role="status">{phase==='connected'?'Waiting for your Yaaro’s camera…':'Your Yaaro’s video appears once the call connects.'}</span>}{!camera&&<span className="camera-off-label">Your camera is off</span>}</div>:<div className="real-call-voice"><span className="call-orb"><Phone size={34}/></span><p>{phase==='connected'?'You’re connected. Make yourself at home.':phase==='ended'?'A little hello can happen another time.':'Your conversation is on its way.'}</p></div>}{phase!=='ended'&&<audio ref={remoteAudio} autoPlay muted={!speaker}/>} {soundBlocked&&<div className="form-notice" role="status">Tap Enable sound to hear your Yaaro.<button className="text-link" onClick={playIncoming}>Enable sound</button></div>}{error&&<div className="form-notice" role="alert">{error}</div>}{phase!=='ended'?<div className="real-call-controls"><button className="icon-button" aria-label={muted?'Unmute microphone':'Mute microphone'} aria-pressed={muted} onClick={toggleMic} disabled={!mediaReady}>{muted?<MicOff/>:<Mic/>}</button>{call?.mode==='video'&&<button className="icon-button" aria-label={camera?'Turn camera off':'Turn camera on'} aria-pressed={!camera} onClick={toggleCamera} disabled={!mediaReady}>{camera?<Video/>:<VideoOff/>}</button>}<button className="icon-button" aria-label={speaker?'Mute call audio':'Enable call audio'} aria-pressed={!speaker} onClick={toggleSound}>{speaker?<Volume2/>:<VolumeX/>}</button><button className="button call-end" onClick={()=>void hangup()}><PhoneOff size={20}/> End call</button></div>:<button className="button primary wide" onClick={()=>{setCall(null);setPhase('');setError('');onClear();}}>Back to YAARO</button>}<p className="small-note">Private relay connection. Calls are not recorded by YAARO. Maximum call length: 60 minutes.</p></div></Modal>;
}
