'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,Video,SwitchCamera,X,Check,RotateCcw,Zap,ZapOff} from 'lucide-react';
export default function CameraCapture({disabled,onCapture,photoAction='Use photo',allowVideo=true}:{disabled:boolean;onCapture:(file:File)=>Promise<boolean|void>;photoAction?:string;allowVideo?:boolean}){
 const [state,setState]=useState<'idle'|'opening'|'live'|'review'>('idle'),[error,setError]=useState(''),[front,setFront]=useState(false),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState(''),[working,setWorking]=useState(false),[torch,setTorch]=useState(false),[torchSupported,setTorchSupported]=useState(false),[torchBusy,setTorchBusy]=useState(false);
 const stream=useRef<MediaStream|null>(null),video=useRef<HTMLVideoElement|null>(null),nativeVideo=useRef<HTMLInputElement>(null),nativePhoto=useRef<HTMLInputElement>(null),generation=useRef(0);
 const stop=()=>{generation.current++;setTorch(false);setTorchSupported(false);setTorchBusy(false);stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(video.current)video.current.srcObject=null;};
 useEffect(()=>{const hide=()=>{if(document.hidden){stop();setState(value=>value==='review'?value:'idle');}};document.addEventListener('visibilitychange',hide);return()=>{stop();document.removeEventListener('visibilitychange',hide);};},[]);
 useEffect(()=>{if(!photo){setPreview('');return;}const url=URL.createObjectURL(photo);setPreview(url);return()=>URL.revokeObjectURL(url);},[photo]);
 useEffect(()=>{if(state==='live'&&video.current&&stream.current){video.current.srcObject=stream.current;void video.current.play().catch(()=>setError('Tap the camera preview to start it.'));}},[state]);
 async function start(useFront=front){stop();setPhoto(null);setError('');setState('opening');const current=generation.current;
  try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access is unavailable. Try your device camera below.');const next=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:useFront?'user':'environment'},width:{ideal:1280},height:{ideal:720}}});if(current!==generation.current){next.getTracks().forEach(track=>track.stop());return;}stream.current=next;const track=next.getVideoTracks()[0];const caps=track?.getCapabilities?.() as (MediaTrackCapabilities & {torch?:boolean})|undefined;setTorchSupported(caps?.torch===true);setTorch(false);setFront(track?.getSettings().facingMode?track.getSettings().facingMode==='user':useFront);setState('live');}
  catch(e){if(current!==generation.current)return;setState('idle');const name=(e as Error).name;setError(name==='NotAllowedError'?'Camera permission was denied. Allow it in your browser, or use your device camera.':name==='NotFoundError'?'No camera was found. Choose a photo from Gallery.':name==='NotReadableError'?'Your camera is in use. Close the other camera app and try again.':(e as Error).message);}
 }
 async function toggleTorch(){const track=stream.current?.getVideoTracks()[0];if(!track||!torchSupported||torchBusy)return;const current=generation.current;setTorchBusy(true);setError('');try{await track.applyConstraints({advanced:[{torch:!torch} as MediaTrackConstraintSet]});if(current!==generation.current)return;const settings=track.getSettings() as MediaTrackSettings & {torch?:boolean};if(settings.torch!==!torch)throw new Error('This browser could not switch the flashlight. Try your device camera.');setTorch(settings.torch);}catch(e){if(current===generation.current)setError((e as Error).message);}finally{if(current===generation.current)setTorchBusy(false);}}
 async function takePhoto(){const element=video.current;if(!element?.videoWidth||!element.videoHeight){setError('Your camera is still starting. Try again in a moment.');return;}const current=generation.current;setWorking(true);setError('');try{
  const scale=Math.min(1,1280/Math.max(element.videoWidth,element.videoHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(element.videoWidth*scale);canvas.height=Math.round(element.videoHeight*scale);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Unable to capture a photo. Try your device camera.');ctx.drawImage(element,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Unable to capture this photo.')),'image/jpeg',.9));if(current!==generation.current)return;stop();setPhoto(new File([blob],'yaaro-camera.jpg',{type:'image/jpeg'}));setState('review');
 }catch(e){if(current===generation.current)setError((e as Error).message);}finally{setWorking(false);}}
 async function usePhoto(){if(!photo)return;setWorking(true);try{const accepted=await onCapture(photo);if(accepted!==false){setPhoto(null);setState('idle');}}catch(e){setError((e as Error).message);}finally{setWorking(false);}}
 async function nativeSelected(file?:File){if(!file)return;stop();setWorking(true);setError('');try{await onCapture(file);}catch(e){setError((e as Error).message);}finally{setWorking(false);}}
 function close(){stop();setPhoto(null);setError('');setState('idle');}
 return <div className="camera-capture">
 <input ref={nativeVideo} type="file" hidden accept="video/*" capture="environment" aria-label="Record a camera video" onChange={event=>{const file=event.target.files?.[0];event.target.value='';void nativeSelected(file);}}/>
 <input ref={nativePhoto} type="file" hidden accept="image/*" capture="environment" aria-label="Take a photo using your device camera" onChange={event=>{const file=event.target.files?.[0];event.target.value='';void nativeSelected(file);}}/>
 {state==='idle'?<div className={`camera-entry-options ${!allowVideo?'photo-only':''}`}><button type="button" disabled={disabled||working} onClick={()=>void start()}><Camera size={22}/><span><b>Camera</b><small>Take a photo</small></span></button>{allowVideo&&<button type="button" disabled={disabled||working} onClick={()=>{stop();nativeVideo.current?.click();}}><Video size={22}/><span><b>Record video</b><small>Phone camera · up to 10 seconds</small></span></button>}</div>:<div className="camera-workspace"><div className="camera-workspace-heading"><b>{state==='review'?'Your photo':state==='opening'?'Opening camera…':'Camera'}</b><button className="icon-button" type="button" onClick={close} aria-label="Close camera" disabled={working}><X size={19}/></button></div>{state==='opening'&&<p className="small-note" role="status">Allow camera access in your browser to continue.</p>}{state==='live'&&<><video ref={video} autoPlay muted playsInline className={front?'camera-front':''} aria-label="Live camera preview" onClick={event=>void event.currentTarget.play().catch(()=>{})}/><div className="camera-workspace-actions"><button className="button outline small camera-torch" type="button" disabled={!torchSupported||torchBusy||working} aria-pressed={torch} aria-label={torch?'Turn flashlight off':'Turn flashlight on'} title={torchSupported?'Toggle camera flashlight':'Flashlight unavailable on this camera or browser'} onClick={()=>void toggleTorch()}>{torch?<Zap size={18}/>:<ZapOff size={18}/>} {torchBusy?'Switching…':torch?'Flash on':'Flash off'}</button><button className="button outline small" type="button" disabled={working||torchBusy} onClick={()=>void start(!front)}><SwitchCamera size={18}/> Flip</button><button className="button primary" type="button" disabled={working||torchBusy} onClick={()=>void takePhoto()}><Camera size={18}/> Take photo</button></div>{!torchSupported&&<p className="small-note">Flashlight is unavailable on this camera. Try the rear camera or your phone’s camera app.</p>}</>}{state==='review'&&<><img src={preview} alt="Review your camera photo"/><div className="camera-workspace-actions"><button className="button outline small" type="button" disabled={working||disabled} onClick={()=>void start()}><RotateCcw size={16}/> Retake</button><button className="button primary" type="button" disabled={working||disabled} onClick={()=>void usePhoto()}><Check size={17}/>{working?'Preparing…':photoAction}</button></div></>}</div>}
 {error&&<div className="form-notice" role="alert">{error}<button className="text-link" type="button" disabled={disabled||working} onClick={()=>nativePhoto.current?.click()}><Camera size={15}/> Use device camera</button></div>}
 {state==='idle'&&allowVideo&&<p className="small-note camera-device-note">Video uses your phone’s recorder and its flash controls where supported. Use Gallery for an MP4 or compatible H.264 MOV. On iPhone, choose Camera → Formats → Most Compatible if a recording is unsupported.</p>}
 </div>;
}
