'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Camera,Mic,Square,X,Send,Video} from 'lucide-react';
import {Modal} from './ui';
import {prepareChatPhoto,prepareMomentVideo,captureVoice,type VoiceCapture} from '@/lib/media-browser';
export default function ChatMediaTools({conversation,disabled,onSaved}:{conversation:string;disabled:boolean;onSaved:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[error,setError]=useState(''),[voiceBlob,setVoiceBlob]=useState<Blob|null>(null),[voiceUrl,setVoiceUrl]=useState('');const input=useRef<HTMLInputElement>(null),capture=useRef<VoiceCapture|null>(null),epoch=useRef(0),started=useRef(0),timer=useRef<ReturnType<typeof setInterval>|null>(null),uploadIds=useRef(new WeakMap<Blob,string>());
 function cancel(){capture.current?.cancel();capture.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;setRecording(false);setSeconds(0);setVoiceBlob(null);}
 useEffect(()=>()=>{epoch.current++;capture.current?.cancel();if(timer.current)clearInterval(timer.current);},[conversation]);
 useEffect(()=>{if(!voiceBlob){setVoiceUrl('');return;}const url=URL.createObjectURL(voiceBlob);setVoiceUrl(url);return()=>URL.revokeObjectURL(url);},[voiceBlob]);
 async function upload(blob:Blob,kind:'photo'|'voice'|'video',token:number){let id=uploadIds.current.get(blob);if(!id){id=crypto.randomUUID();uploadIds.current.set(blob,id);}const params=new URLSearchParams({id,conversation,kind}),response=await fetch('/api/chat-media?'+params,{method:'POST',headers:{'Content-Type':blob.type},body:blob}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||'Unable to send this attachment.');if(token===epoch.current){await onSaved();setVoiceBlob(null);setOpen(false);}}
 async function photo(file?:File){if(!file)return;const token=epoch.current;setBusy(true);setError('');try{const video=file.type==='video/mp4';await upload(video?await prepareMomentVideo(file):await prepareChatPhoto(file),video?'video':'photo',token);}catch(e){if(token===epoch.current)setError((e as Error).message);}finally{if(token===epoch.current)setBusy(false);if(input.current)input.current.value='';}}
 async function startRecording(){const token=epoch.current;setBusy(true);setError('');try{const next=await captureVoice();if(token!==epoch.current){next.cancel();return;}capture.current=next;started.current=Date.now();setSeconds(0);setRecording(true);timer.current=setInterval(()=>{setSeconds(Math.min(60,Math.floor((Date.now()-started.current)/1000)));if(Date.now()-started.current>=60000)void sendVoice(false);},1000);}catch(e){if(token===epoch.current)setError((e as Error).name==='NotAllowedError'?'Microphone permission was denied. Allow it in your browser to record a voice note.':(e as Error).message);}finally{if(token===epoch.current)setBusy(false);}}
 async function sendVoice(send=true){const active=capture.current;if(!active)return;capture.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;const token=epoch.current;setBusy(true);setRecording(false);try{const blob=await active.stop();if(token!==epoch.current)return;setVoiceBlob(blob);if(send)await upload(blob,'voice',token);}catch(e){if(token===epoch.current)setError((e as Error).message);}finally{if(token===epoch.current)setBusy(false);}}
 async function retryVoice(){if(!voiceBlob)return;const token=epoch.current;setBusy(true);setError('');try{await upload(voiceBlob,'voice',token);}catch(e){if(token===epoch.current)setError((e as Error).message);}finally{if(token===epoch.current)setBusy(false);}}
 return <>
 <input type="file" ref={input} hidden accept="image/jpeg,image/png,image/webp,video/mp4" aria-label="Choose a chat photo or video" onChange={event=>void photo(event.target.files?.[0])}/>
 <button type="button" className="icon-button" aria-label="Send a photo, video or voice note" disabled={disabled||busy} onClick={()=>{setError('');setOpen(true);}}><Plus size={20}/></button>
 {open&&<Modal title="Share a little more" onClose={()=>{epoch.current++;cancel();setBusy(false);setOpen(false);}}><div className="media-share-options">
 {recording?<><div className="voice-recording" role="status"><span/><Mic size={25}/><b>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</b><p>Recording · up to 60 seconds</p></div><div className="inline-actions"><button className="button primary" type="button" onClick={()=>void sendVoice(true)}><Square size={16}/> Stop & send</button><button className="button outline" type="button" onClick={cancel}><X size={16}/> Cancel</button></div></>:voiceBlob?<><audio controls src={voiceUrl} aria-label="Preview your voice note"/><div className="inline-actions"><button type="button" className="button primary" disabled={busy} onClick={()=>void retryVoice()}><Send size={16}/> Send voice note</button><button type="button" className="button outline" disabled={busy} onClick={()=>setVoiceBlob(null)}>Discard</button></div></>:<><button type="button" disabled={busy} onClick={()=>input.current?.click()}><Camera size={25}/><span><b>Photo or video · View once</b><small>Photo up to 5 MB · MP4 video up to 10 seconds / 12 MB</small></span><Send size={17}/></button><button type="button" disabled={busy} onClick={()=>void startRecording()}><Mic size={25}/><span><b>Voice note</b><small>Microphone starts only when you tap here</small></span><Send size={17}/></button></>}
 {busy&&<p role="status">Preparing and sending…</p>}{error&&<p className="form-notice" role="alert">{error}</p>}<p className="small-note">Photos and videos can be opened once by the receiver and vanish on closing. Screenshots and screen recording cannot be blocked or detected on the web.</p>
 </div></Modal>}
 </>;
}
