'use client';
import {useState,useRef,useEffect,type FormEvent} from 'react';
import {ArrowLeft,ArrowRight,Check,Users,Globe2,LockKeyhole,EyeOff,ShieldCheck,Hash} from 'lucide-react';
import {spaceDetails,spacePurposes,spaceTopics} from '@/lib/spaces-model';
import {languages} from '@/lib/data';
import {spaceApi as api} from '@/lib/spaces-browser';
import {CommunityImagePicker,uploadCommunityImage} from './community-premium';
const initialRules='Be kind. Respect privacy and boundaries. No harassment, scams, spam, or sexual content. Share useful contributions and give credit. Report concerns to moderators.';
export default function CommunityBuilder({onCreated,onBusyChange}:{onCreated:(id:string)=>void;onBusyChange?:(busy:boolean)=>void}){
 const id=useRef(crypto.randomUUID()),created=useRef(false),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [draft,setDraft]=useState({name:'',handle:'',description:'',topic:'Music' as typeof spaceTopics[number],subcategory:'',purpose:'Friendship' as typeof spacePurposes[number],language:'English',visibility:'public' as 'public'|'private'|'secret',access:'open' as 'open'|'approval',rules:initialRules});
 const [logo,setLogo]=useState<Blob|null>(null),[cover,setCover]=useState<Blob|null>(null),[channels,setChannels]=useState(['General','Introductions','Ask & share']),[preview,setPreview]=useState({logo:'',cover:''});
 useEffect(()=>{onBusyChange?.(busy);},[busy,onBusyChange]);
 useEffect(()=>{const next={logo:logo?URL.createObjectURL(logo):'',cover:cover?URL.createObjectURL(cover):''};setPreview(next);return()=>{Object.values(next).forEach(url=>{if(url)URL.revokeObjectURL(url);});};},[logo,cover]);
 function validate(){if(step===0)spaceDetails.pick({name:true,handle:true,description:true}).parse(draft);if(step===1)spaceDetails.pick({topic:true,purpose:true,language:true,subcategory:true}).parse(draft);if(step===2)spaceDetails.pick({visibility:true}).parse(draft);if(step===3){spaceDetails.pick({rules:true}).parse(draft);if(channels.some(c=>c.trim().length<2||c.trim().length>30)||new Set(channels.map(c=>c.trim().toLowerCase())).size!==3)throw Error('Choose three different channel names, each 2–30 characters.');}}
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setError('');try{validate();if(step<4){setStep(step+1);return;}setBusy(true);const details=spaceDetails.parse({...draft,access:draft.visibility==='public'?'open':'approval'});await api('/api/spaces','POST',created.current?{action:'edit',space:id.current,details}:{action:'create',id:id.current,details});created.current=true;const detail=await api('/api/spaces?space='+id.current);if(detail.channels.some((channel:any,i:number)=>i<3&&channel.name!==channels[i].trim())){for(let i=0;i<3;i++){const channel=detail.channels[i];if(channel)await api('/api/spaces','POST',{action:'channelControl',space:id.current,channel:channel.id,name:'setup-'+channel.id.slice(0,8),description:channel.description,readOnly:!!channel.read_only,archived:false,position:i});}for(let i=0;i<3;i++){const channel=detail.channels[i];if(channel)await api('/api/spaces','POST',{action:'channelControl',space:id.current,channel:channel.id,name:channels[i].trim(),description:channel.description,readOnly:!!channel.read_only,archived:false,position:i});}}if(logo)await uploadCommunityImage(id.current,'logo',logo);if(cover)await uploadCommunityImage(id.current,'cover',cover);onCreated(id.current);}catch(e){setError((e as {issues?:{message:string}[]}).issues?.[0]?.message||(e as Error).message);}finally{setBusy(false);onBusyChange?.(false);}}
 const titles=['Give your people a place.','What brings you together?','Open doors. Clear boundaries.','Make it feel like home.','Your community, ready.'];
 return <form className="space-form community-builder premium-builder" onSubmit={submit}>
  <div className="community-builder-progress" aria-label={`Step ${step+1} of 5`}>{['Identity','Purpose','Privacy','Setup','Preview'].map((label,index)=><span key={label} className={index<=step?'active':''} aria-current={index===step?'step':undefined}><i>{index<step?<Check size={13}/>:index+1}</i><b>{label}</b></span>)}</div>
  <div className="community-builder-copy"><span className="eyebrow">STEP {step+1} OF 5</span><h2>{titles[step]}</h2><p>{['Start with a name, a story, and a look that feels like you.','Help the right people find a little common ground.','Choose who can discover and join your community.','Give conversations a direction and set a shared standard.','This is how your community will appear to your people.'][step]}</p></div>
  {step===0&&<><label>Community name<input required minLength={3} maxLength={60} value={draft.name} placeholder="Tamil Indie Music Club" onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Unique handle<div className="community-handle-field"><span>@</span><input required minLength={3} maxLength={40} pattern="[a-z0-9][a-z0-9-]{2,39}" value={draft.handle} placeholder="tamil-indie-music" onChange={e=>setDraft({...draft,handle:e.target.value.toLowerCase()})}/></div></label><label>A little about your community<textarea required minLength={20} maxLength={700} value={draft.description} placeholder="Discover independent artists, swap playlists, and talk about the songs we love." onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="community-branding-grid"><CommunityImagePicker kind="logo" onChange={setLogo}/><CommunityImagePicker kind="cover" onChange={setCover}/></div></>}
  {step===1&&<><div className="space-form-grid"><label>Purpose<select value={draft.purpose} onChange={e=>setDraft({...draft,purpose:e.target.value as typeof draft.purpose})}>{spacePurposes.map(value=><option key={value}>{value}</option>)}</select></label><label>Category<select value={draft.topic} onChange={e=>setDraft({...draft,topic:e.target.value as typeof draft.topic})}>{spaceTopics.map(value=><option key={value}>{value}</option>)}</select></label></div><label>Topics / subcategory (optional)<input maxLength={60} value={draft.subcategory} placeholder="Indie artists, playlists, songwriting" onChange={e=>setDraft({...draft,subcategory:e.target.value})}/></label><label>Language<select value={draft.language} onChange={e=>setDraft({...draft,language:e.target.value})}>{[...languages,'Multilingual'].map(value=><option key={value}>{value}</option>)}</select></label></>}
  {step===2&&<div className="community-visibility-options">{([['public','Public','Anyone can discover it and agree to the rules to join.',Globe2],['private','Private','People can discover the overview. Hosts approve membership.',LockKeyhole],['secret','Secret','Hidden from discovery. A valid invitation grants access.',EyeOff]] as const).map(([value,title,description,Icon])=><button key={value} type="button" className={draft.visibility===value?'selected':''} aria-pressed={draft.visibility===value} onClick={()=>setDraft({...draft,visibility:value})}><Icon size={22}/><span><b>{title}</b><small>{description}</small></span>{draft.visibility===value&&<Check size={18}/>}</button>)}</div>}
  {step===3&&<><label>Community rules<textarea required minLength={20} maxLength={2000} value={draft.rules} onChange={e=>setDraft({...draft,rules:e.target.value})}/></label><fieldset className="community-default-channels"><legend>Your first three channels</legend>{channels.map((name,index)=><label key={index}><Hash size={16}/><input required minLength={2} maxLength={30} value={name} aria-label={`Channel ${index+1} name`} onChange={e=>setChannels(channels.map((value,i)=>i===index?e.target.value:value))}/></label>)}</fieldset><p className="space-form-note"><ShieldCheck size={17}/>{draft.visibility==='private'?'Hosts approve every membership request.':'People agree to your rules before joining.'} You can manage channels and member roles after launch.</p></>}
  {step===4&&<><article className="community-preview launch-preview"><div className="launch-preview-cover">{preview.cover&&<img src={preview.cover} alt="Your community cover preview"/>}<span>{draft.topic} · {draft.language}</span></div><div className="launch-preview-copy"><span className="community-preview-emblem">{preview.logo?<img src={preview.logo} alt="Your community logo preview"/>:<Users size={28}/>}</span><small>{draft.visibility.toUpperCase()} COMMUNITY</small><h2>{draft.name}</h2><b>@{draft.handle}</b><p>{draft.description}</p><div><span>{draft.purpose}</span>{draft.subcategory&&<span>{draft.subcategory}</span>}</div></div></article><div className="community-launch-checks">{channels.map(name=><span key={name}><Hash size={16}/>{name}</span>)}</div><p className="space-muted">You’re the owner. Start with an introduction and invite a few people who share your interest.</p></>}
  {error&&<p className="form-notice" role="alert">{error} Your choices are kept here.</p>}
  <div className="community-builder-actions">{step>0&&<button type="button" className="button outline" disabled={busy} onClick={()=>{setError('');setStep(step-1);}}><ArrowLeft size={16}/> Back</button>}<button type="submit" className="button primary" disabled={busy}>{busy?'Creating…':step===4?'Create Community':'Continue'}<ArrowRight size={16}/></button></div>
 </form>;
}
