'use client';
import {useEffect,useState} from 'react';
import {CalendarDays,Clock,ArrowUpRight,Search,ArrowLeft,ArrowRight} from 'lucide-react';
import {spaceApi as api} from '@/lib/spaces-browser';
import type {SpaceEvent} from '@/lib/spaces-model';
import {Empty} from './ui';
export default function CommunityEvents({onOpen}:{onOpen:(id:string)=>void}){
 const [view,setView]=useState('upcoming'),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[rows,setRows]=useState<(SpaceEvent&{space:string;spaceName:string;coverUrl:string|null})[]>([]),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let stop=false;setLoading(true);const timer=setTimeout(()=>void api(`/api/spaces?myEvents=1&view=${view}&offset=${offset}&q=${encodeURIComponent(query)}`).then(r=>{if(!stop){setRows(r.events);setMore(r.hasMore);setError('');}}).catch(e=>{if(!stop)setError(e.message);}).finally(()=>{if(!stop)setLoading(false);}),180);return()=>{stop=true;clearTimeout(timer);};},[view,query,offset,retry]);
 return <section className="premium-events"><div className="social-heading"><span className="eyebrow">MAKE TIME FOR YOUR PEOPLE</span><h1>Good things happen together.</h1><p>Meetups and shared plans from the communities you’ve joined.</p></div><div className="premium-event-tools"><div className="spaces-mode">{[['upcoming','Upcoming'],['plans','My plans'],['past','Past']].map(([id,label])=><button key={id} aria-pressed={view===id} className={view===id?'selected':''} onClick={()=>{setView(id);setOffset(0);}}>{label}</button>)}</div><label className="spaces-search"><Search size={18}/><input value={query} maxLength={100} placeholder="Search events or communities" aria-label="Search your community events" onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label></div>{error&&<div className="real-error" role="alert">{error}<button onClick={()=>setRetry(retry+1)}>Retry</button></div>}{loading?<div className="spaces-skeleton" aria-label="Loading events" role="status"><div/><div/></div>:rows.length?<div className="premium-event-grid">{rows.map(event=><article className="premium-event-card" key={event.id}><div className="premium-event-cover">{event.coverUrl?<img src={event.coverUrl} alt="" loading="lazy"/>:<CalendarDays size={48} strokeWidth={1}/>}<div className="premium-event-date"><b>{new Date(event.starts_at).getDate()}</b><span>{new Date(event.starts_at).toLocaleDateString([],{month:'short'})}</span></div></div><div className="premium-event-copy"><small>{event.spaceName}</small><h2>{event.title}</h2><p>{event.description}</p><span><Clock size={14}/>{new Date(event.starts_at).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</span><div><small>{event.going} going{event.myRsvp==='going'?' · You’re going':event.myRsvp==='interested'?' · Interested':''}</small><button className="button outline small" onClick={()=>onOpen(event.space)}>View event <ArrowUpRight size={15}/></button></div></div></article>)}</div>:<Empty title={view==='plans'?'Make room for a good gathering.':'Your next shared plan starts here.'} description="Events from your joined communities appear here. Open a community’s Events tab to RSVP or schedule a meetup."/>}{(offset>0||more)&&<div className="spaces-pagination"><button className="button outline small" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}><ArrowLeft size={15}/> Previous</button><button className="button outline small" disabled={!more} onClick={()=>setOffset(offset+20)}>Next <ArrowRight size={15}/></button></div>}</section>;
}
