'use client';
import {useState} from 'react';
import {Search,Pin,Star,MessageCircle,ChevronRight,Ellipsis,Plus,ArrowRight} from 'lucide-react';
import {Modal} from './ui';
import {MemberAvatar} from './profile-photo';
import {conversationGroups} from '@/lib/conversation-list';
import type {Friendship} from '@/lib/community-model';
type Props={friends:Friendship[];activeId?:string;busy:boolean;onSelect:(friend:Friendship)=>void;onDiscover:()=>void;onPreference:(friend:Friendship,kind:'pin'|'favorite',enabled:boolean)=>void};
function messageTime(timestamp:number){const date=new Date(timestamp);return date.toDateString()===new Date().toDateString()?date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):date.toLocaleDateString([],{month:'short',day:'numeric'});}
export default function ConversationList({friends,activeId,busy,onSelect,onDiscover,onPreference}:Props){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[menuId,setMenuId]=useState<string|null>(null);
 const pins=friends.filter(f=>f.pinned).length,favorites=friends.filter(f=>f.favorite).length,groups=conversationGroups(filter==='unread'?friends.filter(f=>!!f.unreadCount):friends,query,filter==='favorites'),menu=friends.find(f=>f.id===menuId),unread=friends.filter(f=>!!f.unreadCount).length;
 return <aside className="inbox-sidebar" aria-label="Your conversations">
  <div className="inbox-title"><div><h2>Messages <span>{friends.length}</span></h2><small>Your people, one hello away.</small></div><button className="icon-button new-conversation" aria-label="Find a Yaaro to message" onClick={onDiscover}><Plus size={22}/></button></div>
  <label className="inbox-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a Yaaro" aria-label="Search conversations"/></label>
  <div className="inbox-tabs">{[['all','All'],['unread','Unread'],['favorites','Favorites']].map(([id,label])=><button key={id} className={filter===id?'selected':''} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}{id==='unread'&&unread>0&&<span>{unread}</span>}</button>)}</div>
  <div className="inbox-capacity"><span><Pin size={13}/> {pins}/2 pinned</span><span><Star size={13}/> {favorites}/3 favorites</span></div>
  <div className="inbox-rows">{groups.map(group=>!!group.items.length&&<section key={group.title} aria-label={group.title}><div className="inbox-section-title"><h3>{group.title}</h3><span>{group.items.length}</span></div>{group.items.map(friend=><div key={friend.id} className={`conversation-row ${activeId===friend.id?'selected':''} ${friend.unreadCount?'has-unread':''}`}>
   <button className="conversation-open" onClick={()=>onSelect(friend)} aria-label={`Open conversation with ${friend.person.name}`} aria-pressed={activeId===friend.id}><MemberAvatar member={friend.person} size="small"/><span className="conversation-copy"><span className="conversation-name"><b>{friend.person.name}</b>{friend.lastMessage&&<time dateTime={new Date(friend.lastMessage.createdAt).toISOString()}>{messageTime(friend.lastMessage.createdAt)}</time>}</span><span className="conversation-preview">{friend.lastMessage?(friend.lastMessage.deleted?'Message deleted':`${friend.lastMessage.own?'You: ':''}${friend.lastMessage.body}`):`Say hello · ${friend.person.vibe}`}</span><span className="conversation-badges">{friend.person.online&&<span>Online now</span>}{friend.pinned&&<Pin size={11} aria-label="Pinned"/>}{friend.favorite&&<Star size={11} aria-label="Favorite"/>}</span></span>{!!friend.unreadCount?<span className="conversation-unread" aria-label={`${friend.unreadCount} unread messages`}>{friend.unreadCount>99?'99+':friend.unreadCount}</span>:<ChevronRight size={15} className="conversation-chevron"/>}</button>
   <div className="conversation-actions"><button className="icon-button conversation-menu-button" disabled={busy} aria-label={`Options for ${friend.person.name}`} aria-haspopup="dialog" onClick={()=>setMenuId(friend.id)}><Ellipsis size={19}/></button></div>
  </div>)}</section>)}{groups.every(g=>!g.items.length)&&<div className="inbox-empty"><Search size={25}/><h3>{query?'No Yaaros found.':filter==='unread'?'All caught up.':filter==='favorites'?'Your favorites start here.':'Your next hello is waiting.'}</h3><p>{query?'Try a different name or vibe.':filter==='unread'?'No unread messages right now.':filter==='favorites'?'Open a Yaaro’s options and add them to favorites.':'Discover someone with your kind of energy.'}</p></div>}</div>
 {menu&&<Modal title={menu.person.name} onClose={()=>setMenuId(null)}><div className="profile-menu-list"><button disabled={busy||(!menu.pinned&&pins>=2)} onClick={()=>{onPreference(menu,'pin',!menu.pinned);setMenuId(null);}}><Pin size={21}/><span><b>{menu.pinned?'Unpin conversation':'Pin conversation'}</b><small>{pins}/2 pinned · Keep important conversations at the top</small></span></button><button disabled={busy||(!menu.favorite&&favorites>=3)} onClick={()=>{onPreference(menu,'favorite',!menu.favorite);setMenuId(null);}}><Star size={21}/><span><b>{menu.favorite?'Remove from favorites':'Add to favorites'}</b><small>{favorites}/3 favorites · Keep your closest Yaaros together</small></span></button><button onClick={()=>{onSelect(menu);setMenuId(null);}}><MessageCircle size={21}/><span><b>Open conversation</b><small>Continue your conversation</small></span><ArrowRight size={18}/></button></div></Modal>}
 </aside>;
}
