'use client';
import {useState,type ReactNode} from 'react';
import {Search,SlidersHorizontal,X,ArrowLeft,ArrowRight,Compass,ShieldCheck} from 'lucide-react';
import {languages,interests,vibes} from '@/lib/data';
import {regions,type Member} from '@/lib/community-model';
import {Modal,VibeIcon,Empty} from './ui';
export type DiscoveryFilters={query:string;vibe:string;language:string;interest:string;region:string};
const clear:DiscoveryFilters={query:'',vibe:'',language:'',interest:'',region:''};
type Props={people:Member[];filters:DiscoveryFilters;offset:number;hasMore:boolean;onFilters:(filters:DiscoveryFilters)=>void;onPage:(offset:number)=>void;renderCard:(person:Member)=>ReactNode};
export default function DiscoveryExplorer({people,filters,offset,hasMore,onFilters,onPage,renderCard}:Props){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(filters);
 const count=Number(!!filters.vibe)+Number(!!filters.language)+Number(!!filters.interest)+Number(!!filters.region);
 const selected=(['vibe','language','interest','region'] as const).filter(key=>!!filters[key]);
 return <div className="discovery-explorer">
  <div className="explorer-heading"><span className="eyebrow">A LITTLE COMMON GROUND GOES A LONG WAY</span><h1>Find your people.</h1><p>A shared interest. A familiar language. A new hello.</p></div>
  <div className="explorer-search-row"><label className="explorer-search"><Search size={19}/><input value={filters.query} maxLength={100} onChange={event=>onFilters({...filters,query:event.target.value})} placeholder="Search people, bios, or cities" aria-label="Search people, bios, or cities"/>{filters.query&&<button type="button" aria-label="Clear search" onClick={()=>onFilters({...filters,query:''})}><X size={17}/></button>}</label><button className={`explorer-filter-button ${count?'has-filters':''}`} onClick={()=>{setDraft(filters);setOpen(true);}} aria-label={`Open discovery filters${count?`, ${count} active`:''}`} aria-haspopup="dialog"><SlidersHorizontal size={20}/><span>Filters</span>{count>0&&<b>{count}</b>}</button></div>

  <div className="explorer-vibes" aria-label="Filter by vibe">{['','Chill','Music','Gaming','Travel','Ideas','Study','Fun'].map(vibe=><button key={vibe||'all'} className={filters.vibe===vibe?'selected':''} aria-pressed={filters.vibe===vibe} onClick={()=>onFilters({...filters,vibe})}>{vibe?<VibeIcon name={vibe} size={17}/>:<Compass size={17}/>}<span>{vibe||'All Yaaros'}</span></button>)}</div>
  {!!selected.length&&<div className="explorer-active-filters" aria-label="Active filters">{selected.map(key=><button key={key} aria-label={`Remove ${key} filter: ${filters[key]}`} onClick={()=>onFilters({...filters,[key]:''})}>{filters[key]}<X size={13}/></button>)}<button className="explorer-clear" onClick={()=>onFilters(clear)}>Clear all</button></div>}
  <div className="explorer-results-heading"><h2>{filters.query?'Search results':filters.vibe?`${filters.vibe} energy`:'People to discover'}</h2><small>{people.length} on this page</small></div>
  {people.length?<div className="real-people-grid explorer-grid">{people.map(renderCard)}</div>:<Empty title="No Yaaros here yet." description="Try a different location, vibe, language, or interest. Your next hello could be one filter away."><button className="button outline" onClick={()=>onFilters(clear)}>Reset filters</button></Empty>}
  {(offset>0||hasMore)&&<nav className="explorer-pagination" aria-label="Discovery pages"><button className="button outline small" disabled={offset===0} onClick={()=>onPage(Math.max(0,offset-24))}><ArrowLeft size={15}/> Previous</button><span>Page {Math.floor(offset/24)+1}</span><button className="button outline small" disabled={!hasMore} onClick={()=>onPage(offset+24)}>Next <ArrowRight size={15}/></button></nav>}
  <p className="explorer-privacy"><ShieldCheck size={15}/> Contact details stay private. Only approximate regions are shared.</p>
  {open&&<Modal title="Find your wavelength" onClose={()=>setOpen(false)}><form className="explorer-filter-form" onSubmit={event=>{event.preventDefault();onFilters(draft);setOpen(false);}}><p>Choose a little common ground for your next connection.</p><fieldset><legend>Current vibe</legend><div className="explorer-filter-vibes">{['',...vibes.map(v=>v[1])].map(vibe=><button key={vibe||'all'} type="button" className={draft.vibe===vibe?'selected':''} aria-pressed={draft.vibe===vibe} onClick={()=>setDraft({...draft,vibe})}>{vibe&&<VibeIcon name={vibe} size={16}/>} {vibe||'Any vibe'}</button>)}</div></fieldset><div className="explorer-selects"><label>Language<select value={draft.language} onChange={event=>setDraft({...draft,language:event.target.value})}><option value="">Any language</option>{languages.map(language=><option key={language}>{language}</option>)}</select></label><label>Interest<select value={draft.interest} onChange={event=>setDraft({...draft,interest:event.target.value})}><option value="">Any interest</option>{interests.map(interest=><option key={interest}>{interest}</option>)}</select></label></div><label>City or region<input value={draft.region} maxLength={60} placeholder="Any location" list="yaaro-discovery-regions" onChange={event=>setDraft({...draft,region:event.target.value})}/></label><datalist id="yaaro-discovery-regions">{regions.filter(value=>!['Prefer not to say','Other region'].includes(value)).map(value=><option key={value} value={value}/>)}</datalist><div className="explorer-filter-footer"><button type="button" className="text-link" onClick={()=>setDraft({...clear,query:filters.query})}>Reset filters</button><button className="button primary" type="submit">Show Yaaros <ArrowRight size={16}/></button></div></form></Modal>}
 </div>;
}
