'use client';
import {useState,useRef,useEffect,type FormEvent} from 'react';
import {MessageCircle,Phone,Video,Zap,ArrowRight,Globe2,ShieldCheck,Send,UserPlus,Check,Flag,Loader2,SlidersHorizontal,X} from 'lucide-react';
import {api} from '@/lib/services';
import {languages,vibes,interests} from '@/lib/data';
import type {Member} from '@/lib/community-model';
import type {ExploreState} from '@/lib/explore-model';
import {useCalls} from './call-provider';
import {useSounds} from './sounds';
import {MemberAvatar} from './profile-photo';
import {Modal,VibeTag} from './ui';
export default function ExploreConnect({me,onExplore,onReport,onChanged}:{me:Member;onExplore:()=>void;onReport:(member:Member)=>void;onChanged:()=>Promise<void>}){
 const {startCall}=useCalls(),{play}=useSounds();
 const [mode,setMode]=useState<'text'|'voice'|'video'>('text'),[language,setLanguage]=useState(''),[vibe,setVibe]=useState(''),[interest,setInterest]=useState(''),[specific,setSpecific]=useState(false),[region,setRegion]=useState('');
 const [state,setState]=useState<ExploreState|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[draft,setDraft]=useState(''),[sending,setSending]=useState(false),[waited,setWaited]=useState(false);
 const [android,setAndroid]=useState(false);
 useEffect(()=>{setAndroid(/Android/i.test(navigator.userAgent));},[]);
 const ticket=useRef<string|null>(null),alive=useRef(true),sequence=useRef(0),seen=useRef(new Set<string>()),initialized=useRef(''),bottom=useRef<HTMLDivElement>(null);
 const session=state?.session,searching=!!state?.waiting,locked=searching||!!session;
 function acceptState(next:ExploreState){setState(next);if(next.session?.state==='active'){if(initialized.current!==next.session.id){initialized.current=next.session.id;seen.current=new Set();play('received','match:'+next.session.id);}for(const message of next.session.messages){if(!seen.current.has(message.id)){seen.current.add(message.id);if(message.author!==me.id)play('received','explore:'+message.id);}}}}
 async function join(){if(busy)return;setBusy(true);setError('');setWaited(false);const token=++sequence.current;try{const next=await api('/api/explore','POST',{action:'join',filters:{mode,language,vibe,interest,region:specific?region.trim():''}}) as ExploreState;if(!alive.current||token!==sequence.current){if(next.ticket)void api('/api/explore','POST',{action:'cancel',ticket:next.ticket}).catch(()=>{});return;}ticket.current=next.ticket||null;acceptState(next);}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setBusy(false);}}
 async function cancel(){const key=ticket.current;ticket.current=null;sequence.current++;setState(null);setError('');if(key)try{await api('/api/explore','POST',{action:'cancel',ticket:key});}catch(e){setError((e as Error).message);}}
 async function end(){if(!session||!ticket.current||busy)return;setBusy(true);try{await api('/api/explore','POST',{action:'end',session:session.id,ticket:ticket.current});acceptState(await api('/api/explore?ticket='+ticket.current));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function decide(decision:'request'|'skip'){if(!session||!ticket.current||busy)return;setBusy(true);setError('');try{await api('/api/explore','POST',{action:'decision',session:session.id,ticket:ticket.current,decision});await onChanged();await cancel();if(decision==='request')setError('Your connection choice is saved. If you both choose Connect, you’re Yaaros; otherwise the request stays pending.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function block(){if(!session||busy)return;setBusy(true);try{await api('/api/community','POST',{action:'block',target:session.peer.id});await onChanged();await cancel();setError('This Yaaro is blocked and your temporary conversation has ended.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function send(event:FormEvent){event.preventDefault();if(!draft.trim()||sending||!session||!ticket.current)return;setSending(true);setError('');const body=draft.trim(),id=crypto.randomUUID();try{await api('/api/explore','POST',{action:'message',session:session.id,ticket:ticket.current,id,body});setDraft('');play('sent','explore-sent:'+id);acceptState(await api('/api/explore?ticket='+ticket.current));}catch(e){setError((e as Error).message);}finally{setSending(false);}}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;sequence.current++;const key=ticket.current;if(key)void fetch('/api/explore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel',ticket:key}),keepalive:true}).catch(()=>{});};},[]);
 useEffect(()=>{if(!state?.ticket)return;const key=state.ticket;let stopped=false,inFlight=false,lastPulse=0;const check=async()=>{if(inFlight||ticket.current!==key||!navigator.onLine)return;inFlight=true;try{const pulse=Date.now()-lastPulse>8000;let next:ExploreState;if(pulse){lastPulse=Date.now();next=await api('/api/explore','POST',{action:'pulse',ticket:key});}else next=await api('/api/explore?ticket='+key);if(!stopped&&ticket.current===key){acceptState(next);if(next.expired){ticket.current=null;setState(null);setError('Your search ended. Start again when you’re ready.');}}}catch(e){if(!stopped)setError((e as Error).message);}finally{inFlight=false;}};void check();const timer=setInterval(check,1500);const pagehide=()=>{void fetch('/api/explore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel',ticket:key}),keepalive:true}).catch(()=>{});};window.addEventListener('pagehide',pagehide);return()=>{stopped=true;clearInterval(timer);window.removeEventListener('pagehide',pagehide);};},[state?.ticket]);
 useEffect(()=>{if(!searching)return;const timeout=setTimeout(()=>setWaited(true),20000);return()=>clearTimeout(timeout);},[searching]);
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest',behavior:'auto'});},[session?.messages.at(-1)?.id]);
 function call(){if(!session||session.mode==='text')return;startCall({friend:{id:session.id,status:'exploring',requester:me.id,updatedAt:Date.now(),person:session.peer},mode:session.mode,nonce:Date.now()});}
 return <div className="explore-connect"><div className="explore-intro"><span className="eyebrow"><Zap size={15}/> YOUR NEXT HELLO</span><h1>Find your wavelength.</h1><p>Meet someone exploring YAARO right now. A fresh conversation, without a connection request first.</p></div>
 {!session&&<section className="explore-search panel"><div className="explore-art" aria-hidden="true"><span>NEW PEOPLE. REAL CONVERSATIONS.</span><h2>One hello.<br/><em>A new possibility.</em></h2><div><MessageCircle/><i/><Phone/><i/><Video/></div></div><h2 className="explore-question">How do you want to connect?</h2><div className="explore-modes">{([{id:'text',name:'Text',Icon:MessageCircle,description:'Say hello'},{id:'voice',name:'Voice',Icon:Phone,description:'Hear their story'},{id:'video',name:'Video',Icon:Video,description:'Meet face to face'}] as const).map(({id,name,Icon,description})=><button key={id} disabled={locked||busy} aria-pressed={mode===id} className={mode===id?'selected':''} onClick={()=>setMode(id)}><span><Icon size={25}/></span><b>{name}</b><small>{description}</small>{mode===id&&<Check className="explore-check" size={14}/>}</button>)}</div>
 <section className="explore-preferences"><h3 id="explore-preferences-title"><SlidersHorizontal size={17}/> Your preferences</h3><fieldset className="explore-filter-box" aria-labelledby="explore-preferences-title" disabled={locked||busy}><div className="explore-filter-grid"><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">Any language</option>{languages.map(l=><option key={l}>{l}</option>)}</select></label><label>Vibe<select value={vibe} onChange={e=>setVibe(e.target.value)}><option value="">Any vibe</option>{vibes.map(([,v])=><option key={v}>{v}</option>)}</select></label><label>Interest<select value={interest} onChange={e=>setInterest(e.target.value)}><option value="">Any interest</option>{interests.map(i=><option key={i}>{i}</option>)}</select></label><label>Location<select value={specific?'specific':'any'} onChange={e=>setSpecific(e.target.value==='specific')}><option value="any">Any location</option><option value="specific">Choose city or region</option></select></label>{specific&&<label className="explore-region">City or region<input value={region} onChange={e=>setRegion(e.target.value)} maxLength={60} placeholder="e.g. Bengaluru or Chennai" autoComplete="address-level2"/><small>Matches the broad location people choose to share. No GPS or exact addresses.</small></label>}</div></fieldset></section>
 {searching?<div className="explore-wait" role="status" aria-live="polite"><Loader2 className="explore-spinner"/><b>Finding someone exploring {mode}…</b><p>{waited?'No compatible explorer yet. You can keep waiting or cancel and broaden your preferences.':'You’ll meet someone who is also looking for a new conversation.'}</p><button className="button outline" onClick={()=>void cancel()}>Cancel search</button></div>:<button className="button primary wide explore-find" disabled={busy||(specific&&!region.trim())} onClick={()=>void join()}><Zap size={18}/>{busy?'Joining exploration…':'Find my Yaaro'}<ArrowRight size={18}/></button>}
 <p className="explore-privacy"><ShieldCheck size={17}/> Starting a search makes you available only to other explorers in the same mode. Camera and microphone stay off until you start or accept a call.</p></section>}
 {session?.state==='active'&&<section className="explore-session panel"><header><MemberAvatar member={session.peer}/><div><span className="eyebrow">YAARO FOUND</span><h2>{session.peer.name} <small>{session.peer.age}</small></h2><p>{session.peer.languages.join(' · ')}{!['Prefer not to say','Other region',''].includes(session.peer.region)?' / '+session.peer.region:''}</p></div><button className="icon-button" aria-label="Report or block this Yaaro" onClick={()=>onReport(session.peer)}><Flag size={20}/></button></header><div className="explore-session-note"><VibeTag name={session.peer.vibe}/><span>Temporary session · No inbox history</span></div>{session.mode==='text'?<><div className="explore-messages" aria-live="polite">{!session.messages.length&&<div className="explore-hello"><MessageCircle size={30}/><h3>A little hello goes a long way.</h3><p>Start with a shared interest.</p></div>}{session.messages.map(m=><div key={m.id} className={`explore-message ${m.author===me.id?'own':''}`}><p>{m.body}</p><small>{new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>)}<div ref={bottom}/></div><form className="explore-composer" onSubmit={send}><input aria-label="Temporary message" placeholder="Say hello…" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2000}/><button className="send-button" type="submit" disabled={sending||!draft.trim()} aria-label="Send message"><Send size={20}/></button></form></>:<div className="explore-call-ready">{session.mode==='video'?<Video size={38}/>:<Phone size={38}/>}<h3>You’ve found your Yaaro.</h3><p>{session.caller||android?'Start the call when you’re ready. Your Yaaro will be asked to accept.':'Your Yaaro can start the call. You’ll receive an incoming-call prompt here.'}</p>{(session.caller||android)&&<button className="button primary" onClick={call}>Start {session.mode} call<ArrowRight size={17}/></button>}</div>}<footer><button className="text-link" disabled={busy} onClick={()=>void block()}>Block Yaaro</button><span>Messages disappear when either person ends. Calls are not recorded.</span><button className="button outline" disabled={busy} onClick={()=>void end()}>End conversation</button></footer></section>}
 {error&&<div className="form-notice" role="status">{error}</div>}
 {!locked&&<button className="explore-discover" onClick={onExplore}><Globe2 size={18}/> Browse profiles in Discover <ArrowRight size={16}/></button>}
 {session?.state==='ended'&&<Modal title="Keep the connection?" centered onClose={()=>void decide('skip')}><div className="explore-finish"><MemberAvatar member={session.peer}/><h2>Make {session.peer.name} your Yaaro?</h2><p>Your temporary conversation has ended and its messages are gone. Send a normal connection request to stay in touch.</p><button className="button primary wide" disabled={busy} onClick={()=>void decide('request')}><UserPlus size={19}/> Connect with {session.peer.name}</button><button className="button outline wide" disabled={busy} onClick={()=>void decide('skip')}><X size={18}/> No thanks · Explore again</button><small>If you both pass, no conversation appears in either inbox. You may meet again in a future search.</small>{error&&<p role="alert">{error}</p>}</div></Modal>}
 </div>;
}
