'use client';
import { useState } from 'react';
import { MessageCircle, Zap, Users, ShieldCheck, Headphones, Check, Menu, X, Sparkles, Heart, Video, Globe } from 'lucide-react';
import { Brand, Avatar, VibePicker, VibeIcon } from './ui';
import { people } from '@/lib/data';
import { MotionControl } from './motion';
export default function Landing(){const [vibe,setVibe]=useState('Chill'),[menu,setMenu]=useState(false);return <div className="landing">
<header className="public-nav"><Brand/><button className="icon-button mobile-menu" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}><a className="active" href="/">Home</a><a href="/app/discover">Discover</a><a href="#features">Features</a><a href="#safety">Safety</a><a href="#about">About</a><a href="/business">For Business</a></nav><div className="nav-actions"><MotionControl/><a href="/auth/login" className="login-link">Log In</a><a className="button primary small" href="/auth/signup">Join YAARO</a></div></header>
<main><section className="hero"><div className="hero-aurora" aria-hidden="true"><i/><i/><i/></div><div className="hero-copy"><div className="eyebrow"><span/> YOUR VIBE. YOUR PEOPLE.</div><h1>Find Your<br/><span>Yaaro.</span><span className="hero-period">✳</span></h1><p>Meet people who match your vibe. Chat, call, share moments, and turn conversations into connections.</p><div className="hero-actions"><a href="/onboarding" className="button primary">Find My Yaaro <Zap size={18}/></a><a href="/community" className="button outline">Explore YAARO</a></div><div className="hero-foot"><div className="avatar-stack">{people.slice(0,4).map(p=><Avatar key={p.id} person={p} size="tiny"/>)}</div><span>A little hello. A whole new connection.<small>Preview the community with fictional Yaaros.</small></span></div><div className="hero-safety"><ShieldCheck size={15}/> Friendship first. Your comfort always.</div></div>
<div className="hero-stage logo-stage"><div className="logo-orbit orbit-one" aria-hidden="true"><i/></div><div className="logo-orbit orbit-two" aria-hidden="true"><i/></div><div className="logo-orbit orbit-three" aria-hidden="true"/><div className="logo-center" data-tilt><img src="/yaaro-logo.png" alt="YAARO — Meet. Talk. Connect." width="520" height="240" fetchPriority="high"/><span>MEET. TALK. CONNECT.</span></div><div className="logo-satellite satellite-chat"><MessageCircle size={26}/><span>A little hello.</span></div><div className="logo-satellite satellite-music"><Headphones size={25}/><span>Your wavelength.</span></div><div className="logo-satellite satellite-people"><Users size={25}/><span>Your kind of people.</span></div><div className="logo-stage-caption"><span/> CONNECTION STARTS HERE</div></div></section>
<section className="connection-strip"><span>People are connecting<br/><b>one conversation at a time.</b></span><div className="connection-people">{people.slice(0,3).map(p=><div key={p.id}><Avatar person={p} size="small"/><span><b>{p.name}</b><small><VibeIcon name={p.vibe} size={14}/> {p.vibe}</small></span></div>)}</div><span className="sample-caption">Fictional community preview</span></section>
<section className="vibe-section vibe-lab" id="vibes" data-reveal><div className="vibe-lab-heading"><div><div className="eyebrow">TUNE INTO YOUR PEOPLE</div><h2>What’s your <span>vibe?</span></h2><p>Find a conversation that feels like you.<br/>Pick your mood. Make your next hello count.</p></div><div className="vibe-signal" aria-hidden="true"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></div><VibePicker value={vibe} onChange={setVibe}/><div className="vibe-launch"><div className="vibe-current" key={vibe}><span className="vibe-current-icon"><VibeIcon name={vibe} size={25}/></span><span>Your wavelength<strong>{vibe}</strong></span><div className="mini-signal" aria-hidden="true"><i/><i/><i/><i/></div></div><a href={`/app/connect?vibe=${encodeURIComponent(vibe)}`} className="button primary">Find My Yaaro <Zap size={17}/></a></div></section>
<section id="features" className="feature-section"><div className="section-heading" data-reveal><div><div className="eyebrow">MORE THAN A HELLO</div><h2>Small moments.<br/>Real connections.</h2></div><p>One place to find your people,<br/>and keep the conversation going.</p></div><div className="feature-grid"><a href="/app/connect" className="feature-card feature-blue"><Zap size={30}/><h3>Find your wavelength.</h3><p>Pick a vibe and explore Quick Connect. A new conversation is one hello away.</p><span className="feature-link">Explore Quick Connect</span><div className="feature-pills"><span>Chill</span><span>Gaming</span></div></a><a href="/app/chats" className="feature-card"><MessageCircle size={30}/><h3>Talk your way.</h3><p>A home for text conversations, with voice and video experiences coming next.</p><div className="mini-chat"><span>Same playlist?</span><span>Same wavelength</span></div></a><a href="/app/rooms" className="feature-card"><Headphones size={30}/><h3>Find your circle.</h3><p>Music lovers, movie people, late-night thinkers. Discover a room that feels like you.</p><div className="room-pill">Tamil Music Addicts <span>ROOM PREVIEW</span></div></a></div></section>
<section className="safety-section" id="safety"><div className="safety-icon"><ShieldCheck size={58}/></div><div><div className="eyebrow">GOOD VIBES NEED A SAFE SPACE</div><h2>Your space. Your boundaries.</h2><p>You choose who can reach you and what you share. Privacy controls, blocking, and reporting belong at the heart of YAARO.</p><div className="safety-checks"><span><Check size={17}/> Privacy on your terms</span><span><Check size={17}/> Block & report</span><span><Check size={17}/> Friendship first</span></div><a href="/policy/safety" className="text-link">Visit the Safety Center</a></div></section>
<section id="about" className="about-section"><div className="eyebrow">MEET. TALK. CONNECT.</div><h2>The internet feels better<br/>when you find your people.</h2><p>YAARO is being built for genuine friendship, shared interests, and everyday conversations. No pressure to perform. Just space to be yourself.</p><a href="/auth/signup" className="button primary">Join the beginning <Heart size={17}/></a></section></main>
<footer className="footer"><div><Brand/><p>Your vibe. Your people. Your YAARO.</p></div><div><b>Explore</b><a href="/app/discover">Discover</a><a href="/app/rooms">Rooms</a><a href="/business">For Business</a></div><div><b>Trust & safety</b><a href="/policy/privacy">Privacy Policy</a><a href="/policy/terms">Terms of Service</a><a href="/policy/community">Community Guidelines</a><a href="/policy/cookies">Cookie Policy</a></div><div><b>YAARO preview</b><a href="/demo/admin">Admin demo</a><a href="/admin">Protected administration</a><small>Early product preview.<br/>Live social services coming next.</small></div><div className="footer-bottom">© {new Date().getFullYear()} YAARO <span>Made for meaningful connections.</span></div></footer></div>}
