'use client';
import {useEffect,useState,useCallback,useRef} from 'react';
import {Plus,ImagePlus,Trash2,Flag,Clock,Users,Lock,RefreshCw,X} from 'lucide-react';
import {Modal} from './ui';
import {api} from '@/lib/services';
import {prepareChatPhoto} from '@/lib/media-browser';
type Moment={id:string;author:string;name:string;body:string;photoUrl?:string;visibility:'friends'|'private';createdAt:number;expiresAt:number|null;own:boolean};
export default function MomentsPanel({onReport}:{onReport:(author:string,id:string)=>void}){
 const [moments,setMoments]=useState<Moment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[view,setView]=useState<Moment|null>(null),[body,setBody]=useState(''),[visibility,setVisibility]=useState('friends'),[duration,setDuration]=useState('24h'),[photo,setPhoto]=useState<Blob|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false);const request=useRef(0),draftId=useRef(crypto.randomUUID());
 const refresh=useCallback(async()=>{const id=++request.current;try{const data=await api('/api/moments');if(id===request.current){setMoments(data.moments);setError('');}}catch(e){if(id===request.current)setError((e as Error).message);}finally{if(id===request.current)setLoading(false);}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(!document.hidden&&navigator.onLine)void refresh();},30000);return()=>{clearInterval(timer);request.current++;};},[refresh]);
 useEffect(()=>{if(!photo){setPreview('');return;}const url=URL.createObjectURL(photo);setPreview(url);return()=>URL.revokeObjectURL(url);},[photo]);
 useEffect(()=>{if(!view?.expiresAt)return;const timer=setTimeout(()=>setView(null),Math.max(0,view.expiresAt-Date.now()));return()=>clearTimeout(timer);},[view?.id,view?.expiresAt]);
 async function selectPhoto(file?:File){if(!file)return;setBusy(true);setError('');try{setPhoto(await prepareChatPhoto(file));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function publish(){setBusy(true);setError('');try{const form=new FormData();form.set('id',draftId.current);form.set('body',body);form.set('visibility',visibility);form.set('duration',duration);if(photo)form.set('image',photo,'moment.png');const response=await fetch('/api/moments',{method:'POST',body:form}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||'Unable to share your Moment.');setBody('');setPhoto(null);setOpen(false);draftId.current=crypto.randomUUID();await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(moment:Moment){setBusy(true);try{await api('/api/moments?id='+moment.id,'DELETE');setView(null);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="moments-panel"><div className="home-section-title"><h2>Moments</h2><button className="text-link" onClick={()=>setOpen(true)}><Plus size={16}/> Share</button></div><div className="moments-strip"><button className="moment-create" onClick={()=>setOpen(true)}><span><Plus size={25}/></span><b>Your moment</b><small>A little of your day</small></button>{moments.filter(moment=>!moment.expiresAt||moment.expiresAt>Date.now()).slice(0,10).map(moment=><button className={`moment-preview ${moment.photoUrl?'has-photo':''}`} key={moment.id} onClick={()=>setView(moment)}>{moment.photoUrl&&<img src={moment.photoUrl} alt="" loading="lazy"/>}<span className="moment-preview-content"><b>{moment.name}</b><span>{moment.body||'A photo from their day'}</span><small>{moment.visibility==='private'?<Lock size={11}/>:<Users size={11}/>} {moment.own?'You':moment.expiresAt?'24 hours':'Kept'}</small></span></button>)}</div>{loading&&<p className="small-note" role="status">Loading your circle’s Moments…</p>}{!loading&&!moments.length&&!error&&<p className="small-note">Your circle’s updates will appear here. Share the first little moment.</p>}{error&&!open&&<p className="form-notice" role="alert">{error}<button className="text-link" onClick={()=>void refresh()}><RefreshCw size={13}/> Retry</button></p>}
 {open&&<Modal title="Share a moment" onClose={()=>{if(!busy)setOpen(false);}}><form className="moment-compose" onSubmit={event=>{event.preventDefault();void publish();}}><label>Your moment<textarea value={body} maxLength={500} onChange={event=>setBody(event.target.value)} placeholder="A thought, a small win, a little of your day…"/></label><small className="moment-character-count">{body.length}/500</small>{preview&&<div className="moment-photo-preview"><img src={preview} alt="Your selected moment photo"/><button className="icon-button" type="button" aria-label="Remove selected photo" onClick={()=>setPhoto(null)}><X size={17}/></button></div>}<label className="moment-photo-chooser"><ImagePlus size={19}/><span>{photo?'Change photo':'Add a photo'}</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} aria-label="Choose a moment photo" onChange={event=>void selectPhoto(event.target.files?.[0])}/></label><div className="moment-compose-settings"><label>Who can see this?<select value={visibility} onChange={event=>setVisibility(event.target.value)}><option value="friends">My Yaaros</option><option value="private">Only me</option></select></label><label>How long?<select value={duration} onChange={event=>setDuration(event.target.value)}><option value="24h">24 hours</option><option value="keep">Keep until I delete</option></select></label></div><p className="small-note">Shared Moments are visible only to your accepted connections. Removing or blocking a connection removes their access.</p>{error&&<p className="form-notice" role="alert">{error}</p>}<button className="button primary wide" disabled={busy||(!body.trim()&&!photo)}>{busy?'Sharing…':'Share moment'}</button></form></Modal>}
 {view&&<Modal title={`${view.name}’s moment`} onClose={()=>setView(null)}><article className="moment-view">{view.photoUrl&&<img src={view.photoUrl} alt={view.body||`Photo shared by ${view.name}`}/>}<p>{view.body}</p><div className="moment-view-meta"><span>{view.visibility==='private'?<Lock size={14}/>:<Users size={14}/>} {view.visibility==='private'?'Only you':'My Yaaros'}</span><span><Clock size={14}/>{view.expiresAt?'Expires '+new Date(view.expiresAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Kept until deleted'}</span></div>{view.own?<button className="button outline small" disabled={busy} onClick={()=>void remove(view)}><Trash2 size={16}/> Delete moment</button>:<button className="button outline small" onClick={()=>{onReport(view.author,view.id);setView(null);}}><Flag size={16}/> Report moment</button>}</article></Modal>}
 </section>;
}
