'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode,type CSSProperties} from 'react';
import {Pause,Play} from 'lucide-react';
const MotionContext=createContext({enabled:true,paused:false,reduced:false,toggle:()=>{}});
export function celebrate(){if(typeof window!=='undefined')window.dispatchEvent(new Event('yaaro:celebrate'));}
export function MotionControl(){const {paused,reduced,toggle}=useContext(MotionContext);return <button type="button" className="icon-button motion-control" onClick={toggle} disabled={reduced} aria-label={reduced?'Reduced motion follows your device setting':paused?'Enable animations':'Pause animations'} title={reduced?'Reduced motion follows your device setting':paused?'Enable animations':'Pause animations'} aria-pressed={paused}>{paused||reduced?<Play size={17}/>:<Pause size={17}/>}</button>}
export function MotionProvider({children}:{children:ReactNode}){
 const [paused,setPaused]=useState(false),[reduced,setReduced]=useState(false),[burst,setBurst]=useState(0);const pauseRef=useRef(false);const enabled=!paused&&!reduced;
 useEffect(()=>{const pref=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(pref.matches);change();pref.addEventListener('change',change);try{const saved=localStorage.getItem('yaaro:motion')==='off';pauseRef.current=saved;setPaused(saved);}catch{}return()=>pref.removeEventListener('change',change);},[]);
 function toggle(){const next=!pauseRef.current;pauseRef.current=next;setPaused(next);try{localStorage.setItem('yaaro:motion',next?'off':'on');}catch{}}
 useEffect(()=>{const active=enabled&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&!pauseRef.current;document.documentElement.dataset.motion=active?'on':'off';if(!active)return;
  const animations=new Set<Animation>(),seen=new WeakSet<Element>(),pending=new Set<Element>();let scanFrame=0,tiltFrame=0,tilted:HTMLElement|null=null;let observer:IntersectionObserver|null=null;
  const selectors='[data-reveal],.feature-card,.person-card,.real-person,.room-card,.moment-card,.real-stats>.panel,.metric-card,.real-request,.real-profile-form,.empty,.safety-section,.about-section,.business-cards>.panel,.home-conversation-row,.conversation-row,.moment-tile,.connect-mode-picker>button,.studio-photo-first';
  function animate(el:HTMLElement,delay=0){if(seen.has(el)||!el.isConnected)return;seen.add(el);if(!el.animate)return;const animation=el.animate([{opacity:0,transform:'translate3d(0,12px,0)'},{opacity:1,transform:'translate3d(0,0,0)'}],{duration:420,delay,easing:'cubic-bezier(.22,1,.36,1)',fill:'backwards'});animations.add(animation);animation.onfinish=()=>animations.delete(animation);}
  if('IntersectionObserver' in window)observer=new IntersectionObserver(entries=>{let i=0;for(const entry of entries)if(entry.isIntersecting){animate(entry.target as HTMLElement,(i++%4)*35);observer?.unobserve(entry.target);}},{threshold:.08,rootMargin:'0px 0px -16px 0px'});
  function register(el:Element){if(seen.has(el))return;if(observer)observer.observe(el);else animate(el as HTMLElement);}
  document.querySelectorAll(selectors).forEach(register);
  function collect(node:Node){if(!(node instanceof Element))return;if(node.matches(selectors))pending.add(node);node.querySelectorAll(selectors).forEach(el=>pending.add(el));if(!scanFrame)scanFrame=requestAnimationFrame(()=>{scanFrame=0;pending.forEach(register);pending.clear();});}
  const mutations=new MutationObserver(records=>{for(const record of records)record.addedNodes.forEach(collect);});mutations.observe(document.body,{childList:true,subtree:true});
  const fine=matchMedia('(hover: hover) and (pointer: fine)');
  function resetTilt(){if(tilted){tilted.style.removeProperty('--tilt-x');tilted.style.removeProperty('--tilt-y');tilted=null;}}
  function pointer(e:PointerEvent){if(!fine.matches)return;const el=(e.target as Element)?.closest<HTMLElement>('[data-tilt]');if(!el){resetTilt();return;}if(tiltFrame)return;tiltFrame=requestAnimationFrame(()=>{tiltFrame=0;if(tilted&&tilted!==el)resetTilt();tilted=el;const box=el.getBoundingClientRect();el.style.setProperty('--tilt-x',`${((e.clientY-box.top)/box.height-.5)*-6}deg`);el.style.setProperty('--tilt-y',`${((e.clientX-box.left)/box.width-.5)*6}deg`);});}
  function ripple(e:PointerEvent){const el=(e.target as Element)?.closest<HTMLElement>('.button,.send-button,.vibe,.choice-grid>button');if(!el||el.hasAttribute('disabled')||!el.animate)return;const box=el.getBoundingClientRect(),size=Math.max(box.width,box.height)*1.7;const dot=document.createElement('span');dot.className='tap-ripple';dot.setAttribute('aria-hidden','true');dot.style.width=dot.style.height=`${size}px`;dot.style.left=`${e.clientX-box.left-size/2}px`;dot.style.top=`${e.clientY-box.top-size/2}px`;el.appendChild(dot);const animation=dot.animate([{transform:'scale(0)',opacity:.24},{transform:'scale(1)',opacity:0}],{duration:480,easing:'cubic-bezier(.2,.6,.3,1)'});animations.add(animation);animation.onfinish=()=>{animations.delete(animation);dot.remove();};}
  function visibility(){document.documentElement.classList.toggle('motion-paused',document.hidden);}
  const party=()=>setBurst(n=>n+1);window.addEventListener('yaaro:celebrate',party);document.addEventListener('pointermove',pointer,{passive:true});document.addEventListener('pointerdown',ripple,{passive:true});document.addEventListener('visibilitychange',visibility);visibility();
  return()=>{observer?.disconnect();mutations.disconnect();cancelAnimationFrame(scanFrame);cancelAnimationFrame(tiltFrame);animations.forEach(a=>a.cancel());document.querySelectorAll('.tap-ripple').forEach(x=>x.remove());resetTilt();window.removeEventListener('yaaro:celebrate',party);document.removeEventListener('pointermove',pointer);document.removeEventListener('pointerdown',ripple);document.removeEventListener('visibilitychange',visibility);};
 },[enabled]);
 return <MotionContext.Provider value={{enabled,paused,reduced,toggle}}>{children}{enabled&&burst>0&&<ConnectionBurst key={burst}/>}</MotionContext.Provider>;
}
function ConnectionBurst(){const [visible,setVisible]=useState(true);useEffect(()=>{const t=setTimeout(()=>setVisible(false),950);return()=>clearTimeout(t);},[]);if(!visible)return null;return <div className="connection-burst" aria-hidden="true">{Array.from({length:16},(_,i)=>{const angle=i*Math.PI*2/16;return <i key={i} style={{'--dx':`${Math.cos(angle)*(95+(i%3)*28)}px`,'--dy':`${Math.sin(angle)*(95+(i%3)*28)}px`,'--turn':`${i*47}deg`,'--delay':`${i%3*22}ms`,'--burst-color':['#12c7b5','#1769e0','#84f6e8','#44b9f4'][i%4]} as CSSProperties}/>})}</div>}
