'use client';
import {useEffect,useState} from 'react';
import {Modal} from './ui';
export async function passwordRequest(body:Record<string,string>){const response=await fetch('/api/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json() as {error?:string;message?:string};if(!response.ok)throw Error(result.error||'Unable to continue. Please try again.');return result;}
export function NewPasswordFields({password,confirmation,onPassword,onConfirmation,busy}:{password:string;confirmation:string;onPassword:(value:string)=>void;onConfirmation:(value:string)=>void;busy:boolean}){return <><label>New password<input type="password" autoComplete="new-password" minLength={12} maxLength={128} required disabled={busy} value={password} onChange={e=>onPassword(e.target.value)}/><small className="password-hint">Use at least 12 characters.</small></label><label>Re-enter new password<input type="password" autoComplete="new-password" minLength={12} maxLength={128} required disabled={busy} value={confirmation} onChange={e=>onConfirmation(e.target.value)}/></label></>;}
export default function PasswordDialog({onClose,onSaved,forgot=false}:{onClose:()=>void;onSaved?:()=>void;forgot?:boolean}){
 const [recovery,setRecovery]=useState(forgot),[email,setEmail]=useState(''),[oldPassword,setOld]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);
 useEffect(()=>{let alive=true;fetch('/api/password',{cache:'no-store'}).then(r=>r.json()).then((r:unknown)=>{if(alive)setEmail((r as {email:string}).email||'');}).catch(()=>{});return()=>{alive=false;};},[]);
 return <Modal centered title={recovery?'Forgot password':'Change password'} onClose={()=>{if(!busy)onClose();}}><form className="account-password-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{if(recovery){await passwordRequest({action:'request',email:email.trim()});setSent(true);}else{if(password!==confirmation)throw Error('Both new passwords must match.');await passwordRequest({action:'change',oldPassword,password,confirmation});onSaved?.();onClose();}}catch(e){setError(e instanceof Error?e.message:'Unable to continue.');}finally{setBusy(false);}}}>{sent?<><div className="password-feedback" role="status"><h3>Check your email</h3><p>If this email belongs to a YAARO account, we’ll send a link to create and confirm your new password. Check your spam folder too.</p></div><button type="button" className="button primary wide" onClick={onClose}>Done</button></>:<><p>{recovery?'Enter your registered email address. We’ll send you a secure password reset link.':'Verify your old password, then choose a new one.'}</p>{recovery?<label>Registered email address<input type="email" autoComplete="email" required maxLength={254} value={email} disabled={busy} onChange={e=>setEmail(e.target.value)}/></label>:<><label>Old password<input type="password" autoComplete="current-password" required maxLength={128} value={oldPassword} disabled={busy} onChange={e=>setOld(e.target.value)}/></label><NewPasswordFields {...{password,confirmation,busy}} onPassword={setPassword} onConfirmation={setConfirmation}/></>}{error&&<p className="password-error" role="alert">{error}</p>}<button className="button primary wide" disabled={busy}>{busy?'Please wait…':recovery?'Send reset link':'Change password'}</button>{!recovery&&<button type="button" className="password-forgot" disabled={busy} onClick={()=>{setRecovery(true);setOld('');setPassword('');setConfirmation('');setError('');}}>Forgot password?</button>}</>}</form></Modal>;
}
