'use client';
import {useEffect,useState} from 'react';
import {passwordSignInLink,type PasswordReturn} from '@/lib/password-return';
import PasswordDialog,{NewPasswordFields,passwordRequest} from './password-dialog';
export default function PasswordRecovery({token,returnTo='web'}:{token:string;returnTo?:PasswordReturn}){
 const [androidDevice,setAndroidDevice]=useState(false);
 useEffect(()=>setAndroidDevice(/Android/i.test(navigator.userAgent)),[]);
 const [verified,setVerified]=useState(false),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[forgot,setForgot]=useState(false);
 useEffect(()=>{let alive=true;fetch('/api/password',{cache:'no-store'}).then(r=>r.json()).then((r:unknown)=>{if(alive&&(r as {recovery?:boolean}).recovery)setVerified(true);}).catch(()=>{});return()=>{alive=false;};},[]);
 return <section className="panel password-recovery-card"><h1>{done?'Password updated':verified?'Create a new password':'Reset your password'}</h1>{done?<><p>Your new password is ready. You can sign in to YAARO in the app or browser.</p><a href={passwordSignInLink(returnTo,androidDevice,typeof location==='undefined'?'https://autumn-lake-80feyaaro.haritre07.workers.dev':location.origin)} className="button primary wide">{returnTo==='android'&&androidDevice?'Back to YAARO app':'Back to sign in'}</a>{returnTo==='android'&&androidDevice&&<a className="password-forgot" href="/auth/login">Sign in on the website instead</a>}</>:<form className="account-password-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{if(!verified){if(!token)throw Error('Open the password reset link from your email to continue.');await passwordRequest({action:'verify',token});history.replaceState(null,'','/auth/recovery?return_to='+returnTo);setVerified(true);}else{if(password!==confirmation)throw Error('Both new passwords must match.');await passwordRequest({action:'reset',password,confirmation});setPassword('');setConfirmation('');setDone(true);}}catch(e){setError(e instanceof Error?e.message:'Unable to reset password.');}finally{setBusy(false);}}}><p>{verified?'Choose your new password and enter it again to confirm.':'Continue to verify this email link. Password reset links can only be used once.'}</p>{verified&&<NewPasswordFields {...{password,confirmation,busy}} onPassword={setPassword} onConfirmation={setConfirmation}/>}<button className="button primary wide" disabled={busy}>{busy?'Please wait…':verified?'Save new password':'Continue to reset password'}</button>{error&&<p className="password-error" role="alert">{error}</p>}<button type="button" className="password-forgot" disabled={busy} onClick={()=>setForgot(true)}>Request a new reset link</button></form>}{forgot&&<PasswordDialog forgot returnTo={returnTo} onClose={()=>setForgot(false)}/>}</section>;
}
