'use client';
import {useState,useRef} from 'react';
import {ImagePlus,Trash2} from 'lucide-react';
import CameraCapture from './camera-capture';
import {prepareProfilePhoto} from '@/lib/media-browser';
import {saveProfilePhoto} from '@/lib/profile-photo-upload';
import {avatars,type Member} from '@/lib/community-model';
export function MemberAvatar({member,size=''}:{member:Member;size?:string}){const [failed,setFailed]=useState('');return <span className={`avatar mint avatar-tone-${Math.max(0,avatars.indexOf(member.avatar))} ${size}`} aria-label={`${member.name} profile photo`}>{member.photoUrl&&failed!==member.photoUrl?<img src={member.photoUrl} alt="" loading="lazy" onError={()=>setFailed(member.photoUrl!)}/>:<span>{member.name.slice(0,1).toUpperCase()}</span>}{member.online&&<i className="online-dot"/>}</span>}
export function ProfilePhoto({member,onSaved,draftPhoto,onDraft,disabled=false}:{member?:Member;onSaved:()=>Promise<void>;draftPhoto?:Blob|null;onDraft?:(photo:Blob|null)=>void;disabled?:boolean}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null);
 async function upload(file?:File){if(!file)return;setBusy(true);setError('');try{const blob=await prepareProfilePhoto(file);if(onDraft)onDraft(blob);else{await saveProfilePhoto(blob);await onSaved();}return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);if(input.current)input.current.value='';}}
 async function remove(){setBusy(true);setError('');try{if(onDraft)onDraft(null);else{await saveProfilePhoto(null);await onSaved();}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="profile-photo-tools"><input ref={input} type="file" accept="image/*,.heic,.heif,.avif" aria-label="Choose profile photo" hidden onChange={e=>void upload(e.target.files?.[0])}/><button type="button" className="button outline small" disabled={busy||disabled} onClick={()=>input.current?.click()}><ImagePlus size={17}/>{busy?'Saving photo…':(draftPhoto||draftPhoto===undefined&&member?.photoUrl)?'Change photo':'Add a profile photo'}</button>{(draftPhoto||draftPhoto===undefined&&member?.photoUrl)&&<button className="icon-button" type="button" aria-label="Remove profile photo" disabled={busy||disabled} onClick={remove}><Trash2 size={17}/></button>}<CameraCapture disabled={busy||disabled} onCapture={upload} allowVideo={false} photoAction={onDraft?'Use profile photo':'Save profile photo'}/><p className="small-note">Photos up to 15 MB, including iPhone HEIC where supported. Center-cropped and converted before upload.{onDraft&&' Changes are saved when you finish your profile.'}</p>{error&&<p className="form-notice" role="alert">{error}</p>}</div>;
}
