'use client';
import {useState,useRef} from 'react';
import {Camera,Trash2} from 'lucide-react';
import {avatars,type Member} from '@/lib/community-model';
export function MemberAvatar({member,size=''}:{member:Member;size?:string}){const [failed,setFailed]=useState('');return <span className={`avatar mint avatar-tone-${Math.max(0,avatars.indexOf(member.avatar))} ${size}`} aria-label={`${member.name} profile photo`}>{member.photoUrl&&failed!==member.photoUrl?<img src={member.photoUrl} alt="" loading="lazy" onError={()=>setFailed(member.photoUrl!)}/>:<span>{member.name.slice(0,1).toUpperCase()}</span>}{member.online&&<i className="online-dot"/>}</span>}
export function ProfilePhoto({member,onSaved}:{member:Member;onSaved:()=>Promise<void>}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null);
 async function response(r:Response){const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||'Unable to save your photo. Try again.');await onSaved();}
 async function upload(file?:File){if(!file)return;setBusy(true);setError('');let bitmap:ImageBitmap|undefined;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw new Error('Choose a JPEG, PNG, or WebP photo under 5 MB.');bitmap=await createImageBitmap(file);if(bitmap.width>10000||bitmap.height>10000||bitmap.width*bitmap.height>40000000)throw new Error('Choose a smaller photo.');const canvas=document.createElement('canvas');canvas.width=canvas.height=384;const context=canvas.getContext('2d');if(!context)throw new Error('Photo editing is unavailable in this browser.');const side=Math.min(bitmap.width,bitmap.height);context.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,384,384);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Unable to prepare the photo.')),'image/png'));await response(await fetch('/api/photo',{method:'POST',headers:{'Content-Type':'image/png'},body:blob}));}catch(e){setError((e as Error).message);}finally{bitmap?.close();setBusy(false);if(input.current)input.current.value='';}}
 async function remove(){setBusy(true);setError('');try{await response(await fetch('/api/photo',{method:'DELETE'}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="profile-photo-tools"><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" aria-label="Choose profile photo" hidden onChange={e=>void upload(e.target.files?.[0])}/><button type="button" className="button outline small" disabled={busy} onClick={()=>input.current?.click()}><Camera size={17}/>{busy?'Saving photo…':member.photoUrl?'Change photo':'Add a profile photo'}</button>{member.photoUrl&&<button className="icon-button" type="button" aria-label="Remove profile photo" disabled={busy} onClick={remove}><Trash2 size={17}/></button>}<p className="small-note">JPEG, PNG, or WebP · up to 5 MB. Center-cropped and re-encoded before upload.</p>{error&&<p className="form-notice" role="alert">{error}</p>}</div>;
}
