'use client';
import {useState,useEffect,type FormEvent} from 'react';
import {ArrowLeft,ArrowRight,Check,ShieldCheck,Sparkles,Headphones,Flower2,Gamepad2,Coffee,Lightbulb,Waves,Orbit,UserRound,Globe2,Heart,Palette} from 'lucide-react';
import {languages,interests} from '@/lib/data';
import {adultAge,avatars,regions,type CommunityProfile,type Member} from '@/lib/community-model';
import {VibePicker,VibeTag} from './ui';
import {MemberAvatar,ProfilePhoto} from './profile-photo';
const looks=[{Icon:Waves,label:'Easygoing'},{Icon:Headphones,label:'Sound seeker'},{Icon:Flower2,label:'Day dreamer'},{Icon:Gamepad2,label:'Player one'},{Icon:Coffee,label:'Coffee person'},{Icon:Lightbulb,label:'Idea maker'},{Icon:Orbit,label:'Explorer'},{Icon:Sparkles,label:'Bright energy'}];
const steps=[{name:'About you',Icon:UserRound},{name:'Your world',Icon:Globe2},{name:'Your energy',Icon:Palette},{name:'Ready to go',Icon:Heart}];
type Props={profile:CommunityProfile;onChange:(profile:CommunityProfile)=>void;consent:boolean;onConsent:(value:boolean)=>void;busy:boolean;offline:boolean;member?:Member;onPhotoSaved:()=>Promise<void>;draftPhoto?:Blob|null;onDraftPhoto:(photo:Blob|null)=>void;onSubmit:(event:FormEvent)=>void;onCancel?:()=>void};
export default function ProfileStudio({profile,onChange,consent,onConsent,busy,offline,member,onPhotoSaved,draftPhoto,onDraftPhoto,onSubmit,onCancel}:Props){
 const [step,setStep]=useState(0),[error,setError]=useState(''),[draftUrl,setDraftUrl]=useState('');
 useEffect(()=>{if(!draftPhoto){setDraftUrl('');return;}const url=URL.createObjectURL(draftPhoto);setDraftUrl(url);return()=>URL.revokeObjectURL(url);},[draftPhoto]);
 const look=Math.max(0,avatars.indexOf(profile.avatar)),Look=looks[look].Icon;
 function toggle(key:'languages'|'interests',value:string){onChange({...profile,[key]:profile[key].includes(value)?profile[key].filter(x=>x!==value):[...profile[key],value]});}
 function next(){setError('');if(step===0){if(!profile.name.trim()){setError('Tell us what your Yaaros should call you.');return;}try{adultAge(profile.dob);}catch{setError('Enter a valid birthday. YAARO is currently for adults aged 18 and over.');return;}}if(step===1&&(!profile.languages.length||profile.interests.length<3)){setError('Pick at least one language and three interests.');return;}setStep(Math.min(3,step+1));}
 function changeStep(value:number){setError('');setStep(value);}
 return <div className="profile-studio" data-reveal>
  <aside className="studio-story"><img src="/yaaro-logo.png" width="150" height="58" alt="YAARO"/><span className="studio-kicker">A LITTLE YOU. A LOT OF POSSIBILITY.</span><h1>Your people.<br/>Your world.<br/><span>Your YAARO.</span></h1><p>A playlist, a big idea, a little hello. Let people discover what makes you, you.</p><div className={`studio-preview studio-look-${look}`}><div className="studio-preview-orbit" aria-hidden="true"/>{draftUrl?<img className="studio-draft-photo" src={draftUrl} alt="Your selected profile photo"/>:draftPhoto===undefined&&member?.photoUrl?<MemberAvatar member={member} size="profile-avatar"/>:<span className="studio-avatar"><Look size={38}/></span>}<h2>{profile.name.trim()||'Your name here'}</h2><VibeTag name={profile.vibe}/><p>{profile.bio||'A little about you goes a long way.'}</p><div className="studio-preview-tags">{profile.interests.slice(0,3).map(value=><span key={value}>{value}</span>)}</div></div><span className="studio-privacy"><ShieldCheck size={16}/> Your birthday and contact details stay private.</span></aside>
  <form className="studio-form" onSubmit={event=>{event.preventDefault();if(step<3)next();else onSubmit(event);}}>
   <div className="studio-step-nav" aria-label="Profile creation progress">{steps.map(({name,Icon},index)=><span key={name} className={index===step?'current':index<step?'complete':''} aria-current={index===step?'step':undefined}><i>{index<step?<Check size={15}/>:<Icon size={15}/>}</i><small>{name}</small></span>)}</div><div className="studio-progress"><span style={{width:`${(step+1)*25}%`}}/></div>
   <div className="studio-step" key={step}>
    <span className="eyebrow">STEP {step+1} OF 4</span>
    {step===0&&<><h2>Hey, future Yaaro.</h2><p>Start with your photo, then add a little about yourself.</p><section className="studio-photo-first" aria-label="Profile photo"><div className="studio-photo-first-preview">{draftUrl?<img src={draftUrl} alt="Your selected profile photo"/>:draftPhoto===undefined&&member?.photoUrl?<MemberAvatar member={member} size="profile-avatar"/>:<span className="studio-avatar"><Look size={32}/></span>}</div><div><h3>Your profile photo</h3><ProfilePhoto member={member} onSaved={onPhotoSaved} draftPhoto={draftPhoto} onDraft={onDraftPhoto} disabled={busy||offline}/></div></section><label>What should we call you?<input autoComplete="nickname" required value={profile.name} maxLength={40} onChange={e=>onChange({...profile,name:e.target.value})} placeholder="Your display name"/></label><div className="form-two"><label>Birthday <small>Only you can see this</small><input type="date" required value={profile.dob} max={new Date().toISOString().slice(0,10)} onChange={e=>onChange({...profile,dob:e.target.value})}/></label><label>Your region <small>Share only an approximate region</small><select value={profile.region} onChange={e=>onChange({...profile,region:e.target.value})}>{regions.map(value=><option key={value}>{value}</option>)}</select></label></div><div className="studio-note"><ShieldCheck size={19}/><span>Your email, phone number, and full birthday never appear on your public profile.</span></div></>}
    {step===1&&<><h2>Find your common ground.</h2><p>Shared interests make the first hello a little easier.</p><div className="row-title"><h3>Your languages</h3><small>{profile.languages.length} selected</small></div><div className="studio-choices">{languages.map(value=><button type="button" aria-pressed={profile.languages.includes(value)} className={profile.languages.includes(value)?'selected':''} key={value} onClick={()=>toggle('languages',value)}>{value}{profile.languages.includes(value)&&<Check size={13}/>}</button>)}</div><div className="row-title"><h3>Things you’re into</h3><small>{profile.interests.length}/3 minimum</small></div><div className="studio-choices interests">{interests.map(value=><button type="button" aria-pressed={profile.interests.includes(value)} className={profile.interests.includes(value)?'selected':''} key={value} onClick={()=>toggle('interests',value)}>{value}{profile.interests.includes(value)&&<Check size={13}/>}</button>)}</div></>}
    {step===2&&<><h2>Let your energy show.</h2><p>Pick an avatar and the vibe you’re bringing today.</p><div className="studio-avatar-options">{looks.map(({Icon,label},index)=><button key={label} type="button" className={look===index?'selected':''} aria-label={`Choose ${label} avatar`} aria-pressed={look===index} onClick={()=>onChange({...profile,avatar:avatars[index]})}><Icon size={23}/><small>{label}</small>{look===index&&<Check size={12}/>}</button>)}</div><h3>Your current vibe</h3><VibePicker compact value={profile.vibe} onChange={vibe=>onChange({...profile,vibe})}/><label>Your little intro <small>Optional · {profile.bio.length}/250</small><textarea value={profile.bio} maxLength={250} placeholder="A song on repeat? A place you love? Tell us a little." onChange={e=>onChange({...profile,bio:e.target.value})}/></label></>}
    {step===3&&<><h2>This is your beginning.</h2><p>Take a look. Your next connection starts here.</p><div className="studio-review"><span className="studio-review-photo">{draftUrl?<img src={draftUrl} alt="Your selected profile photo"/>:draftPhoto===undefined&&member?.photoUrl?<MemberAvatar member={member} size="profile-avatar"/>:<span className="studio-avatar"><Look size={31}/></span>}</span><div><h3>{profile.name}</h3><VibeTag name={profile.vibe}/><p>{profile.languages.join(' · ')} · {profile.region}</p></div><button type="button" className="text-link" disabled={busy} onClick={()=>changeStep(0)}>Edit</button></div><div className="studio-review-interests">{profile.interests.map(value=><span key={value}>{value}</span>)}</div>{profile.bio&&<blockquote className="studio-bio">{profile.bio}</blockquote>}<label className="checkbox publish-consent"><input type="checkbox" required checked={consent} onChange={e=>onConsent(e.target.checked)}/><span>I’m 18 or older, agree to the <a href="/policy/community">Community Guidelines</a>, and want to share this display profile with people who can access YAARO.</span></label><div className="studio-note"><Heart size={20}/><span>Good connections happen at your pace. Your privacy choices are always yours.</span></div></>}
   </div>
   {error&&<p className="form-notice" role="alert">{error}</p>}
   <div className="studio-footer">{step>0?<button type="button" className="button outline" disabled={busy} onClick={()=>changeStep(step-1)}><ArrowLeft size={16}/> Back</button>:onCancel?<button type="button" className="button outline" disabled={busy} onClick={onCancel}>Cancel</button>:<small>Meet. Talk. Connect.</small>}{step<3?<button type="button" className="button primary" disabled={busy||offline} onClick={next}>Continue <ArrowRight size={17}/></button>:<button type="submit" className="button primary" disabled={busy||offline||!consent||profile.interests.length<3||!profile.languages.length}>{busy?'Saving…':member?'Save my profile':'Find my Yaaro'}<ArrowRight size={17}/></button>}</div>
  </form>
 </div>;
}
