'use client';
import {useState,type ReactNode} from 'react';
import {ArrowUpRight,ArrowRight,Plus,Pin,Star,Compass,MessageCircle,Zap,ShieldCheck,Bell,Heart,Phone,Video,Check,SlidersHorizontal,Sparkles,Globe2} from 'lucide-react';
import {MemberAvatar,ProfilePhoto} from './profile-photo';
import {VibeTag,VibeIcon,Empty} from './ui';
import type {Friendship,Member,Self} from '@/lib/community-model';
export function SocialHome({me,friends,people,incoming,onNavigate,onVibe,onView,renderCard}:{me:Self;friends:Friendship[];people:Member[];incoming:number;onNavigate:(tab:string)=>void;onVibe:()=>void;onView:(member:Member)=>void;renderCard:(member:Member)=>ReactNode}){
 const circle=[...friends].sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||Number(!!b.favorite)-Number(!!a.favorite)||Number(b.person.online)-Number(a.person.online)).slice(0,8);
 const unread=friends.reduce((total,friend)=>total+(friend.unreadCount||0),0);
 return <div className="social-home">
  <div className="social-heading"><div><span className="eyebrow">YOUR DAILY DOSE OF GOOD ENERGY</span><h1>Hey, {me.name}<span className="greeting-spark"><Sparkles size={25}/></span></h1><p>A new conversation could change your day.</p></div><button className="social-vibe-button" onClick={onVibe}><VibeIcon name={me.vibe} size={21}/><span>Feeling <b>{me.vibe}</b></span><SlidersHorizontal size={15}/></button></div>
  <div className="circle-strip panel"><button className="circle-person own" onClick={onVibe}><span className="circle-ring"><MemberAvatar member={me}/><i><Plus size={13}/></i></span><b>Your vibe</b></button>{circle.map(friend=><button className={`circle-person ${friend.person.online?'online':''}`} key={friend.id} onClick={()=>onView(friend.person)}><span className="circle-ring"><MemberAvatar member={friend.person}/>{friend.favorite&&<i><Star size={11}/></i>}</span><b>{friend.person.name}</b></button>)}{!circle.length&&<div className="circle-invitation"><span>Your circle starts with one hello.</span><button className="text-link" onClick={()=>onNavigate('discover')}>Find your first Yaaro <ArrowRight size={13}/></button></div>}</div>
  <section className="social-hero" data-reveal><div className="social-hero-copy"><span className="hero-label"><span/> MADE FOR YOUR KIND OF PEOPLE</span><h2>Less scrolling.<br/><span>More connecting.</span></h2><p>Your interests. Your energy. A whole world of people to share them with.</p><div><button className="button white" onClick={()=>onNavigate('connect')}><Zap size={17}/> Find my Yaaro</button><button className="hero-secondary" onClick={()=>onNavigate('discover')}>Explore <ArrowUpRight size={17}/></button></div></div><div className="social-hero-art" aria-hidden="true"><i className="hero-orbit orbit-one"/><i className="hero-orbit orbit-two"/><div className="hero-brand-disc"><img src="/yaaro-logo.png" alt="" width="210" height="88"/><span>meet. talk. connect.</span></div><span className="hero-token token-one"><MessageCircle size={19}/></span><span className="hero-token token-two"><Heart size={19}/></span><span className="hero-token token-three"><VibeIcon name={me.vibe} size={20}/></span></div></section>
  <div className="social-shortcuts"><button onClick={()=>onNavigate('chats')}><span><MessageCircle size={20}/></span><div><b>Keep the conversation going</b><small>{unread?`${unread} unread messages`:'A little hello goes a long way'}</small></div><ArrowUpRight size={17}/></button><button onClick={()=>onNavigate('notifications')}><span><Heart size={20}/></span><div><b>Make room for a new Yaaro</b><small>{incoming?`${incoming} connection ${incoming===1?'request':'requests'} waiting`:'Your next connection is out there'}</small></div><ArrowUpRight size={17}/></button></div>
  <div className="social-section-heading"><div><span className="eyebrow">NEW FACES. SHARED ENERGY.</span><h2>People you may vibe with</h2></div><button className="text-link" onClick={()=>onNavigate('discover')}>See all <ArrowUpRight size={15}/></button></div>
  {people.length?<div className="real-people-grid">{people.slice(0,3).map(renderCard)}</div>:<Empty title="Your people are on their way." description="New members will appear as they join and share their profiles."><button className="button outline" onClick={()=>onNavigate('discover')}>Explore discovery</button></Empty>}
  <div className="social-kind-note"><ShieldCheck size={22}/><div><b>Your pace. Your boundaries.</b><p>Connect when it feels right. You choose who can message and call you.</p></div><button onClick={()=>onNavigate('profile')} aria-label="Review privacy settings"><ArrowRight size={19}/></button></div>
 </div>;
}
export function ConnectScene({people,matching,attempted,match,friend,disabled,onLanguage,onVibe,onFind,onExplore,onStart,renderCard}:{people:Member[];matching:boolean;attempted:boolean;match:Member|null;friend?:Friendship;disabled:boolean;onLanguage:ReactNode;onVibe:ReactNode;onFind:()=>void;onExplore:()=>void;onStart:(friend:Friendship,mode:'text'|'voice'|'video')=>void;renderCard:(member:Member)=>ReactNode}){
 const [mode,setMode]=useState<'text'|'voice'|'video'>('text');
 return <div className="connect-experience"><div className="social-heading centered"><span className="eyebrow"><Zap size={14}/> THE FIRST HELLO STARTS HERE</span><h1>Find your wavelength.</h1><p>Good energy. Shared interests. Someone new to talk to.</p></div><div className={`connect-scene panel ${matching?'searching':''}`}><div className="connect-radar" aria-hidden="true"><i/><i/><i/><span className="radar-brand"><img src="/yaaro-logo.png" alt="" width="140" height="60"/></span>{people.slice(0,3).map((person,index)=><span className={`radar-person radar-person-${index}`} key={person.id}><MemberAvatar member={person}/></span>)}</div><h2>How do you want to connect?</h2><div className="connect-mode-picker">{([{id:'text',label:'Text',Icon:MessageCircle},{id:'voice',label:'Voice',Icon:Phone},{id:'video',label:'Video',Icon:Video}] as const).map(({id,label,Icon})=><button key={id} aria-pressed={mode===id} className={mode===id?'selected':''} onClick={()=>setMode(id)}><Icon size={23}/><b>{label}</b><small>{id==='text'?'Start a conversation':id==='voice'?'Hear their story':'See a friendly face'}</small>{mode===id&&<Check size={13}/>}</button>)}</div><div className="connect-filter-wrap"><span><SlidersHorizontal size={15}/> Fine-tune your vibe</span><div className="connect-filters">{onLanguage}{onVibe}</div></div><button className="button primary connect-find" disabled={matching||disabled} onClick={onFind}>{matching?<><span className="search-pulse"><i/><i/><i/></span>Finding your wavelength…</>:<><Zap size={18}/> Find my Yaaro <ArrowRight size={18}/></>}</button><p className="connect-consent"><ShieldCheck size={14}/> Both people say yes before chatting or calling. Your camera and microphone stay off until you start or accept a call.</p></div>{match&&!matching&&<section className="connect-result" data-reveal><span className="eyebrow"><Sparkles size={14}/> A NEW CONNECTION COULD START HERE</span><h2>Meet {match.name}.</h2>{renderCard(match)}{friend?.status==='accepted'&&<button className="button primary" onClick={()=>onStart(friend,mode)}>{mode==='text'?'Open conversation':`Start ${mode} call`}<ArrowRight size={17}/></button>}</section>}{attempted&&!matching&&!match&&<Empty title="No one available with this vibe yet." description="Try another language or vibe, or explore everyone in Discover."><button className="button outline" onClick={onExplore}>Discover Yaaros</button></Empty>}<button className="connect-explore" onClick={onExplore}><Compass size={17}/> Discover all Yaaros <ArrowUpRight size={16}/></button></div>;
}
export function ProfileHeader({me,friends,pane,onPane,onEdit,onPhotoSaved}:{me:Self;friends:Friendship[];pane:string;onPane:(pane:string)=>void;onEdit:()=>void;onPhotoSaved:()=>Promise<void>}){
 return <section className="social-profile panel" data-reveal><div className="social-profile-cover"><span className="profile-cover-word" aria-hidden="true">YOUR WORLD.</span><i/><i/><span className="profile-cover-brand">YAARO / {me.vibe.toUpperCase()}</span></div><div className="social-profile-identity"><span className="profile-photo-ring"><MemberAvatar member={me} size="profile-avatar"/></span><button className="button outline small" onClick={onEdit}>Edit profile <ArrowUpRight size={15}/></button></div><div className="social-profile-details"><h1>{me.name}<span className="profile-age">{me.age}</span></h1><VibeTag name={me.vibe}/><p>{me.bio||'Your story is just getting started.'}</p><span className="profile-languages"><Globe2 size={14}/>{me.languages.join(' · ')}{me.region!=='Prefer not to say'&&` / ${me.region}`}</span><div className="social-profile-stats"><button onClick={()=>onPane('connections')}><b>{friends.length}</b><span>Yaaros</span></button><button onClick={()=>onPane('connections')}><b>{friends.filter(f=>f.pinned).length}<Pin size={12}/></b><span>Pinned</span></button><button onClick={()=>onPane('connections')}><b>{friends.filter(f=>f.favorite).length}<Star size={12}/></b><span>Favorites</span></button></div><ProfilePhoto member={me} onSaved={onPhotoSaved}/></div><nav className="profile-content-tabs" aria-label="Profile sections">{[['about','About me'],['connections','My Yaaros'],['settings','Settings & privacy']].map(([id,label])=><button key={id} className={pane===id?'selected':''} aria-pressed={pane===id} onClick={()=>onPane(id)}>{label}</button>)}</nav></section>;
}
export function NotificationCenter({incoming,outgoing,friends,enabled,onEnable,renderRequest,onChat,onSettings}:{incoming:Friendship[];outgoing:Friendship[];friends:Friendship[];enabled:boolean;onEnable:()=>void;renderRequest:(friend:Friendship,kind:string)=>ReactNode;onChat:(friend:Friendship)=>void;onSettings:()=>void}){
 const [filter,setFilter]=useState('all');const unread=friends.filter(friend=>!!friend.unreadCount);const recent=friends.filter(friend=>Date.now()-friend.updatedAt<7*86400000).slice(0,6);
 return <div className="notification-center"><div className="social-heading"><div><span className="eyebrow">YOUR PEOPLE, KEEPING IN TOUCH</span><h1>Your notifications.</h1><p>The hellos, conversations, and connections that matter.</p></div><button className="button outline small" onClick={onEnable}>{enabled?'Turn off browser alerts':'Enable browser alerts'}<Bell size={15}/></button></div><div className="notification-tabs">{[['all','All activity'],['requests','Requests'],['messages','Messages']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}{id==='requests'&&!!incoming.length&&<span>{incoming.length}</span>}{id==='messages'&&!!unread.length&&<span>{unread.length}</span>}</button>)}</div>
  {filter!=='messages'&&<section className="notification-section panel"><div className="notification-section-heading"><span><Heart size={19}/> New Yaaro requests</span><small>{incoming.length} waiting</small></div>{incoming.length?incoming.map(friend=>renderRequest(friend,'incoming')):<div className="notification-zero"><Check size={18}/><p>You’re all caught up on connection requests.</p></div>}</section>}
  {filter!=='requests'&&<section className="notification-section panel"><div className="notification-section-heading"><span><MessageCircle size={19}/> Conversations</span><small>{unread.length} unread</small></div>{unread.length?unread.map(friend=><button className="activity-row" key={friend.id} onClick={()=>onChat(friend)}><MemberAvatar member={friend.person}/><span><b>{friend.person.name}</b><p>{friend.lastMessage?.deleted?'Message deleted':friend.lastMessage?.body||'Sent you a message'}</p><small>{friend.unreadCount} unread {friend.unreadCount===1?'message':'messages'}</small></span><ArrowUpRight size={18}/></button>):<div className="notification-zero"><MessageCircle size={18}/><p>No unread conversations. A good time for a new hello.</p></div>}</section>}
  {filter==='all'&&!!recent.length&&<section className="notification-section panel"><div className="notification-section-heading"><span><Heart size={19}/> Recent connections</span><small>This week</small></div>{recent.map(friend=><button className="activity-row" key={friend.id} onClick={()=>onChat(friend)}><MemberAvatar member={friend.person}/><span><b>You and {friend.person.name} are Yaaros.</b><p>Your conversation is ready whenever you are.</p><small>{new Date(friend.updatedAt).toLocaleDateString([],{month:'short',day:'numeric'})}</small></span><ArrowUpRight size={18}/></button>)}</section>}
  {filter!=='messages'&&!!outgoing.length&&<section className="notification-section panel"><div className="notification-section-heading"><span><ArrowUpRight size={19}/> Sent requests</span><small>{outgoing.length} pending</small></div>{outgoing.map(friend=>renderRequest(friend,'outgoing'))}</section>}
  <div className="social-kind-note"><Bell size={21}/><div><b>Make notifications work for you.</b><p>Choose who can call and message you, and manage browser alerts.</p></div><button onClick={onSettings} aria-label="Manage notification and privacy settings"><ArrowRight size={19}/></button></div>
 </div>;
}
