'use client';
import {createContext,useContext,useEffect,useRef,useState,useCallback,type ReactNode} from 'react';
import {Volume2} from 'lucide-react';
import {SoundEngine,type SoundKind} from '@/lib/sound-engine';
type Preferences={messages:boolean;notifications:boolean;calls:boolean};
const defaults:Preferences={messages:true,notifications:true,calls:true};
const Context=createContext<{preferences:Preferences;ready:boolean;enable:()=>Promise<boolean>;setPreference:(key:keyof Preferences,value:boolean)=>void;play:(kind:SoundKind,key?:string)=>void;ring:(kind:'incoming'|'outgoing')=>()=>void}|null>(null);
export function useSounds(){const value=useContext(Context);if(!value)throw Error('Sound provider unavailable');return value;}
export function SoundProvider({children}:{children:ReactNode}){
 const [preferences,setPreferences]=useState(defaults),[ready,setReady]=useState(false);const prefs=useRef(preferences);prefs.current=preferences;const engine=useRef<SoundEngine|null>(null),seen=useRef(new Set<string>()),lastTone=useRef(new Map<SoundKind,number>());
 const enable=useCallback(async()=>{if(!engine.current)engine.current=new SoundEngine(()=>{const Audio=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;return new Audio();});const value=await engine.current.unlock();setReady(value);return value;},[]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('yaaro:sounds')||'{}');setPreferences({messages:typeof saved.messages==='boolean'?saved.messages:true,notifications:typeof saved.notifications==='boolean'?saved.notifications:true,calls:typeof saved.calls==='boolean'?saved.calls:true});}catch{}const gesture=(event:Event)=>{if(event.isTrusted)void enable();};window.addEventListener('pointerdown',gesture);window.addEventListener('keydown',gesture);return()=>{window.removeEventListener('pointerdown',gesture);window.removeEventListener('keydown',gesture);engine.current?.dispose();engine.current=null;};},[enable]);
 function setPreference(key:keyof Preferences,value:boolean){setPreferences(current=>{const next={...current,[key]:value};prefs.current=next;try{localStorage.setItem('yaaro:sounds',JSON.stringify(next));}catch{}return next;});}
 const play=useCallback((kind:SoundKind,key?:string)=>{const group=kind==='sent'||kind==='received'?'messages':kind==='notification'?'notifications':'calls';if(!prefs.current[group])return;if(key){if(seen.current.has(key))return;seen.current.add(key);if(seen.current.size>400)seen.current.delete(seen.current.values().next().value!);}const now=Date.now();if(now-(lastTone.current.get(kind)||0)<250)return;lastTone.current.set(kind,now);if(!engine.current?.play(kind))setReady(false);},[]);
 const ring=useCallback((kind:'incoming'|'outgoing')=>{if(!prefs.current.calls)return()=>{};if(!engine.current?.ready)setReady(false);return engine.current?.ring(kind)||(()=>{});},[]);
 return <Context.Provider value={{preferences,ready,enable,setPreference,play,ring}}>{children}</Context.Provider>;
}
export function SoundPreferences(){const {preferences,ready,enable,setPreference,play}=useSounds();return <section className="sound-preferences" aria-label="YAARO sounds"><h3><Volume2 size={18}/> Sounds</h3>{([['messages','Message sounds'],['notifications','Notification sounds'],['calls','Call tones & ringtone']] as const).map(([key,label])=><div className="sound-setting" key={key}><span>{label}</span><button type="button" role="switch" aria-checked={preferences[key]} aria-label={label} onClick={()=>{setPreference(key,!preferences[key]);if(!preferences[key])void enable();}}><span aria-hidden="true"><i/></span><small>{preferences[key]?'On':'Off'}</small></button></div>)}<button type="button" className="text-link" onClick={()=>void enable().then(ok=>{if(ok)play('sent');})}>{ready?'Preview message sound':'Enable & preview sounds'}</button><p>Sounds play while YAARO is open after your first tap. Your device’s volume and browser settings apply.</p></section>;}
