'use client';
import { useEffect,useRef,useState,type ReactNode } from 'react';
import {createPortal} from 'react-dom';
import { X, ShieldCheck, Waves, Laugh, MoonStar, HandHeart, Headphones, Gamepad2, BriefcaseBusiness, HeartHandshake, Clapperboard, Compass, BookOpen, Lightbulb, type LucideIcon } from 'lucide-react';
import { vibes,type Person } from '@/lib/data';
export function Brand(){return <a href="/" className="brand" aria-label="YAARO home"><img src="/yaaro-logo.png" alt="YAARO" width="150" height="58"/><span className="brand-tag">meet. talk. connect.</span></a>}
export function Avatar({person,size='',emoji}:{person?:Person;size?:string;emoji?:string}){return <span className={`avatar ${person?.color||'mint'} ${size}`} aria-label={person?`${person.name} avatar`:undefined}><span>{emoji||person?.name.slice(0,1)||'Y'}</span>{person?.online&&<i className="online-dot"/>}</span>}
const vibeIcons:Record<string,LucideIcon>={Chill:Waves,Fun:Laugh,'Late Night Talk':MoonStar,'Need Someone':HandHeart,Music:Headphones,Gaming:Gamepad2,Career:BriefcaseBusiness,Relationships:HeartHandshake,Movies:Clapperboard,Travel:Compass,Study:BookOpen,Ideas:Lightbulb};
export function VibeIcon({name,size=24}:{name:string;size?:number}){const Icon=vibeIcons[name]||Waves;return <Icon size={size} strokeWidth={1.8} aria-hidden="true"/>}
export function VibeTag({name}:{name:string}){return <span className="vibe-tag"><VibeIcon name={name} size={15}/> {name}</span>}
export function VibePicker({value,onChange,compact=false}:{value:string;onChange:(v:string)=>void;compact?:boolean}){return <div className={`vibes ${compact?'compact':''}`}>{vibes.map(([,name])=><button key={name} className={`vibe ${value===name?'selected':''}`} onClick={()=>onChange(name)} aria-pressed={value===name}><span key={`${name}:${value===name}`} className="vibe-emoji vibe-icon"><VibeIcon name={name} size={28}/></span>{name}</button>)}</div>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDivElement>(null);const closeRef=useRef(onClose);closeRef.current=onClose;const [mounted,setMounted]=useState(false);useEffect(()=>{setMounted(true);},[]);useEffect(()=>{if(!mounted)return;const before=document.activeElement as HTMLElement;const focus=ref.current?.querySelector<HTMLElement>('button,input,select,textarea,a[href]');focus?.focus();const old=document.body.style.overflow;document.body.style.overflow='hidden';document.body.classList.add('yaaro-modal-open');function key(e:KeyboardEvent){if(e.key==='Escape')closeRef.current();if(e.key==='Tab'){const all=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href],[tabindex="0"]');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.body.classList.remove('yaaro-modal-open');document.removeEventListener('keydown',key);before?.focus();}},[mounted]);if(!mounted)return null;return createPortal(<div className="modal-backdrop yaaro-overlay" onClick={onClose}><div ref={ref} role="dialog" aria-modal="true" aria-label={title} className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><X size={22}/></button></div>{children}</div></div>,document.body)}
export function DemoNote({text='Fictional profiles. Explore freely—no one is contacted.'}:{text?:string}){return <div className="demo-note"><span className="demo-label">DEMO</span><span>{text}</span></div>}
export function Empty({title,description,children}:{title:string;description:string;children?:ReactNode}){return <div className="empty"><div className="empty-icon"><ShieldCheck size={30}/></div><h3>{title}</h3><p>{description}</p>{children}</div>}
