import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {db,identity,failure} from '@/lib/server';
import {MediaService} from '@/lib/media-service';
import {mediaGuard,boundedMedia,privateMedia} from '@/lib/media-server';
import {validatePhoto} from '@/lib/photo-validation';
export async function GET(req:Request){try{const user=await identity();if(!user)throw new Error('UNAUTHORIZED');const service=new MediaService(db(),user.userId),params=new URL(req.url).searchParams;if(params.get('photo')==='1')return await privateMedia(await service.momentPhoto(z.string().uuid().parse(params.get('id'))),'image/png');const expired=await service.purgeExpired();if(expired.length)await env.BUCKET?.delete(expired).catch(()=>{});return Response.json({moments:await service.moments()},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(req:Request){let key:string|undefined;try{const user=await mediaGuard(req,'moment_write'),bytes=await boundedMedia(req,1100000),form=await new Response(bytes,{headers:{'Content-Type':req.headers.get('content-type')||''}}).formData();const id=z.string().uuid().parse(form.get('id')),body=z.string().trim().max(500).parse(form.get('body')),visibility=z.enum(['friends','private']).parse(form.get('visibility')),duration=z.enum(['24h','keep']).parse(form.get('duration')),file=form.get('image');if(await new MediaService(db(),user.userId).existingMoment(id))return Response.json({saved:true});if(file instanceof File&&file.size){if(file.type!=='image/png'||!env.BUCKET)throw new Error('INVALID');const photo=new Uint8Array(await file.arrayBuffer());validatePhoto(photo);key=`moments/${id}/${crypto.randomUUID()}.png`;await env.BUCKET.put(key,photo);}if(!body&&!key)throw new Error('INVALID');return Response.json(await new MediaService(db(),user.userId).saveMoment(id,body,visibility,duration,key||null));}catch(e){if(key)await env.BUCKET?.delete(key).catch(()=>{});return failure(e);}}
export async function DELETE(req:Request){try{const user=await mediaGuard(req,'moment_write'),id=z.string().uuid().parse(new URL(req.url).searchParams.get('id')),key=await new MediaService(db(),user.userId).deleteMoment(id);if(key)await env.BUCKET?.delete(key);return Response.json({saved:true});}catch(e){return failure(e);}}
