export const vibes=[['😌','Chill'],['😂','Fun'],['🌙','Late Night Talk'],['🫂','Need Someone'],['🎵','Music'],['🎮','Gaming'],['💼','Career'],['❤️','Relationships'],['🎬','Movies'],['✈️','Travel'],['📚','Study'],['💡','Ideas']];
export const languages=['English','Tamil','Hindi','Kannada','Telugu','Malayalam','Bengali','Marathi','French','Spanish'];
export const interests=['Music','Gaming','Movies','Travel','Photography','Technology','Startups','Books','Fitness','Art','Food','Cricket','Design','Study','Career','Comedy'];
export type Person={id:string;name:string;age:number;city:string;languages:string[];vibe:string;interests:string[];bio:string;emoji:string;color:string;online:boolean};
export const people:Person[]=[
{id:'p1',name:'Aadhya',age:24,city:'Bengaluru',languages:['English','Kannada'],vibe:'Music',interests:['Music','Art','Photography'],bio:'Collecting playlists, little moments, and good conversations.',emoji:'🎧',color:'peach',online:true},
{id:'p2',name:'Kavin',age:25,city:'Chennai',languages:['Tamil','English'],vibe:'Chill',interests:['Movies','Music','Travel'],bio:'Filter coffee. Indie music. A conversation that goes somewhere.',emoji:'☕',color:'mint',online:true},
{id:'p3',name:'Sahana',age:23,city:'Coimbatore',languages:['Tamil','English'],vibe:'Ideas',interests:['Design','Art','Startups'],bio:'Designer by day, big-idea person always. What are you making?',emoji:'🎨',color:'lilac',online:true},
{id:'p4',name:'Arjun',age:26,city:'Hyderabad',languages:['Telugu','Hindi','English'],vibe:'Gaming',interests:['Gaming','Technology','Cricket'],bio:'One more game? Always. Looking for a kind squad.',emoji:'🎮',color:'sky',online:false},
{id:'p5',name:'Meera',age:24,city:'Kochi',languages:['Malayalam','English'],vibe:'Travel',interests:['Travel','Books','Food'],bio:'Slow weekends, new cities, and stories worth sharing.',emoji:'🧳',color:'yellow',online:true},
{id:'p6',name:'Rohan',age:27,city:'Mumbai',languages:['Hindi','English','Marathi'],vibe:'Career',interests:['Startups','Career','Technology'],bio:'Building something small. Happy to swap ideas and cheer you on.',emoji:'💡',color:'rose',online:false}];
export const rooms=[{id:'r1',emoji:'🎵',title:'Tamil Music Addicts',topic:'The playlist never ends',host:'Kavin',count:12,color:'mint'}, {id:'r2',emoji:'🌙',title:'Late Night Talks',topic:'A little space to unwind',host:'Aadhya',count:8,color:'lilac'}, {id:'r3',emoji:'💼',title:'Startup Talks',topic:'Small ideas. Big possibilities.',host:'Rohan',count:16,color:'sky'}, {id:'r4',emoji:'📚',title:'Study Together',topic:'Focus feels better together',host:'Meera',count:6,color:'yellow'}, {id:'r5',emoji:'😂',title:'Just For Fun',topic:'Bring your best bad joke',host:'Sahana',count:9,color:'peach'}, {id:'r6',emoji:'🎮',title:'Gamers Adda',topic:'Find your next squad',host:'Arjun',count:10,color:'rose'}];
export type Message={id:string;person:string;text:string;own:boolean;reaction?:string;reply?:string;time:string};
export type Profile={name:string;dob:string;gender:string;languages:string[];interests:string[];bio:string;vibe:string;avatar:string};
export type Workspace={profile:Profile;requests:string[];connections:string[];blocks:string[];messages:Message[];moments:{id:string;text:string;visibility:string;duration:string;createdAt:number}[];privacy:Record<string,string>;readNotifications:string[];statuses:Record<string,string>;audit:{action:string;target:string;time:string}[]};
export const initial:Workspace={profile:{name:'Yaaro',dob:'',gender:'Prefer not to say',languages:['English','Tamil'],interests:['Music','Movies','Travel'],bio:'Here for good conversations and new perspectives.',vibe:'Chill',avatar:'😌'},requests:[],connections:['p2'],blocks:[],messages:[{id:'m1',person:'p2',text:'Hey! What’s a song you’ve had on repeat lately?',own:false,time:'10:24'},{id:'m2',person:'p2',text:'Anything with a good acoustic guitar ☕',own:true,time:'10:25'},{id:'m3',person:'p2',text:'We’re going to get along. I have a playlist for that!',own:false,time:'10:26'}],moments:[],privacy:{messages:'Connections only',calls:'Connections only',requests:'Everyone',moments:'Friends only',online:'Connections only',discover:'Everyone',visibility:'Discoverable',notifications:'On'},readNotifications:[],statuses:{},audit:[]};
export const reportCategories=['Harassment','Spam','Scam/Fraud','Sexual Content','Threats','Fake Profile','Impersonation','Underage Safety Concern','Child sexual abuse or exploitation','Other'];
export const adminSections=['Overview','Users','Creators','Businesses','Reports','Moderation','Rooms','Moments','Transactions','Coins','Gifts','Advertising','Analytics','Notifications','Settings','Admins','Audit Logs'];
