import {CommunityService} from './community-service';
export class MediaService{
 private community:CommunityService;constructor(private database:D1Database,owner:string){this.community=new CommunityService(database,owner);}
 private stmt(sql:string,...values:any[]){return this.database.prepare(sql).bind(...values);}
 async chatAsset(id:string){const asset=await this.stmt('SELECT cm.*, m.deleted,m.author FROM chat_media cm JOIN chat_messages m ON m.id=cm.message WHERE cm.id=?',id).first<any>();if(!asset||asset.deleted)throw new Error('NOT_FOUND');await this.community.conversationAccess(asset.conversation);return asset;}
 async claimChat(id:string){
  const asset=await this.chatAsset(id),me=await this.community.memberId();if(asset.kind==='voice'||asset.author===me)throw new Error('FORBIDDEN');
  const now=Date.now(),result=await this.stmt(`INSERT INTO chat_media_views(message,viewer,opened_at) SELECT m.id,?,? FROM chat_messages m JOIN chat_media cm ON cm.message=m.id JOIN friendships f ON f.id=m.conversation AND f.status='accepted' JOIN members a ON a.id=m.author AND a.status='active' JOIN members v ON v.id=? AND v.status='active' WHERE m.id=? AND m.deleted=0 AND m.author!=? AND cm.kind IN ('photo','video') AND (f.member_a=? OR f.member_b=?) AND NOT EXISTS(SELECT 1 FROM member_blocks b WHERE (b.blocker=? AND b.blocked=m.author) OR (b.blocker=m.author AND b.blocked=?)) ON CONFLICT(message) DO NOTHING`,me,now,me,id,me,me,me,me,me).run();if(!result.meta.changes)throw new Error('VIEWED');
  await this.stmt('UPDATE chat_messages SET receiver_read_at=COALESCE(receiver_read_at,?) WHERE id=?',now,id).run();return asset;
 }
 async closeChat(id:string){const me=await this.community.memberId();await this.stmt('DELETE FROM chat_messages WHERE id=? AND EXISTS(SELECT 1 FROM chat_media_views v WHERE v.message=chat_messages.id AND v.viewer=?)',id,me).run();return {saved:true};}
 async checkSend(conversation:string){const access=await this.community.conversationAccess(conversation);if(JSON.parse(access.peer.privacy).messages==='Nobody')throw new Error('FORBIDDEN');return access;}
 async existingChat(id:string,conversation:string){const {me}=await this.checkSend(conversation);const m=await this.stmt('SELECT m.author,m.conversation,cm.id AS asset FROM chat_messages m LEFT JOIN chat_media cm ON cm.message=m.id WHERE m.id=?',id).first<any>();if(!m)return false;if(m.author!==me.id||m.conversation!==conversation)throw new Error('FORBIDDEN');if(!m.asset)throw new Error('CONFLICT');return true;}
 async existingMoment(id:string){const me=await this.community.memberId(),m=await this.stmt('SELECT author FROM member_moments WHERE id=?',id).first<any>();if(!m)return false;if(m.author!==me)throw new Error('FORBIDDEN');return true;}
 async saveChat(id:string,conversation:string,kind:'photo'|'voice'|'video',key:string){
 const {me,peer}=await this.checkSend(conversation);const existing=await this.stmt('SELECT id,author,conversation FROM chat_messages WHERE id=?',id).first<any>();if(existing){if(existing.author!==me.id||existing.conversation!==conversation)throw new Error('FORBIDDEN');throw new Error('CONFLICT');}
 const now=Date.now(),body=kind==='photo'?'Photo':kind==='video'?'Video':'Voice note',mime=kind==='photo'?'image/png':kind==='video'?'video/mp4':'audio/wav';
 const result=await this.database.batch([
 this.stmt("INSERT INTO chat_messages (id,conversation,author,body,reply_id,deleted,created_at) SELECT ?,?,?,?,NULL,0,? WHERE EXISTS (SELECT 1 FROM friendships WHERE id=? AND status='accepted') AND EXISTS (SELECT 1 FROM members WHERE id=? AND status='active' AND json_extract(privacy,'$.messages')!='Nobody') AND EXISTS (SELECT 1 FROM members WHERE id=? AND status='active') AND NOT EXISTS (SELECT 1 FROM member_blocks WHERE (blocker=? AND blocked=?) OR (blocker=? AND blocked=?))",id,conversation,me.id,body,now,conversation,peer.id,me.id,me.id,peer.id,peer.id,me.id),
 this.stmt('INSERT INTO chat_media (id,message,conversation,storage_key,kind,content_type,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM chat_messages WHERE id=? AND author=? AND conversation=?)',id,id,conversation,key,kind,mime,now,id,me.id,conversation)
 ]);if(!result[0].meta.changes||!result[1].meta.changes)throw new Error('FORBIDDEN');return {saved:true};
 }
 private scope=`(m.author=? OR ((m.visibility='everyone' OR (m.visibility IN ('friends','selected') AND EXISTS (SELECT 1 FROM friendships f WHERE f.status='accepted' AND ((f.member_a=? AND f.member_b=m.author) OR (f.member_b=? AND f.member_a=m.author))) AND (m.visibility='friends' OR EXISTS (SELECT 1 FROM moment_recipients r WHERE r.moment=m.id AND r.member=?)))) AND NOT EXISTS (SELECT 1 FROM member_blocks b WHERE (b.blocker=? AND b.blocked=m.author) OR (b.blocker=m.author AND b.blocked=?))))`;
 private scopeValues(me:string){return [me,me,me,me,me,me];}
 async purgeExpired(){await this.community.memberId();const now=Date.now(),rows=await this.stmt('SELECT id,photo_key FROM member_moments WHERE expires_at IS NOT NULL AND expires_at<=? LIMIT 20',now).all<any>();if(rows.results.length)await this.database.batch(rows.results.map(m=>this.stmt('DELETE FROM member_moments WHERE id=? AND expires_at<=?',m.id,now)));return rows.results.map(m=>m.photo_key).filter(Boolean) as string[];}
 async moments(){const me=await this.community.memberId();const rows=await this.stmt(`SELECT m.*,u.name,EXISTS(SELECT 1 FROM moment_views v WHERE v.moment=m.id AND v.member=?) AS viewed FROM member_moments m JOIN members u ON u.id=m.author AND u.status='active' WHERE (m.expires_at IS NULL OR m.expires_at>?) AND (${this.scope}) ORDER BY m.created_at DESC LIMIT 40`,me,Date.now(),...this.scopeValues(me)).all<any>();return rows.results.map(m=>({id:m.id,author:m.author,name:m.name,visibility:m.visibility,createdAt:m.created_at,expiresAt:m.expires_at,own:m.author===me,kind:m.media_kind,viewed:!!m.viewed}));}
 async momentAsset(id:string){const me=await this.community.memberId();const m=await this.stmt(`SELECT m.* FROM member_moments m JOIN members u ON u.id=m.author AND u.status='active' WHERE m.id=? AND (m.expires_at IS NULL OR m.expires_at>?) AND (${this.scope})`,id,Date.now(),...this.scopeValues(me)).first<any>();if(!m)throw new Error('NOT_FOUND');return m;}
 async momentPhoto(id:string){await this.momentAsset(id);throw new Error('FORBIDDEN');}
 async claimMoment(id:string){const me=await this.community.memberId();await this.momentAsset(id);const result=await this.stmt(`INSERT INTO moment_views(moment,member,viewed_at) SELECT m.id,?,? FROM member_moments m JOIN members u ON u.id=m.author AND u.status='active' WHERE m.id=? AND (m.expires_at IS NULL OR m.expires_at>?) AND (${this.scope}) AND NOT EXISTS(SELECT 1 FROM moment_views v WHERE v.moment=m.id AND v.member=?) ON CONFLICT(moment,member) DO NOTHING`,me,Date.now(),id,Date.now(),...this.scopeValues(me),me).run();if(!result.meta.changes)throw new Error('VIEWED');}
 async saveMoment(id:string,body:string,visibility:'friends'|'private'|'everyone'|'selected',duration:'24h'|'keep',key:string|null,recipients:string[]=[],kind:'photo'|'video'='photo'){
 const me=await this.community.memberId(),now=Date.now(),targets=[...new Set(recipients)];
 if(visibility==='selected'){
 if(!targets.length||targets.length>100||targets.includes(me))throw new Error('INVALID');
 for(const target of targets){const pair=[me,target].sort().join(':');const access=await this.community.conversationAccess(pair);if(access.peer.id!==target)throw new Error('FORBIDDEN');}
 }else if(targets.length)throw new Error('INVALID');
 const writes=[this.stmt("INSERT INTO member_moments (id,author,body,visibility,expires_at,created_at,photo_key,media_kind) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM members WHERE id=? AND status='active')",id,me,body,visibility,duration==='24h'?now+86400000:null,now,key,kind,me)];
 for(const target of targets)writes.push(this.stmt("INSERT INTO moment_recipients(moment,member) SELECT ?,? WHERE EXISTS(SELECT 1 FROM friendships WHERE id=? AND status='accepted') AND EXISTS(SELECT 1 FROM members WHERE id=? AND status='active') AND NOT EXISTS(SELECT 1 FROM member_blocks WHERE (blocker=? AND blocked=?) OR (blocker=? AND blocked=?))",id,target,[me,target].sort().join(':'),target,me,target,target,me));
 const results=await this.database.batch(writes);if(results.some(r=>!r.meta.changes)){await this.stmt('DELETE FROM member_moments WHERE id=? AND author=?',id,me).run();throw new Error('FORBIDDEN');}return {saved:true};
 }
 async deleteMoment(id:string){const me=await this.community.memberId(),m=await this.stmt('SELECT photo_key FROM member_moments WHERE id=? AND author=?',id,me).first<any>();if(!m)throw new Error('FORBIDDEN');await this.stmt('DELETE FROM member_moments WHERE id=? AND author=?',id,me).run();return m.photo_key as string|null;}
}
