import {encodeVoice} from './media-validation';
export async function prepareChatPhoto(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw new Error('Choose a JPEG, PNG, or WebP image under 5 MB.');const bitmap=await createImageBitmap(file);try{if(bitmap.width>10000||bitmap.height>10000||bitmap.width*bitmap.height>40000000)throw new Error('Choose a smaller photo.');const ratio=Math.min(1,512/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Photo preparation is unavailable.');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob&&blob.size<=1048576?resolve(blob):reject(new Error('Choose a simpler or smaller photo.')),'image/png'));}finally{bitmap.close();}}
export type VoiceCapture={stop:()=>Promise<Blob>;cancel:()=>void};
export async function captureVoice():Promise<VoiceCapture>{
 if(!navigator.mediaDevices?.getUserMedia||!window.AudioContext)throw new Error('Voice notes need a current browser over HTTPS.');const stream=await navigator.mediaDevices.getUserMedia({audio:true});let context:AudioContext|undefined;
 try{context=new AudioContext({sampleRate:16000});if(!context.audioWorklet)throw new Error('Voice recording is unavailable in this browser. Try a current browser over HTTPS.');await context.audioWorklet.addModule('/voice-recorder-worklet.js');await context.resume();const source=context.createMediaStreamSource(stream),node=new AudioWorkletNode(context,'yaaro-voice-recorder'),chunks:Float32Array[]=[];let stopped=false,finish:(()=>void)|undefined;node.port.onmessage=event=>{if(event.data==='done')finish?.();else if(event.data instanceof Float32Array)chunks.push(event.data);};source.connect(node);node.connect(context.destination);
 const close=()=>{stream.getTracks().forEach(track=>track.stop());source.disconnect();node.disconnect();void context!.close();};
 return {cancel(){if(stopped)return;stopped=true;close();},async stop(){if(stopped)throw new Error('Recording cancelled.');stopped=true;await new Promise<void>(resolve=>{const timeout=setTimeout(resolve,1000);finish=()=>{clearTimeout(timeout);resolve();};node.port.postMessage('flush');});close();if(!chunks.length)throw new Error('No audio was recorded.');const bytes=encodeVoice(chunks,context!.sampleRate);if(bytes.length<3244)throw new Error('Record at least a short hello.');return new Blob([bytes],{type:'audio/wav'});}};
 }catch(error){stream.getTracks().forEach(track=>track.stop());void context?.close();throw error;}
}
