import {encodeVoice} from './media-validation';
export async function prepareChatPhoto(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5242880)throw new Error('Choose a JPEG, PNG, or WebP image under 5 MB.');const bitmap=await createImageBitmap(file);try{if(bitmap.width>10000||bitmap.height>10000||bitmap.width*bitmap.height>40000000)throw new Error('Choose a smaller photo.');const ratio=Math.min(1,512/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Photo preparation is unavailable.');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob&&blob.size<=1048576?resolve(blob):reject(new Error('Choose a simpler or smaller photo.')),'image/png'));}finally{bitmap.close();}}
export type VoiceCapture={stop:()=>Promise<Blob>;cancel:()=>void};
export async function captureVoice():Promise<VoiceCapture>{
 if(!navigator.mediaDevices?.getUserMedia||!window.AudioContext)throw new Error('Voice notes need a current browser over HTTPS.');const stream=await navigator.mediaDevices.getUserMedia({audio:true});let context:AudioContext|undefined;
 try{context=new AudioContext({sampleRate:16000});if(!context.audioWorklet)throw new Error('Voice recording is unavailable in this browser. Try a current browser over HTTPS.');await context.audioWorklet.addModule('/voice-recorder-worklet.js');await context.resume();const source=context.createMediaStreamSource(stream),node=new AudioWorkletNode(context,'yaaro-voice-recorder'),chunks:Float32Array[]=[];let stopped=false,finish:(()=>void)|undefined;node.port.onmessage=event=>{if(event.data==='done')finish?.();else if(event.data instanceof Float32Array)chunks.push(event.data);};source.connect(node);node.connect(context.destination);
 const close=()=>{stream.getTracks().forEach(track=>track.stop());source.disconnect();node.disconnect();void context!.close();};
 return {cancel(){if(stopped)return;stopped=true;close();},async stop(){if(stopped)throw new Error('Recording cancelled.');stopped=true;await new Promise<void>(resolve=>{const timeout=setTimeout(resolve,1000);finish=()=>{clearTimeout(timeout);resolve();};node.port.postMessage('flush');});close();if(!chunks.length)throw new Error('No audio was recorded.');const bytes=encodeVoice(chunks,context!.sampleRate);if(bytes.length<3244)throw new Error('Record at least a short hello.');return new Blob([bytes],{type:'audio/wav'});}};
 }catch(error){stream.getTracks().forEach(track=>track.stop());void context?.close();throw error;}
}

export async function prepareMomentVideo(file:File){
 if(file.type!=='video/mp4'||file.size>12*1024*1024)throw new Error('Choose an MP4 video under 12 MB.');
 const {validateMomentVideo}=await import('./moment-video');
 try{validateMomentVideo(new Uint8Array(await file.arrayBuffer()));}catch(e){throw new Error((e as Error).message==='VIDEO_TOO_LONG'?'Videos can be no longer than 10 seconds.':'Choose a standard H.264 MP4 video, up to 10 seconds long.');}
 const url=URL.createObjectURL(file),video=document.createElement('video');video.preload='metadata';
 try{await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Unable to read this video. Try another MP4.')),10000);video.onloadedmetadata=()=>{clearTimeout(timeout);Number.isFinite(video.duration)&&video.duration>0&&video.duration<=10?resolve():reject(new Error('Videos can be no longer than 10 seconds.'));};video.onerror=()=>{clearTimeout(timeout);reject(new Error('This video cannot play in your browser. Choose another MP4.'));};video.src=url;});return file;}
 finally{video.removeAttribute('src');video.load();URL.revokeObjectURL(url);}
}
