export type PushEnv={FCM_SERVICE_ACCOUNT?:string;APNS_KEY_ID?:string;APNS_TEAM_ID?:string;APNS_PRIVATE_KEY?:string;APNS_BUNDLE_ID?:string};
export type PushData={kind:'message'|'call';eventId:string;conversation:string;sender:string;name:string;mode?:string;account:string};
const encode=(v:Uint8Array|string)=>btoa(typeof v==='string'?v:String.fromCharCode(...v)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
async function jwt(header:object,claims:object,pem:string,ec=false){const bytes=Uint8Array.from(atob(pem.replace(/-----[^-]+-----|\s/g,'')),c=>c.charCodeAt(0));const algorithm=ec?{name:'ECDSA',namedCurve:'P-256'}:{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'};const key=await crypto.subtle.importKey('pkcs8',bytes,algorithm,false,['sign']);const body=encode(JSON.stringify(header))+'.'+encode(JSON.stringify(claims));const signature=await crypto.subtle.sign(ec?{name:'ECDSA',hash:'SHA-256'}:algorithm,key,new TextEncoder().encode(body));return body+'.'+encode(new Uint8Array(signature));}
export function pushReady(env:PushEnv,platform:string){return platform==='android'?!!env.FCM_SERVICE_ACCOUNT:!!(env.APNS_KEY_ID&&env.APNS_TEAM_ID&&env.APNS_PRIVATE_KEY&&env.APNS_BUNDLE_ID);}
let oauth:{source:string;expires:number;value:Promise<{token:string;project:string}>}|undefined;
async function fcmAuth(source:string){if(oauth?.source===source&&oauth.expires>Date.now())return oauth.value;const value=(async()=>{const s=JSON.parse(source);if(!s.project_id||!s.client_email||!s.private_key)throw Error('PUSH_CONFIGURATION');const now=Math.floor(Date.now()/1000);const assertion=await jwt({alg:'RS256',typ:'JWT'},{iss:s.client_email,scope:'https://www.googleapis.com/auth/firebase.messaging',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600},s.private_key);const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion}),signal:AbortSignal.timeout(7000)});const data=await response.json() as {access_token?:string};if(!response.ok||!data.access_token)throw Error('PUSH_AUTH');return {token:data.access_token,project:s.project_id as string};})();oauth={source,expires:Date.now()+3000000,value};try{return await value;}catch(e){oauth=undefined;throw e;}}
// Push carries only routing and a generic alert, never message text or media.
export async function deliverPush(env:PushEnv,device:{token:string;platform:string;environment:string},data:PushData):Promise<'sent'|'invalid'|'retry'>{
 const title=data.kind==='call'?`Incoming ${data.mode||'voice'} call`:'YAARO';const body=data.kind==='call'?`${data.name} is calling. Open YAARO to answer.`:`${data.name} sent you a message.`;
 if(device.platform==='android'){const auth=await fcmAuth(env.FCM_SERVICE_ACCOUNT!);const response=await fetch(`https://fcm.googleapis.com/v1/projects/${encodeURIComponent(auth.project)}/messages:send`,{method:'POST',headers:{Authorization:'Bearer '+auth.token,'Content-Type':'application/json'},body:JSON.stringify({message:{token:device.token,data:{...data,title,body},android:{priority:'HIGH',ttl:data.kind==='call'?'90s':'3600s',collapse_key:data.kind==='call'?data.eventId:data.conversation}}}),signal:AbortSignal.timeout(7000)});if(response.ok)return 'sent';const result=await response.json() as {error?:{details?:{errorCode?:string}[]}};return result.error?.details?.some(d=>d.errorCode==='UNREGISTERED')?'invalid':'retry';}
 const now=Math.floor(Date.now()/1000),authorization=await jwt({alg:'ES256',kid:env.APNS_KEY_ID},{iss:env.APNS_TEAM_ID,iat:now},env.APNS_PRIVATE_KEY!,true);
 const response=await fetch(`https://${device.environment==='sandbox'?'api.sandbox.push.apple.com':'api.push.apple.com'}/3/device/${device.token}`,{method:'POST',headers:{authorization:'bearer '+authorization,'apns-topic':env.APNS_BUNDLE_ID!,'apns-push-type':'alert','apns-priority':'10','apns-expiration':String(now+(data.kind==='call'?90:3600)),'Content-Type':'application/json'},body:JSON.stringify({aps:{alert:{title,body},sound:'default'},...data}),signal:AbortSignal.timeout(7000)});if(response.ok)return 'sent';const result=await response.json() as {reason?:string};return ['BadDeviceToken','Unregistered','DeviceTokenNotForTopic'].includes(result.reason||'')?'invalid':'retry';
}
