import {Capacitor,registerPlugin} from '@capacitor/core';
import {PushNotifications} from '@capacitor/push-notifications';
import {api} from './services';
export const nativeApp=()=>Capacitor.isNativePlatform();
export const NativeChat=registerPlugin<{setAccount(o:{account:string;enabled:boolean}):Promise<void>;cacheAvatar(o:{member:string;data:string;account:string}):Promise<void>;openBubbleSettings():Promise<void>}>('YaaroChat');
let token='',account='',registeredAccount='',pending:({resolve:()=>void;reject:(e:Error)=>void})|undefined,listeners:Promise<void>|undefined;
let pendingOpen:Record<string,string>|undefined;
export function consumeNativeNotification(){if(!account||!pendingOpen)return;const data=pendingOpen;pendingOpen=undefined;return data.account===account?data:undefined;}
export function openNativeNotification(data:Record<string,string>){if(account&&data.account&&data.account!==account)return;const conversation=data.conversation;if(!conversation||conversation.length>100)return;pendingOpen=data;window.dispatchEvent(new CustomEvent('yaaro-native-open',{detail:data}));}
async function installListeners(){if(listeners)return listeners;listeners=(async()=>{await PushNotifications.addListener('registration',async t=>{token=t.value;try{const result=await api('/api/native-devices','POST',{action:'register',token,platform:Capacitor.getPlatform()});if(!account||result.member!==account)throw Error('Account changed.');registeredAccount=account;localStorage.setItem('yaaro-native-push','on');if(Capacitor.getPlatform()==='android')await NativeChat.setAccount({account,enabled:true});pending?.resolve();pending=undefined;window.dispatchEvent(new Event('yaaro-push-enabled'));}catch{pending?.reject(Error('Unable to register this phone. Please try again.'));pending=undefined;window.dispatchEvent(new Event('yaaro-push-error'));}});await PushNotifications.addListener('registrationError',()=>{pending?.reject(Error('Notification registration failed.'));pending=undefined;window.dispatchEvent(new Event('yaaro-push-error'));});await PushNotifications.addListener('pushNotificationActionPerformed',event=>openNativeNotification(event.notification.data||{}));})();return listeners;}
export async function setNativeAccount(value:string){if(!nativeApp())return;const changed=account!==value;account=value;if(Capacitor.getPlatform()==='android')await NativeChat.setAccount({account:value,enabled:!!value&&localStorage.getItem('yaaro-native-push')==='on'});if(!value){await PushNotifications.removeAllDeliveredNotifications();return;}await installListeners();if(localStorage.getItem('yaaro-native-push')==='on'&&(changed||registeredAccount!==value)){const permission=await PushNotifications.checkPermissions();if(permission.receive==='granted')await PushNotifications.register();}}
export async function enableNativeNotifications(){await installListeners();const ready=await api('/api/native-devices');if(!ready[Capacitor.getPlatform()])throw Error('App notifications are awaiting configuration.');const status=await PushNotifications.requestPermissions();if(status.receive!=='granted')throw Error('Allow notifications in your phone settings to receive messages and calls.');const registered=new Promise<void>((resolve,reject)=>{pending={resolve,reject};});const timeout=setTimeout(()=>{pending?.reject(Error('Registration is taking longer than expected. Please try again.'));pending=undefined;},15000);try{void PushNotifications.register().catch(()=>{pending?.reject(Error('Notification registration failed.'));pending=undefined;});await registered;}finally{clearTimeout(timeout);pending=undefined;}}
export async function disableNativeNotifications(){if(token)await api('/api/native-devices','POST',{action:'remove',token});await PushNotifications.unregister();await PushNotifications.removeAllDeliveredNotifications();localStorage.removeItem('yaaro-native-push');token='';registeredAccount='';if(Capacitor.getPlatform()==='android')await NativeChat.setAccount({account:'',enabled:false});}
export async function nativeSignOut(){if(nativeApp())await disableNativeNotifications();}
