import {CommunityService} from './community-service';
import {pushReady,deliverPush,pushFailureDetails,type PushEnv,type PushData} from './native-push-provider';
export async function nativeDeviceId(token:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))].map(v=>v.toString(16).padStart(2,'0')).join('');}
export class NativeDevices{
 constructor(private db:D1Database,private owner:string){}
 async register(token:string,platform:'android'|'ios',environment:'sandbox'|'production'){const member=await new CommunityService(this.db,this.owner).memberId();const active=await this.db.prepare("SELECT id FROM members WHERE id=? AND status='active'").bind(member).first();if(!active)throw Error('FORBIDDEN');await this.db.prepare('INSERT INTO native_devices(token,device_id,member,platform,environment,enabled,updated_at) VALUES(?,?,?,?,?,1,?) ON CONFLICT(token) DO UPDATE SET member=excluded.member,platform=excluded.platform,environment=excluded.environment,enabled=1,updated_at=excluded.updated_at').bind(token,await nativeDeviceId(token),member,platform,environment,Date.now()).run();await this.db.prepare('DELETE FROM native_push_jobs WHERE token=? AND recipient!=?').bind(token,member).run();return {saved:true,member};}
 async removeDevice(id:string){await this.db.prepare('DELETE FROM native_devices WHERE device_id=? AND member IN(SELECT id FROM members WHERE owner=?)').bind(id,this.owner).run();}
 async remove(token:string){const member=await new CommunityService(this.db,this.owner).memberId();await this.db.prepare('DELETE FROM native_devices WHERE token=? AND member=?').bind(token,member).run();return {saved:true};}
}
type Job={id:string;token:string;kind:'message'|'call';event_id:string;recipient:string;sender:string;conversation:string;expires_at:number;attempts:number;platform:string;environment:string};
export async function drainNativePush(db:D1Database,env:PushEnv,send=deliverPush){const now=Date.now();await db.prepare('DELETE FROM native_push_jobs WHERE expires_at<? OR attempts>=5').bind(now).run();await db.prepare('DELETE FROM native_devices WHERE updated_at<?').bind(now-2592000000).run();const jobs=await db.prepare("SELECT j.*,d.platform,d.environment FROM native_push_jobs j JOIN native_devices d ON d.token=j.token AND d.member=j.recipient AND d.enabled=1 WHERE j.lease_until<? AND ((d.platform='android' AND ?=1) OR (d.platform='ios' AND ?=1)) ORDER BY j.expires_at LIMIT 20").bind(now,pushReady(env,'android')?1:0,pushReady(env,'ios')?1:0).all<Job>();await Promise.all(jobs.results.map(async job=>{if(!pushReady(env,job.platform))return;const claimed=await db.prepare('UPDATE native_push_jobs SET lease_until=?,attempts=attempts+1 WHERE id=? AND lease_until<?').bind(now+60000,job.id,now).run();if(!claimed.meta.changes)return;try{const row=await db.prepare("SELECT name,owner FROM members WHERE id=? AND status='active' AND EXISTS(SELECT 1 FROM members WHERE id=? AND status='active') AND NOT EXISTS(SELECT 1 FROM member_blocks WHERE (blocker=? AND blocked=?) OR (blocker=? AND blocked=?))").bind(job.sender,job.recipient,job.sender,job.recipient,job.recipient,job.sender).first<{name:string;owner:string}>();if(!row){await db.prepare('DELETE FROM native_push_jobs WHERE id=?').bind(job.id).run();return;}const service=new CommunityService(db,row.owner);await service.conversationAccess(job.conversation,job.kind==='call');const recipient=await db.prepare("SELECT id FROM members WHERE id=? AND json_extract(privacy,'$.messages')!='Nobody'").bind(job.recipient).first();if(job.kind==='message'&&!recipient)throw Error('FORBIDDEN');let mode:string|undefined;if(job.kind==='message'){const message=await db.prepare('SELECT id FROM chat_messages WHERE id=? AND deleted=0 AND receiver_read_at IS NULL').bind(job.event_id).first();if(!message)throw Error('FORBIDDEN');}else{const call=await db.prepare("SELECT mode FROM call_sessions WHERE id=? AND state='ringing' AND offer IS NOT NULL").bind(job.event_id).first<{mode:string}>();if(!call)throw Error('FORBIDDEN');mode=call.mode;}
 const data:PushData={kind:job.kind,eventId:job.event_id,conversation:job.conversation,sender:job.sender,name:row.name,account:job.recipient,...(mode?{mode}:{})};const result=await send(env,job,data);if(result==='invalid')await db.prepare('DELETE FROM native_devices WHERE token=?').bind(job.token).run();if(result!=='retry')await db.prepare('DELETE FROM native_push_jobs WHERE id=?').bind(job.id).run();
 }catch(e){if(e instanceof Error&&['FORBIDDEN','NOT_FOUND','SUSPENDED'].includes(e.message))await db.prepare('DELETE FROM native_push_jobs WHERE id=?').bind(job.id).run();else console.warn('Native push delivery pending retry',{platform:job.platform,kind:job.kind,...pushFailureDetails(e)});}}));}
