import {DurableObject} from 'cloudflare:workers';
type Session={space:string;member:string;started:number;lastTyping:number;lastFrame:number};
export class CommunityHub extends DurableObject<Cloudflare.Env>{
 async fetch(request:Request){
  if(new URL(request.url).pathname==='/change'){for(const socket of await this.activeSockets()){try{socket.send(JSON.stringify({type:'changed'}));}catch{socket.close(1011,'Reconnect');}}return new Response(null,{status:204});}
  if(new URL(request.url).pathname==='/ticket'){const space=request.headers.get('X-Space'),member=request.headers.get('X-Member');if(request.method!=='POST'||!space||!member)return new Response(null,{status:403});const token=crypto.randomUUID();await this.ctx.storage.put('ticket:'+token,{space,member,expires:Date.now()+30000});if(!await this.ctx.storage.getAlarm())await this.ctx.storage.setAlarm(Date.now()+60000);return Response.json({ticket:token},{headers:{'Cache-Control':'private, no-store'}});}
  if(request.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});
  const ticket=request.headers.get('X-Ticket')||'',space=request.headers.get('X-Space');const session=await this.ctx.storage.transaction(async storage=>{const entry=await storage.get<{member:string;space:string;expires:number}>('ticket:'+ticket);if(entry)await storage.delete('ticket:'+ticket);return entry;});if(!session||session.expires<=Date.now()||session.space!==space)return new Response(null,{status:403});const member=session.member;
  const allowed=await this.env.DB!.prepare("SELECT sm.member FROM space_members sm JOIN members m ON m.id=sm.member JOIN interest_spaces s ON s.id=sm.space JOIN members host ON host.id=s.owner WHERE sm.space=? AND sm.member=? AND sm.status='active' AND m.status='active' AND host.status='active' AND s.archived=0 AND NOT EXISTS(SELECT 1 FROM member_blocks WHERE (blocker=m.id AND blocked=s.owner) OR (blocker=s.owner AND blocked=m.id))").bind(space,member).first();if(!allowed)return new Response(null,{status:403});
  if(this.ctx.getWebSockets().length>=100||this.ctx.getWebSockets().filter(s=>(s.deserializeAttachment() as Session).member===member).length>=4)return new Response('Room busy. Try again.',{status:503});
  const pair=new WebSocketPair(),[client,server]=Object.values(pair);server.serializeAttachment({space,member,started:Date.now(),lastTyping:0,lastFrame:0} satisfies Session);this.ctx.acceptWebSocket(server);server.send(JSON.stringify({type:'ready'}));return new Response(null,{status:101,webSocket:client});
 }
 private async activeSockets(){const sockets=this.ctx.getWebSockets(),valid:WebSocket[]=[];for(const socket of sockets){const s=socket.deserializeAttachment() as Session;if(Date.now()-s.started>600000)socket.close(4001,'Renew session');else valid.push(socket);}if(!valid.length)return [];const first=valid[0].deserializeAttachment() as Session,ids=[...new Set(valid.map(s=>(s.deserializeAttachment() as Session).member))];const rows=await this.env.DB!.prepare(`SELECT sm.member FROM space_members sm JOIN members m ON m.id=sm.member JOIN interest_spaces s ON s.id=sm.space JOIN members host ON host.id=s.owner WHERE sm.space=? AND sm.member IN (${ids.map(()=>'?').join(',')}) AND sm.status='active' AND m.status='active' AND host.status='active' AND s.archived=0 AND NOT EXISTS(SELECT 1 FROM member_blocks WHERE (blocker=m.id AND blocked=s.owner) OR (blocker=s.owner AND blocked=m.id))`).bind(first.space,...ids).all<{member:string}>();const allowed=new Set(rows.results.map(r=>r.member));return valid.filter(socket=>{const session=socket.deserializeAttachment() as Session;if(session.space!==first.space||!allowed.has(session.member)){socket.close(4003,'Access changed');return false;}return true;});}
 private async authorized(socket:WebSocket){const session=socket.deserializeAttachment() as Session;if(Date.now()-session.started>600000){socket.close(4001,'Renew session');return null;}return this.env.DB!.prepare("SELECT m.name FROM space_members sm JOIN members m ON m.id=sm.member JOIN interest_spaces s ON s.id=sm.space JOIN members host ON host.id=s.owner WHERE sm.space=? AND sm.member=? AND sm.status='active' AND m.status='active' AND host.status='active' AND s.archived=0 AND NOT EXISTS(SELECT 1 FROM member_blocks WHERE (blocker=m.id AND blocked=s.owner) OR (blocker=s.owner AND blocked=m.id))").bind(session.space,session.member).first<{name:string}>();}
 async webSocketMessage(socket:WebSocket,message:string|ArrayBuffer){
  const session=socket.deserializeAttachment() as Session;if(typeof message!=='string'||message.length>200){socket.close(1008,'Invalid frame');return;}
  if(Date.now()-session.started>600000){socket.close(4001,'Renew session');return;}
  let data;try{data=JSON.parse(message);}catch{socket.close(1008,'Invalid frame');return;}
  if(!['ping','typing'].includes(data.type))return;
  if(Date.now()-session.lastFrame<1000||data.type==='typing'&&Date.now()-session.lastTyping<3000)return;session.lastFrame=Date.now();socket.serializeAttachment(session);
  const allowed=await this.authorized(socket);
  if(!allowed){socket.send(JSON.stringify({type:'revoked'}));socket.close(4003,'Access changed');return;}
  if(data.type==='ping'){socket.send(JSON.stringify({type:'pong'}));return;}
  if(Date.now()-session.lastTyping<3000)return;session.lastTyping=Date.now();socket.serializeAttachment(session);
  const channel=String(data.channel||'');if(!/^[a-f0-9-]{36}$/.test(channel))return;const canType=await this.env.DB!.prepare("SELECT c.id FROM space_channels c JOIN space_members sm ON sm.space=c.space WHERE c.id=? AND c.space=? AND c.archived=0 AND sm.member=? AND sm.status='active' AND sm.muted_until<? AND (c.read_only=0 OR sm.role IN ('owner','moderator'))").bind(channel,session.space,session.member,Date.now()).first();if(!canType)return;
  const blockRows=await this.env.DB!.prepare('SELECT blocker,blocked FROM member_blocks WHERE blocker=? OR blocked=?').bind(session.member,session.member).all<{blocker:string;blocked:string}>();const blocked=new Set(blockRows.results.map(r=>r.blocker===session.member?r.blocked:r.blocker));
  for(const target of await this.activeSockets()){const other=target.deserializeAttachment() as Session;if(other.member===session.member||blocked.has(other.member))continue;try{target.send(JSON.stringify({type:'typing',member:session.member,name:allowed.name,channel}));}catch{target.close(1011,'Reconnect');}}
 }
 async alarm(){const entries=await this.ctx.storage.list<{expires:number}>({prefix:'ticket:',limit:1000});const expired=[...entries].filter(([,v])=>v.expires<=Date.now()).map(([k])=>k);if(expired.length)await this.ctx.storage.delete(expired);if(entries.size>=1000||entries.size>expired.length)await this.ctx.storage.setAlarm(Date.now()+60000);}
 webSocketClose(socket:WebSocket,code:number){socket.close(code);}
 webSocketError(socket:WebSocket){socket.close(1011,'Reconnect');}
}
