import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {db,guard,identity,payload,failure} from '@/lib/server';
import {cookies} from 'next/headers';
import {nativeDeviceId,NativeDevices} from '@/lib/native-push-service';
import {pushReady} from '@/lib/native-push-provider';
const schema=z.discriminatedUnion('action',[z.object({action:z.literal('register'),platform:z.enum(['android','ios']),environment:z.enum(['production','sandbox']).default('production'),token:z.string().min(32).max(4096).regex(/^[A-Za-z0-9:_-]+$/)}),z.object({action:z.literal('remove'),token:z.string().min(32).max(4096)})]);
export async function GET(){try{const user=await identity();if(!user)throw Error('UNAUTHORIZED');const device=(await cookies()).get('yaaro_native_device')?.value;const registered=device?!!await db().prepare("SELECT 1 FROM native_devices d JOIN members m ON m.id=d.member WHERE d.device_id=? AND m.owner=? AND d.enabled=1 AND d.updated_at>?").bind(device,user.userId,Date.now()-2592000000).first():false;return Response.json({android:pushReady(env,'android'),ios:pushReady(env,'ios'),registered},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(req:Request){try{const user=await guard(req),a=schema.parse(await payload(req)),service=new NativeDevices(db(),user.userId);if(a.action==='register'){if(!pushReady(env,a.platform))return Response.json({error:'App notifications are awaiting configuration.'},{status:503});if(a.platform==='ios'&&(!/^[a-fA-F0-9]{32,512}$/.test(a.token)||a.token.length%2!==0))throw Error('INVALID');const jar=await cookies(),old=jar.get('yaaro_native_device')?.value;if(old)await service.removeDevice(old);const result=await service.register(a.token,a.platform,a.platform==='ios'&&env.APNS_ENVIRONMENT==='sandbox'?'sandbox':'production');jar.set('yaaro_native_device',await nativeDeviceId(a.token),{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:2592000});return Response.json(result);}const result=await service.remove(a.token);(await cookies()).delete('yaaro_native_device');return Response.json(result);}catch(e){return failure(e);}}
