import {sql} from 'drizzle-orm';
import { sqliteTable, text, integer, index, uniqueIndex, primaryKey, check, type AnySQLiteColumn } from 'drizzle-orm/sqlite-core';
export const workspaces = sqliteTable('demo_workspaces', { owner: text('owner').primaryKey(), data: text('data').notNull(), updatedAt: integer('updated_at').notNull() });
export const reports = sqliteTable('reports', { id:text('id').primaryKey(), owner:text('owner').notNull(), target:text('target').notNull(), category:text('category').notNull(), description:text('description').notNull(), status:text('status').notNull().default('Pending'), createdAt:integer('created_at').notNull() },t=>[index('idx_reports_owner').on(t.owner)]);
export const audit = sqliteTable('audit_logs', { id:text('id').primaryKey(), actor:text('actor').notNull(), action:text('action').notNull(), target:text('target').notNull(), createdAt:integer('created_at').notNull() });
export const events = sqliteTable('product_events', { id:text('id').primaryKey(), owner:text('owner').notNull(), event:text('event').notNull(), createdAt:integer('created_at').notNull() },t=>[index('idx_events_owner_time').on(t.owner,t.createdAt)]);
export const waitlist = sqliteTable('business_waitlist', { owner:text('owner').primaryKey(), company:text('company').notNull(), email:text('email').notNull(), createdAt:integer('created_at').notNull() });

// Consumer-community records stay separate from fictional demo workspaces.
export const members = sqliteTable('members', { id:text('id').primaryKey(), owner:text('owner').notNull(), name:text('name').notNull(), dob:text('dob').notNull(), languages:text('languages').notNull(), interests:text('interests').notNull(), bio:text('bio').notNull(), vibe:text('vibe').notNull(), avatar:text('avatar').notNull(), photoKey:text('photo_key'), region:text('region').notNull().default('Prefer not to say'), privacy:text('privacy').notNull(), published:integer('published').notNull().default(1), status:text('status').notNull().default('active'), createdAt:integer('created_at').notNull(), lastSeen:integer('last_seen').notNull() },t=>[uniqueIndex('idx_members_owner').on(t.owner),index('idx_members_published_status').on(t.published,t.status)]);
export const friendships = sqliteTable('friendships', { id:text('id').primaryKey(), memberA:text('member_a').notNull(), memberB:text('member_b').notNull(), requester:text('requester').notNull(), status:text('status').notNull().default('pending'), createdAt:integer('created_at').notNull(), updatedAt:integer('updated_at').notNull(), readA:integer('read_a').notNull().default(0), readB:integer('read_b').notNull().default(0) },t=>[index('idx_friendships_a').on(t.memberA),index('idx_friendships_b').on(t.memberB)]);
export const realMessages=sqliteTable('chat_messages',{id:text('id').primaryKey(),conversation:text('conversation').notNull(),author:text('author').notNull(),body:text('body').notNull(),disappearing:integer('disappearing').notNull().default(0),receiverReadAt:integer('receiver_read_at'),replyId:text('reply_id'),deleted:integer('deleted').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('idx_chat_conversation_time').on(t.conversation,t.createdAt)]);
export const realBlocks=sqliteTable('member_blocks',{id:text('id').primaryKey(),blocker:text('blocker').notNull(),blocked:text('blocked').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_blocks_blocker').on(t.blocker),index('idx_blocks_blocked').on(t.blocked)]);
export const reactions=sqliteTable('chat_reactions',{id:text('id').primaryKey(),message:text('message').notNull(),member:text('member').notNull(),emoji:text('emoji').notNull()},t=>[index('idx_reactions_message').on(t.message)]);

export const callSessions=sqliteTable('call_sessions',{id:text('id').primaryKey(),conversation:text('conversation').notNull(),caller:text('caller').notNull(),callee:text('callee').notNull(),mode:text('mode').notNull(),state:text('state').notNull().default('ringing'),offer:text('offer'),answer:text('answer'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('idx_calls_caller_state').on(t.caller,t.state),index('idx_calls_callee_state').on(t.callee,t.state)]);

export const chatPreferences=sqliteTable('chat_preferences',{member:text('member').notNull().references(()=>members.id,{onDelete:'cascade'}),target:text('target').notNull().references(()=>members.id,{onDelete:'cascade'}),pinned:integer('pinned').notNull().default(0),favorite:integer('favorite').notNull().default(0),disappearing:integer('disappearing').notNull().default(0),updatedAt:integer('updated_at').notNull()},t=>[primaryKey({columns:[t.member,t.target]}),check('chat_preferences_flags',sql`${t.pinned} IN (0, 1) AND ${t.favorite} IN (0, 1)`)]);

export const chatMedia=sqliteTable('chat_media',{id:text('id').primaryKey(),message:text('message').notNull().unique().references(()=>realMessages.id,{onDelete:'cascade'}),conversation:text('conversation').notNull(),storageKey:text('storage_key').notNull(),kind:text('kind').notNull(),contentType:text('content_type').notNull(),createdAt:integer('created_at').notNull()},t=>[index('chat_media_conversation').on(t.conversation),check('chat_media_kind',sql`${t.kind} IN ('photo','voice','video')`)]);
export const memberMoments=sqliteTable('member_moments',{id:text('id').primaryKey(),author:text('author').notNull().references(()=>members.id),body:text('body').notNull().default(''),photoKey:text('photo_key'),mediaKind:text('media_kind').notNull().default('photo'),visibility:text('visibility').notNull(),expiresAt:integer('expires_at'),createdAt:integer('created_at').notNull()},t=>[index('member_moments_feed').on(t.author,t.createdAt),check('member_moments_visibility',sql`${t.visibility} IN ('friends','private','everyone','selected')`)]);

export const momentRecipients=sqliteTable('moment_recipients',{moment:text('moment').notNull().references(()=>memberMoments.id,{onDelete:'cascade'}),member:text('member').notNull().references(()=>members.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.moment,t.member]})]);
export const momentViews=sqliteTable('moment_views',{moment:text('moment').notNull().references(()=>memberMoments.id,{onDelete:'cascade'}),member:text('member').notNull().references(()=>members.id,{onDelete:'cascade'}),viewedAt:integer('viewed_at').notNull()},t=>[primaryKey({columns:[t.moment,t.member]})]);

export const mediaCleanup=sqliteTable('media_cleanup',{storageKey:text('storage_key').primaryKey()});
export const chatPresence=sqliteTable('chat_presence',{member:text('member').notNull().references(()=>members.id,{onDelete:'cascade'}),conversation:text('conversation').notNull(),touchedAt:integer('touched_at').notNull()},t=>[primaryKey({columns:[t.member,t.conversation]})]);
export const chatMediaViews=sqliteTable('chat_media_views',{message:text('message').primaryKey().references(()=>realMessages.id,{onDelete:'cascade'}),viewer:text('viewer').notNull().references(()=>members.id,{onDelete:'cascade'}),openedAt:integer('opened_at').notNull()});

// Persistent interest communities. Authorization lives in SpacesService, never in client roles.
export const interestSpaces=sqliteTable('interest_spaces',{id:text('id').primaryKey(),owner:text('owner').notNull().references(()=>members.id),name:text('name').notNull(),description:text('description').notNull(),topic:text('topic').notNull(),language:text('language').notNull(),access:text('access').notNull(),rules:text('rules').notNull(),visibility:text('visibility').notNull().default('public'),handle:text('handle'),purpose:text('purpose').notNull().default('Friendship'),subcategory:text('subcategory').notNull().default(''),logoKey:text('logo_key'),coverKey:text('cover_key'),archived:integer('archived').notNull().default(0),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('space_unique_handle').on(t.handle),index('spaces_visibility_updated').on(t.visibility,t.archived,t.updatedAt),check('space_access',sql`${t.access} IN ('open','approval')`)]);
export const spaceMembers=sqliteTable('space_members',{space:text('space').notNull().references(()=>interestSpaces.id,{onDelete:'cascade'}),member:text('member').notNull().references(()=>members.id),role:text('role').notNull().default('member'),status:text('status').notNull(),notifications:integer('notifications').notNull().default(1),mutedUntil:integer('muted_until').notNull().default(0),joinedAt:integer('joined_at').notNull()},t=>[primaryKey({columns:[t.space,t.member]}),index('space_members_person').on(t.member,t.status),check('space_member_role',sql`${t.role} IN ('owner','moderator','member')`),check('space_member_status',sql`${t.status} IN ('active','pending','declined','banned','left')`),check('space_notification_flag',sql`${t.notifications} IN (0,1)`)]);
export const spaceChannels=sqliteTable('space_channels',{id:text('id').primaryKey(),space:text('space').notNull().references(()=>interestSpaces.id,{onDelete:'cascade'}),name:text('name').notNull(),description:text('description').notNull().default(''),readOnly:integer('read_only').notNull().default(0),archived:integer('archived').notNull().default(0),position:integer('position').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('space_channel_name').on(t.space,t.name)]);
export const spacePosts=sqliteTable('space_posts',{id:text('id').primaryKey(),space:text('space').notNull().references(()=>interestSpaces.id,{onDelete:'cascade'}),channel:text('channel').notNull().references(()=>spaceChannels.id),author:text('author').notNull().references(()=>members.id),parent:text('parent').references(():AnySQLiteColumn=>spacePosts.id,{onDelete:'cascade'}),kind:text('kind').notNull(),body:text('body').notNull(),options:text('options'),pollEnds:integer('poll_ends'),pinned:integer('pinned').notNull().default(0),acceptedReply:text('accepted_reply').references(():AnySQLiteColumn=>spacePosts.id),locked:integer('locked').notNull().default(0),editedAt:integer('edited_at'),deleted:integer('deleted').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('space_posts_feed').on(t.space,t.channel,t.parent,t.createdAt),index('space_posts_thread').on(t.parent,t.createdAt),check('space_post_kind',sql`${t.kind} IN ('discussion','question','announcement','poll')`)]);
export const spaceVotes=sqliteTable('space_votes',{post:text('post').notNull().references(()=>spacePosts.id,{onDelete:'cascade'}),member:text('member').notNull().references(()=>members.id),choice:integer('choice').notNull()},t=>[primaryKey({columns:[t.post,t.member]})]);
export const spaceLikes=sqliteTable('space_likes',{post:text('post').notNull().references(()=>spacePosts.id,{onDelete:'cascade'}),member:text('member').notNull().references(()=>members.id)},t=>[primaryKey({columns:[t.post,t.member]})]);
export const spaceSaves=sqliteTable('space_saves',{post:text('post').notNull().references(()=>spacePosts.id,{onDelete:'cascade'}),member:text('member').notNull().references(()=>members.id)},t=>[primaryKey({columns:[t.post,t.member]})]);
export const spaceResources=sqliteTable('space_resources',{id:text('id').primaryKey(),space:text('space').notNull().references(()=>interestSpaces.id,{onDelete:'cascade'}),author:text('author').notNull().references(()=>members.id),title:text('title').notNull(),description:text('description').notNull(),url:text('url').notNull(),createdAt:integer('created_at').notNull()},t=>[index('space_resources_feed').on(t.space,t.createdAt)]);
export const spaceEvents=sqliteTable('space_events',{id:text('id').primaryKey(),space:text('space').notNull().references(()=>interestSpaces.id,{onDelete:'cascade'}),host:text('host').notNull().references(()=>members.id),title:text('title').notNull(),description:text('description').notNull(),startsAt:integer('starts_at').notNull(),duration:integer('duration').notNull(),url:text('url').notNull().default(''),cancelled:integer('cancelled').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('space_events_schedule').on(t.space,t.startsAt)]);
export const spaceRsvps=sqliteTable('space_rsvps',{event:text('event').notNull().references(()=>spaceEvents.id,{onDelete:'cascade'}),member:text('member').notNull().references(()=>members.id),response:text('response').notNull()},t=>[primaryKey({columns:[t.event,t.member]}),check('space_rsvp_response',sql`${t.response} IN ('going','interested')`)]);
export const spaceReports=sqliteTable('space_reports',{id:text('id').primaryKey().references(()=>reports.id),space:text('space').references(()=>interestSpaces.id,{onDelete:'set null'}),post:text('post').references(()=>spacePosts.id,{onDelete:'set null'}),resource:text('resource').references(()=>spaceResources.id,{onDelete:'set null'}),message:text('message').references(()=>spaceMessages.id,{onDelete:'set null'}),evidence:text('evidence').notNull().default(''),reporter:text('reporter').notNull().references(()=>members.id),target:text('target').notNull().references(()=>members.id),category:text('category').notNull(),description:text('description').notNull(),status:text('status').notNull().default('pending'),createdAt:integer('created_at').notNull()},t=>[index('space_reports_queue').on(t.space,t.status,t.createdAt)]);
export const spaceNotifications=sqliteTable('space_notifications',{id:text('id').primaryKey(),recipient:text('recipient').notNull().references(()=>members.id),space:text('space').notNull().references(()=>interestSpaces.id,{onDelete:'cascade'}),title:text('title').notNull(),body:text('body').notNull(),seen:integer('seen').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('space_notifications_person').on(t.recipient,t.seen,t.createdAt)]);

export const spaceInvites=sqliteTable('space_invites',{tokenHash:text('token_hash').primaryKey(),space:text('space').notNull().references(()=>interestSpaces.id,{onDelete:'cascade'}),creator:text('creator').notNull().references(()=>members.id),expiresAt:integer('expires_at').notNull(),maxUses:integer('max_uses').notNull(),uses:integer('uses').notNull().default(0),revoked:integer('revoked').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('space_invites_management').on(t.space,t.createdAt)]);
export const spaceInviteRedemptions=sqliteTable('space_invite_redemptions',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull().references(()=>spaceInvites.tokenHash),member:text('member').notNull().references(()=>members.id),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('space_invite_person').on(t.tokenHash,t.member)]);
export const spaceMessages=sqliteTable('space_messages',{id:text('id').primaryKey(),space:text('space').notNull().references(()=>interestSpaces.id,{onDelete:'cascade'}),channel:text('channel').notNull().references(()=>spaceChannels.id),author:text('author').notNull().references(()=>members.id),body:text('body').notNull(),replyId:text('reply_id').references(():AnySQLiteColumn=>spaceMessages.id),deleted:integer('deleted').notNull().default(0),editedAt:integer('edited_at'),createdAt:integer('created_at').notNull()},t=>[index('space_messages_history').on(t.space,t.channel,t.createdAt,t.id)]);
export const spaceChannelFollows=sqliteTable('space_channel_follows',{channel:text('channel').notNull().references(()=>spaceChannels.id,{onDelete:'cascade'}),member:text('member').notNull().references(()=>members.id)},t=>[primaryKey({columns:[t.channel,t.member]})]);
export const spaceDiscussionFollows=sqliteTable('space_discussion_follows',{post:text('post').notNull().references(()=>spacePosts.id,{onDelete:'cascade'}),member:text('member').notNull().references(()=>members.id)},t=>[primaryKey({columns:[t.post,t.member]})]);
