import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const workspaces = sqliteTable('demo_workspaces', { owner: text('owner').primaryKey(), data: text('data').notNull(), updatedAt: integer('updated_at').notNull() });
export const reports = sqliteTable('reports', { id:text('id').primaryKey(), owner:text('owner').notNull(), target:text('target').notNull(), category:text('category').notNull(), description:text('description').notNull(), status:text('status').notNull().default('Pending'), createdAt:integer('created_at').notNull() },t=>[index('idx_reports_owner').on(t.owner)]);
export const audit = sqliteTable('audit_logs', { id:text('id').primaryKey(), actor:text('actor').notNull(), action:text('action').notNull(), target:text('target').notNull(), createdAt:integer('created_at').notNull() });
export const events = sqliteTable('product_events', { id:text('id').primaryKey(), owner:text('owner').notNull(), event:text('event').notNull(), createdAt:integer('created_at').notNull() },t=>[index('idx_events_owner_time').on(t.owner,t.createdAt)]);
export const waitlist = sqliteTable('business_waitlist', { owner:text('owner').primaryKey(), company:text('company').notNull(), email:text('email').notNull(), createdAt:integer('created_at').notNull() });

// Consumer-community records stay separate from fictional demo workspaces.
export const members = sqliteTable('members', { id:text('id').primaryKey(), owner:text('owner').notNull(), name:text('name').notNull(), dob:text('dob').notNull(), languages:text('languages').notNull(), interests:text('interests').notNull(), bio:text('bio').notNull(), vibe:text('vibe').notNull(), avatar:text('avatar').notNull(), photoKey:text('photo_key'), region:text('region').notNull().default('Prefer not to say'), privacy:text('privacy').notNull(), published:integer('published').notNull().default(1), status:text('status').notNull().default('active'), createdAt:integer('created_at').notNull(), lastSeen:integer('last_seen').notNull() },t=>[uniqueIndex('idx_members_owner').on(t.owner),index('idx_members_published_status').on(t.published,t.status)]);
export const friendships = sqliteTable('friendships', { id:text('id').primaryKey(), memberA:text('member_a').notNull(), memberB:text('member_b').notNull(), requester:text('requester').notNull(), status:text('status').notNull().default('pending'), createdAt:integer('created_at').notNull(), updatedAt:integer('updated_at').notNull(), readA:integer('read_a').notNull().default(0), readB:integer('read_b').notNull().default(0) },t=>[index('idx_friendships_a').on(t.memberA),index('idx_friendships_b').on(t.memberB)]);
export const realMessages=sqliteTable('chat_messages',{id:text('id').primaryKey(),conversation:text('conversation').notNull(),author:text('author').notNull(),body:text('body').notNull(),replyId:text('reply_id'),deleted:integer('deleted').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('idx_chat_conversation_time').on(t.conversation,t.createdAt)]);
export const realBlocks=sqliteTable('member_blocks',{id:text('id').primaryKey(),blocker:text('blocker').notNull(),blocked:text('blocked').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_blocks_blocker').on(t.blocker),index('idx_blocks_blocked').on(t.blocked)]);
export const reactions=sqliteTable('chat_reactions',{id:text('id').primaryKey(),message:text('message').notNull(),member:text('member').notNull(),emoji:text('emoji').notNull()},t=>[index('idx_reactions_message').on(t.message)]);

export const callSessions=sqliteTable('call_sessions',{id:text('id').primaryKey(),conversation:text('conversation').notNull(),caller:text('caller').notNull(),callee:text('callee').notNull(),mode:text('mode').notNull(),state:text('state').notNull().default('ringing'),offer:text('offer'),answer:text('answer'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('idx_calls_caller_state').on(t.caller,t.state),index('idx_calls_callee_state').on(t.callee,t.state)]);
