import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
const out=new URL('../.sites-runtime/explore-tests/',import.meta.url);mkdirSync(out,{recursive:true});
for(const name of ['data','community-model','community-service','explore-model','explore-service','call-service']){let source=readFileSync(new URL(`../lib/${name}.ts`,import.meta.url),'utf8');for(const dependency of ['data','community-model','community-service','explore-model'])source=source.replaceAll(`'./${dependency}'`,`'./${dependency}.mjs'`);writeFileSync(new URL(name+'.mjs',out),ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);}
const {CommunityService}=await import(new URL('community-service.mjs',out));const {ExploreService}=await import(new URL('explore-service.mjs',out));const {CallService}=await import(new URL('call-service.mjs',out));const {exploreAction}=await import(new URL('explore-model.mjs',out));const {defaults}=await import(new URL('community-model.mjs',out));
const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));
class Statement{constructor(query,params=[]){this.query=query;this.params=params;}bind(...params){return new Statement(this.query,params);}async first(){return sql.prepare(this.query).get(...this.params)||null;}async all(){return {results:sql.prepare(this.query).all(...this.params)};}async run(){return {meta:{changes:Number(sql.prepare(this.query).run(...this.params).changes)}};}}
const db={prepare:q=>new Statement(q),async batch(ss){sql.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const profile=(name,region='Bengaluru')=>({name,dob:'2000-01-15',languages:['English','Tamil'],interests:['Music','Movies','Travel'],bio:'Hello',vibe:'Chill',avatar:'😌',region});
const people=[];for(let i=0;i<8;i++){const community=new CommunityService(db,'explorer-'+i);await community.act({action:'profile',profile:profile('Explorer '+i,i===2?'Chennai':i===3?'Prefer not to say':'Bengaluru'),consent:true});people.push({c:community,e:new ExploreService(db,'explorer-'+i),call:new CallService(db,'explorer-'+i),id:await community.memberId()});}
const [a,b,c,d,e,f,g,h]=people;let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};const denied=async(fn,code='FORBIDDEN')=>{await assert.rejects(fn,x=>x.message===code);checks++;};
const join=(p,filters={})=>p.e.act(exploreAction.parse({action:'join',filters:{mode:'text',...filters}}));
const finish=async(p,s,decision='skip')=>p.e.act({action:'decision',session:s.session.id,ticket:s.ticket,decision});
let aa=await join(a,{region:'Bengaluru'});ok(aa.waiting,'First person waits honestly');let cc=await join(c);ok(cc.waiting,'Filters apply to the other profile');let dd=await join(d,{mode:'voice'});ok(dd.waiting,'Different modes do not match');let bb=await join(b);aa=await a.e.state(aa.ticket);ok(aa.session.peer.id===b.id&&bb.session.peer.id===a.id,'New users match without an existing friendship');ok((await a.c.snapshot()).connections.length===0,'Temporary match is absent from normal inbox');ok(!('owner' in aa.session.peer)&&!('dob' in aa.session.peer),'Match exposes display profile only');
await denied(()=>c.c.conversationAccess(aa.session.id));await denied(()=>a.call.act({action:'start',id:crypto.randomUUID(),conversation:aa.session.id,mode:'voice'}));
const message={action:'message',ticket:aa.ticket,session:aa.session.id,id:crypto.randomUUID(),body:'Hello stranger'};await a.e.act(message);await a.e.act(message);bb=await b.e.state(bb.ticket);ok(bb.session.messages.length===1,'Text delivery is idempotent and visible to matched peer');await denied(()=>c.e.act({...message,ticket:cc.ticket,id:crypto.randomUUID()}));for(let i=0;i<32;i++)await a.e.act({...message,id:crypto.randomUUID(),body:'Message '+i});ok((await a.e.state(aa.ticket)).session.messages.length===30,'Ephemeral text retains only latest 30 messages');
await a.e.act({action:'end',ticket:aa.ticket,session:aa.session.id});ok((await b.e.state(bb.ticket)).session.state==='ended','Either person ends the shared session');ok(sql.prepare('SELECT COUNT(*) n FROM explore_messages WHERE session_id=?').get(aa.session.id).n===0,'End immediately removes all temporary messages');await denied(()=>a.e.act({...message,id:crypto.randomUUID()}));await finish(a,aa);await finish(b,bb);ok(sql.prepare('SELECT COUNT(*) n FROM explore_sessions WHERE id=?').get(aa.session.id).n===0,'Both skips purge session metadata');ok((await b.c.snapshot()).connections.length===0,'Both skips create no connection history');
// Same users are eligible in a later search; no permanent exclusion is written.
aa=await join(a,{region:'Bengaluru'});bb=await join(b,{region:'Bengaluru'});aa=await a.e.state(aa.ticket);ok(aa.session.peer.id===b.id,'Same pair can meet again naturally');await finish(a,aa,'request');const request=(await b.c.snapshot()).connections[0];ok(request.status==='pending'&&request.requester===a.id,'One connect becomes a normal pending request');await finish(b,bb,'skip');ok((await b.c.snapshot()).connections[0].status==='pending','Passing does not erase the other person’s normal request');await b.c.act({action:'connection',id:request.id,decision:'accept'});ok((await a.c.snapshot()).connections[0].status==='accepted','Recipient can accept from normal request center');
await c.e.act({action:'cancel',ticket:cc.ticket});await d.e.act({action:'cancel',ticket:dd.ticket});
// Explicit exploration is separate from private online-status visibility.
ok(!(await e.c.snapshot()).people.find(p=>p.id===f.id).online,'Normal online state stays private');let ee=await join(e,{mode:'video',region:'Bengaluru'}),ff=await join(f,{mode:'video',region:'Bengaluru'});ee=await e.e.state(ee.ticket);ok(ee.session.peer.id===f.id,'Explorers match even with connection-only online visibility');await denied(()=>e.call.act({action:'start',id:crypto.randomUUID(),conversation:ee.session.id,mode:'voice'}),'BUSY');const callId=crypto.randomUUID();await e.call.act({action:'start',id:callId,conversation:ee.session.id,mode:'video'});ok((await e.call.get(callId)).callee===f.id,'Existing secure signaling supports a temporary video pair');await e.call.act({action:'end',id:callId});ok((await f.e.state(ff.ticket)).session.state==='ended','Hanging up prompts both exploration participants');await finish(e,ee);await finish(f,ff);ok(sql.prepare('SELECT COUNT(*) n FROM call_sessions WHERE id=?').get(callId).n===0,'Both passes purge temporary call records');
// Android's matched receiver can initiate through the same consent/signaling
// path. The other participant gets the offer; crossed calls stay blocked.
ee=await join(e,{mode:'voice'});ff=await join(f,{mode:'voice'});ee=await e.e.state(ee.ticket);ok(!ee.session.caller,'Fixture represents the previously waiting receiver');const reverseCall=crypto.randomUUID();await e.call.act({action:'start',id:reverseCall,conversation:ee.session.id,mode:'voice'});await denied(()=>f.call.act({action:'start',id:crypto.randomUUID(),conversation:ee.session.id,mode:'voice'}),'BUSY');await e.call.act({action:'offer',id:reverseCall,sdp:'v=0\r\n'});ok((await f.call.get()).id===reverseCall,'Receiver-initiated call reaches the other participant');await f.call.act({action:'accept',id:reverseCall});ok((await e.call.get(reverseCall)).state==='connecting','Normal explicit Accept remains required');await e.call.act({action:'end',id:reverseCall});await finish(e,ee);await finish(f,ff);
// Both explicitly requesting each other produces mutual acceptance.
let gg=await join(g),hh=await join(h);gg=await g.e.state(gg.ticket);await finish(g,gg,'request');await finish(h,hh,'request');ok((await g.c.snapshot()).connections[0].status==='accepted','Two connect choices establish a mutual friendship');
// Block and privacy controls immediately revoke temporary access.
ee=await join(e);ff=await join(f);ee=await e.e.state(ee.ticket);await e.c.act({action:'block',target:f.id});ok((await f.e.state(ff.ticket)).session.state==='ended','Block immediately ends a temporary conversation');await finish(e,ee);await finish(f,ff);ee=await join(e);ff=await join(f);ok(ee.waiting&&ff.waiting,'Blocked pair is excluded from matching');await e.e.act({action:'cancel',ticket:ee.ticket});await f.e.act({action:'cancel',ticket:ff.ticket});await e.c.act({action:'unblock',target:f.id});
ee=await join(e);ff=await join(f);ee=await e.e.state(ee.ticket);await e.c.act({action:'privacy',privacy:{...defaults,messages:'Nobody'},published:true});ok((await f.e.state(ff.ticket)).session.state==='ended','Turning messages off ends text exploration');await finish(e,ee);await finish(f,ff);await denied(()=>join(e));await e.c.act({action:'privacy',privacy:defaults,published:true});
// Atomic ownership: active participant cannot be taken by a third search.
ee=await join(e,{region:'Bengaluru'});ff=await join(f,{region:'Bengaluru'});ee=await e.e.state(ee.ticket);await denied(()=>join(e),'BUSY');cc=await join(c,{region:'Bengaluru'});ok(cc.waiting,'Third explorer cannot claim an active participant');await denied(()=>e.e.act({action:'cancel',ticket:crypto.randomUUID()}),'NOT_FOUND');sql.prepare('UPDATE explore_queue SET touched_at=? WHERE member=?').run(Date.now()-46000,f.id);await e.e.cleanup();ok((await e.e.state(ee.ticket)).session.state==='ended','Lost heartbeat ends and clears abandoned sessions');sql.prepare('UPDATE explore_sessions SET ended_at=? WHERE id=?').run(Date.now()-901000,ee.session.id);await e.e.cleanup();ok(sql.prepare('SELECT COUNT(*) n FROM explore_sessions WHERE id=?').get(ee.session.id).n===0,'Expired post-session prompts are purged');
assert.throws(()=>exploreAction.parse({action:'join',filters:{mode:'text',region:'123 street'}}));checks++;ok(sql.prepare('SELECT COUNT(*) n FROM explore_messages').get().n===0,'No ended session leaves temporary text behind');
// Exercise the real POST route: start includes authorized relay configuration and
// relay failure closes the new call instead of leaving an orphan ringing row.
globalThis.callRouteTest={db,user:'explorer-4',relayFails:false};
writeFileSync(new URL('api-test-env.mjs',out),"export const env={};");
writeFileSync(new URL('api-test-server.mjs',out),`export const db=()=>globalThis.callRouteTest.db;export const identity=async()=>({userId:globalThis.callRouteTest.user});export const guard=async()=>{if(!globalThis.callRouteTest.user)throw new Error('UNAUTHORIZED');return identity();};export const payload=req=>req.json();export const failure=e=>Response.json({error:e.message},{status:e.message==='UNAUTHORIZED'?401:503});`);
writeFileSync(new URL('api-test-turn.mjs',out),`export const relayReady=()=>true;export async function relayServers(env,id,me){const row=await globalThis.callRouteTest.db.prepare('SELECT * FROM call_sessions WHERE id=?').bind(id).first();if(!row||![row.caller,row.callee].includes(me))throw new Error('FORBIDDEN');if(globalThis.callRouteTest.relayFails)throw new Error('RELAY_FAILED');return [{urls:'turn:relay.example:3478',username:'test-only',credential:'test-only'}];}`);
let route=readFileSync(new URL('../app/api/calls/route.ts',import.meta.url),'utf8').replaceAll("'cloudflare:workers'","'./api-test-env.mjs'").replaceAll("'@/lib/server'","'./api-test-server.mjs'").replaceAll("'@/lib/call-service'","'./call-service.mjs'").replaceAll("'@/lib/turn-provider'","'./api-test-turn.mjs'");
writeFileSync(new URL('api-calls.mjs',out),ts.transpileModule(route,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const {POST}=await import(new URL('api-calls.mjs',out));
const startRoute=(id,session)=>POST(new Request('https://yaaro.example/api/calls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'start',id,conversation:session,mode:'voice'})}));
ee=await join(e,{mode:'voice'});ff=await join(f,{mode:'voice'});ee=await e.e.state(ee.ticket);const routeCall=crypto.randomUUID();let response=await startRoute(routeCall,ee.session.id);let result=await response.json();ok(response.status===200&&result.iceServers.length===1&&result.iceTransportPolicy==='relay','Start returns authorized relay configuration in one response');ok(response.headers.get('Cache-Control')==='no-store','Relay credentials are not cacheable');await e.call.act({action:'end',id:routeCall});await finish(e,ee);await finish(f,ff);
ee=await join(e,{mode:'voice'});ff=await join(f,{mode:'voice'});ee=await e.e.state(ee.ticket);const failedCall=crypto.randomUUID();globalThis.callRouteTest.relayFails=true;response=await startRoute(failedCall,ee.session.id);ok(response.status===503,'Relay failure is reported instead of claiming a connected call');ok(sql.prepare('SELECT state FROM call_sessions WHERE id=?').get(failedCall).state==='ended','Failed relay preparation leaves no ringing call');await finish(e,ee);await finish(f,ff);
globalThis.callRouteTest.user=null;response=await startRoute(crypto.randomUUID(),crypto.randomUUID());ok(response.status===401,'Unauthenticated start cannot obtain relay credentials');delete globalThis.callRouteTest;
console.log(`${checks} exploration matching, filtering, consent, call access, request and cleanup checks passed`);
