import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {db,identity,failure} from '@/lib/server';
import {CommunityService} from '@/lib/community-service';
import {normalizePhoto} from '@/lib/photo-validation';
async function uploadGuard(req:Request){const u=await identity();if(!u)throw new Error('UNAUTHORIZED');if(req.headers.get('origin')!==new URL(req.url).origin)throw new Error('FORBIDDEN');if(!env.BUCKET)throw new Error('STORAGE');const now=Date.now();const r=await db().prepare("INSERT INTO product_events (id, owner, event, created_at) SELECT ?, ?, 'photo_write', ? WHERE (SELECT COUNT(*) FROM product_events WHERE owner = ? AND event = 'photo_write' AND created_at > ?) < 3").bind(crypto.randomUUID(),u.userId,now,u.userId,now-60000).run();if(!r.meta.changes)throw new Error('RATE');return new CommunityService(db(),u.userId);}
export async function GET(req:Request){try{const u=await identity();if(!u)throw new Error('UNAUTHORIZED');const id=z.string().uuid().parse(new URL(req.url).searchParams.get('member'));const key=await new CommunityService(db(),u.userId).photo(id);if(!key||!env.BUCKET)throw new Error('NOT_FOUND');const o=await env.BUCKET.get(key);if(!o)throw new Error('NOT_FOUND');return new Response(o.body,{headers:{'Content-Type':'image/png','Content-Disposition':'inline; filename="yaaro-profile.png"','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox",'Cache-Control':'private, no-store'}});}catch(e){return failure(e);}}
export async function POST(req:Request){try{const s=await uploadGuard(req);if(req.headers.get('content-type')!=='image/png'||Number(req.headers.get('content-length')||0)>1048576)throw new Error('INVALID');const own=await s.ownPhoto();const reader=req.body?.getReader();if(!reader)throw new Error('INVALID');let size=0;const parts:Uint8Array[]=[];while(true){const p=await reader.read();if(p.done)break;size+=p.value.length;if(size>1048576){await reader.cancel();throw new Error('INVALID');}parts.push(p.value);}const bytes=new Uint8Array(size);let at=0;for(const p of parts){bytes.set(p,at);at+=p.length;}let prepared:Uint8Array;try{prepared=normalizePhoto(bytes);}catch(error){console.warn(JSON.stringify({event:'profile_photo_rejected',stage:'png_validation',code:error instanceof Error&&/^INVALID_PNG_[A-Z_]+$/.test(error.message)?error.message:'INVALID_PNG',bytes:size}));return Response.json({error:'Your prepared photo could not be validated. Choose another photo or take a new one with Camera.'},{status:400,headers:{'Cache-Control':'no-store'}});}const key=`profiles/${own.id}/${crypto.randomUUID()}.png`;await env.BUCKET!.put(key,prepared,{httpMetadata:{contentType:'image/png'}});try{await s.savePhoto(key);}catch(e){await env.BUCKET!.delete(key);throw e;}if(own.key)await env.BUCKET!.delete(own.key).catch(()=>{});return Response.json({saved:true},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function DELETE(req:Request){try{const s=await uploadGuard(req);const own=await s.ownPhoto();await s.savePhoto(null);if(own.key)await env.BUCKET!.delete(own.key);return Response.json({saved:true});}catch(e){return failure(e);}}
